sPHENIX-Collaboration/macros

macros/g4simulations/G4_CEmc_Spacal.C

Macro to use a new cell builder to group hit in each 10M SPACAL fiber separately in each cell (which allow us to implement fiber-fiber light collection eff. when needed) . This patch is needed to use the SPACAL tower as in engineering drawing, which currently is done in simple eta-phi or z binning.
This also pre-require this pull request in the coresoftware to be merged/compiled:
https://github.com/sPHENIX-Collaboration/coresoftware/pull/29

Build SPACAL towers as in engineering drawing

---

macros/g4simulations/G4_CEmc_Spacal.C

As light collection being fixed in https://github.com/sPHENIX-Collaboration/coresoftware/pull/56 , enable visible energy use for the 1D calorimeter analysis. Also calibrate 1D/2D SPACAL with different calibration constant.

Enable light yield collection for 1D spacal

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_fsPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C

I add 2 function calls to the setup macros to run the removal of compressed information and the removal of redundant nodes during the DST output.

Enable Calorimeter Truth Compression

---

macros/g4simulations/G4_FEMC.C

These macro changes include an easy switch between the fsPHENIX and EIC forward EMCal implementations.  Right now this is at the level of commenting in/out different sections.

allow easy switch between fsPHENIX and EIC EMCal

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/G4Setup_fsPHENIX.C
macros/g4simulations/G4_FEMC.C
macros/g4simulations/G4_FGEM_fsPHENIX.C
macros/g4simulations/G4_FHCAL.C
macros/g4simulations/G4_FwdJets.C
macros/g4simulations/vis.mac

Merge everything together for the fsPHENIX simulation including John's forward calorimeters, Cesar's new field map, updated GEM and piston magnet. Passed geometry checks. More details see wiki: 
https://wiki.bnl.gov/sPHENIX/index.php/Tutorial/fsPHENIX_simulation 
Example event display from the macro: 
* 30 GeV negatively charged pion in the forward calorimeters
* \sqrt{s} = 510 GeV p + p collision with two ET ~ 20-30 GeV jets measured in the forward (eta=1.5) and central (eta=0.17) calorimeters

Merge everything together including forward GEM and piston magnets

---

macros/prototype2/Fun4All_G4_Prototype2.C
macros/prototype2/vis_prototype2.mac

Merge SPACAL and HCals: 
* Add a particle generator more compatible with test beam profile
* Add EMCal in simulation. More discussion on https://github.com/sPHENIX-Collaboration/coresoftware/pull/121 . The default geometry is loaded via calibration database in XML form: https://github.com/sPHENIX-Collaboration/calibrations/pull/8
* Add EMCal digitization
* Add DST reader which output an ROOT CINT friendly TTree with hits and towers
Example setup with 32 GeV pi- shower:

Spacal test beam 2016

---

macros/g4simulations/G4_Pipe.C

Change the inner radii of the beam pipes to match the engineering diagram. Both the Be and Al beam pipes should have inner radii of 2.0005 cm
[22906rB_PHENIX_(v2)_Beam_Pipe_Asm_CAP.pdf](https://github.com/sPHENIX-Collaboration/macros/files/199925/22906rB_PHENIX_.v2._Beam_Pipe_Asm_CAP.pdf)

Fix inner radii of the beampipes based on engineering drawing.

---

macros/prototype2/Fun4All_G4_Prototype2.C

Hopefully last update on SPACAL prototype setup, with dimensions and digitalziation parameter as measured by Sean Stoll and John Haggerty. Specifically
* Tower dimension, assembly spacing as measured by Sean. 
* Two tower output streams includes High gain and Low gain channels. Pixel yield, Pixel -> ADC conversion as measured by Sean. Pedstal noise as measured by John. 
Related updates include:
* Geometry database: https://github.com/sPHENIX-Collaboration/calibrations/pull/9
* G4 simulation macro: this pull request
* Plot macro: https://github.com/sPHENIX-Collaboration/analysis/tree/master/Prototype2/EMCal/macros
* 5k event / setting production set at sPHENIX user disk, available for anyone to look at it with the above plot macros: …

Spacal test beam 2016 - update

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/G4_FEMC.C
macros/g4simulations/vis.mac

Use new tower mapping file that generates combined PbSc/MPC forward ECAL for fsPHENIX.  There are corresponding pull requests in coresoftware and calibrations.

updated to allow PbSc tower type in n ew mapping file

---

macros/prototype2/Fun4All_G4_Prototype2.C

This pull request adds following updates to the prototype simulation :
1. Final location of the EMCal in the joint setup, measured by Eric Mannel and John Haggerty today
2. Tower setup for HCal as developed by @pinkenburg 
3. HCal digitization parameter as collected by Abhisek Sen and John Haggerty
4. Secondary beam profile as measured by Abhisek Sen
Measurement by Eric: 
Photo by John:
New simulation with 32 GeV pion:
Photo by Eric:
Simulation of muon beam after EMCal moved so that beam center hits UIUC module Col3 Row3:
From: Abhisek Sen [mailto:sen.abhisek@gmail.com] 
Sent: Tuesday, April 19, 2016 10:55 PM
To: Huang, Jin <jhuang@bnl.gov>; Haggerty, John <haggerty@bnl.gov>
HCALIN:
1/5 pixel / HG ADC channel 
32/5 pixel / LG ADC channel
0.4 MeV/ LG ADC
0.4/32 MeV/ HG ADC
HCALOUT:
1/5 …

Sync more reality into prototype simulations

---

macros/prototype2/Fun4All_TestBeam.C

Two updates:
1. More Cherenkov signal is added in data stream and process them in production following description on wiki: https://wiki.bnl.gov/sPHENIX/index.php/T-1044#Cerenkov_Counters
2. Adjust calibration for Cherekov so the calibrated amplitude shows up to be positive value.

Add additional Cherekov channels and adjust its polarity

---

macros/prototype2/Fun4All_TestBeam.C

Decode test beam run info to the DST/RUN/RUN_INFO node, including beam parameter, temperature and DAQ settings in the begin run event. Default macros includes producing the follow observables and example reading:
* EMCal gain, ```EMCAL_A0_HighGain```: 1
* EMCal bias, ```EMCAL_GR0_BiasOffset_Tower21```: 227
* EMCal temperature, ```EMCAL_T0_Tower21```: 30.42
* Motion table position ```beam_2CH_mm```: 1058, ```beam_2CV_mm```: 133.2
* Cherenkov pressure, ```beam_MT5CP2_Psia```: 0.4444, ```beam_MT6CP2_Psia```: 0.6783
* Beam counter, ```beam_MT6SC1_Cnts```: 12787, ```beam_MT6SC2_Cnts```: 11283, ```beam_MT6SC3_Cnts```: 10062, ```beam_MT6SC4_Cnts```: 0, ```beam_MT6SC5_Cnts```: 62529
* Beam momentum, ```beam_MTNRG_GeV```: -12
To retrieve this information via DST analysis module:
```c++
#include …
```

Decode run info to DST

---

macros/g4simulations/G4_HcalIn_ref.C

Modifications to change the inner HCAL reference design from 5 scintillators/tower to 4 scintillators/tower, maintaining 4 crossings and the flat steel plate design, as requested by @blackcathj

move to flat plates, 4 scint per tower

---

macros/prototype2/Fun4All_G4_Prototype2.C

Enable use of SPACAL light collection model in simulation. See more in coresofeware pull request:
https://github.com/sPHENIX-Collaboration/coresoftware/issues/173

Enable use of light collection models

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

Adding a simple embed switch, 
```c++
const bool do_embedding = false; // or true
```
which allows embedding a new simulation (e.g. single particle or Pythia jetty events) into an existing DST file (e.g. HIJING simulation production). 
Notes:
* Please check consistency between your local macros (```G4*.C```) and the production macros (like ``` /sphenix/sim//sim01/production/2016-07-21/single_particle/spacal2d/ ```) before running ```readhit = true``` or embedding. Production could use different set of detector than the default macro (e.g. version of tracker or EMCal). Inconsistent macro will lead to error and quit processing.
* Embedding DST into DST is NOT supported, because it is likely the two DST streams use inconsistent  vertex points from event-to-event. Therefore, the macro will …

Introducing the Embedding Flag to main macro

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/G4Setup_EICDetector.C
macros/g4simulations/G4_Aerogel.C
macros/g4simulations/G4_DIRC.C
macros/g4simulations/G4_DSTReader_EICDetector.C
macros/g4simulations/G4_EEMC.C
macros/g4simulations/G4_EGEM_EIC.C
macros/g4simulations/G4_FEMC.C
macros/g4simulations/G4_FEMC_EIC.C
macros/g4simulations/G4_RICH.C

Adding macros to build full EIC detector geometry.
Overlapcheck of all detectors yields overlaps of:
CEMC_1_sec1 with CEMC_1_sec0 volume's (message repeated for all subsequent CEMC_1_sec###) --> Is this a known overlap? Should be the same for default sPHENIX.
hEcalTower_envelope with OuterHcal volume's --> Corner of forward-ECAL clears the physical outer-HCAL, but touches the rectangular boundary box.
BH_1 with hHcalTower_envelope --> hHcalTower_envelope is cone shaped and extends beyond the physical towers, hence this overlap.

Add macros to run EIC Detector geometry

---

macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_Svtx_maps+IT+tpc.C

Thanks to the hard work of tracking experts, now we have a common macro to setup the reference tracking configuration and analysis tuning for Sept 2017 tracking review (3 layer MAPS + 4 layers of intermediate tracker or IT + TPC). 
This pull request does not change default behavior of simulation. To use the reference tracking sim., please switch comments in the following lines in ```macros/g4simulations/G4Setup_sPHENIX.C```:
```c++
//      gROOT->LoadMacro("G4_Svtx.C");                 // default MIE projections
gROOT->LoadMacro("G4_Svtx_maps+IT+tpc.C"); // Reference design for 2016 tracking review
```
* Then a 3-layer MAPS + 4 layer IT + TPC is used in simulation with analysis tuned by tracking team.
* To use 3-layer MAPS + no IT + TPC, please switch number of IT to zero on top of …

Reference tracking sim macro for Sept 2017 tracking review

---

macros/prototype2/Fun4All_TestBeam.C

Make the prototype production macro conform with new calibration xml file interface as introduced in https://github.com/sPHENIX-Collaboration/coresoftware/pull/196 and https://github.com/sPHENIX-Collaboration/coresoftware/pull/197

Use new format of calibration xml file

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/G4_FEMC.C
macros/g4simulations/G4_FGEM_fsPHENIX.C
macros/g4simulations/G4_FHCAL.C

Macro updates to serve as an example to users for how to enable the new fast forward tracking by Haiwang, as well  as the projections to forward detectors that I added.  Note that both Haiwang's and my evaluator are currently private code so I have not added the evaluator.  One could certainly be added as an example. 
I also added a minimum tower energy cutoff for the clustering for both the FEMC and the FHCAL.  This gives a reasonable number of towers (~9) for e-/pi- showers between 10-30 GeV, but it's still not a substitute for a proper clustering algorithm. 
All this is just intended to have some more information in place for people starting in simulations and have the simulations behave semi-reasonable out-of-the-box.

Macro updates for fast forward tracking

---

macros/g4simulations/G4Setup_fsPHENIX.C

Turn on PHG4Reco:: save_DST_geometry() by default.
This will use Jin's PHGeometry utilities to save a TGeometry version of detector geometry in the DST node, which makes the using of GenFit2 based modules possible. Turn this on to make the macros able to run out of box.

Switch on save geometry from Geant4 to DST

---

macros/prototype2/Fun4All_G4_Prototype2.C
macros/prototype3/Fun4All_G4_Prototype3.C

The prototype macros turned into long hard to read spaghetti macros. In order to make them more usable I introduced switch settings which enable us to run selected parts of the reco chain. The switches for each step add in the settings of the previous module switch to prevent running of useless combinations.
The hi eta prototype locations are better adjusted now. It's still not perfect but we can probably go with that. The surrounding black hole is not adjusted yet

more fine grained switches for debugging, better positioning of hi eta prototype

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_HcalIn_ref.C

The number of scintillators per tower is now a parameter which then can be picked up by the cell reconstruction (still needs to be implemented there). Also the particle gun was added to the main macro as option and the subsystem flags now incorporate the flag settings of the input modules they need.

set number of scintillators per tower to 4 in inner hcal

---

macros/prototype3/Fun4All_G4_Prototype3.C
macros/prototype3/vis_prototype3.mac

Pending merge of the pull request in the coresoftware (https://github.com/sPHENIX-Collaboration/coresoftware/pull/231) and calibration (https://github.com/sPHENIX-Collaboration/calibrations/pull/17). The current default output in event display mode is 32 GeV electron in three calorimeters:

Add EMCal to prototype3 simulation

---

macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_Svtx_MAPScyl_ITTcyl_TPC.C
macros/g4simulations/G4_TPC.C

Include new macro G4_TPC.C with new TPC readout specifics: 40 layers and new rphi segmentation.
The longitudinal extension of the cage was updated too.
Including G4_Svtx_MAPScyl_ITTcyl_TPC.C to integrate new TPC to Svtx tracking in a more modular way.
New configuration is switchable from G4Setup_sPHENIX.C. Needs to be switch on by user if he wants to use it.

adding macros for new TPC readout geometry

---

macros/prototype3/Fun4All_TestBeam.C

Update facility channel map for Prototype-3 production macro. Source of information is from https://wiki.bnl.gov/sPHENIX/index.php/2017_calorimeter_beam_test#Facility_Detector_ADC_Map :
* Channel map change for lead glass
* Add channel for beam trigger counter 3 to DST/TOWER_CALIB_SC3
* Add channel for beam scintillating counter behind MWPC4 to DST/TOWER_CALIB_SC_MWPC4
tower.energy variable for these signals are set to be the peak height of wavelet in ADC . The signs of these signals are always adjusted to be positive.

Prototype-3 production macro update

---

macros/prototype3/Fun4All_TestBeam.C

Thanks for Martin pointing out a new signal this year encode the spill indicator. Added a module to interpret the spill indicator and place results in a new event information ''DST/EVENT_INFO'' node, as well as in the DST-reader TTrees as variable ''beam_Is_In_Spill''.

Prototype3 production code update

---

macros/g4simulations/G4_Svtx_maps+IT+tpc.C

Update of G4_Svts_maps+IT+tpc.C to allow tracks with 4 missed layers instead of 30 missed layers. The 30 missed layers was screwing up the tracker cluster association somehow. 
After this update, the tracking efficiency for 2-pion events is 90% and the cluster distributions look reasonable for reconstructed tracks, see attached plots.
[clusters_per_track_by_layer_4missed.pdf](https://github.com/sPHENIX-Collaboration/macros/files/794799/clusters_per_track_by_layer_4missed.pdf)

updated with optimized number of required tracking layers

---

macros/sPHENIXStyle/README.md
macros/sPHENIXStyle/sPhenixStyle.C
macros/sPHENIXStyle/sPhenixStyle.h
macros/sPHENIXStyle/test_style.C

As mentioned in the software meeting, uploading the sPHENIX style file to the macro repository. 
Please find instruction at https://wiki.bnl.gov/sPHENIX/index.php/Plot_template . Here is a snapshot:
To ensure some consistency among plots produced by different sPHENIX members, a candidate style file is being proposed (May 2017), based on the ATLAS style file. Please click here for the gzipped tar file.
For general use, copy or link the ```sPHENIXStyle.h``` and ```sPHENIXStyle.C``` files somewhere, either locally or in your macro path (```gROOT->GetMacroPath()``` will tell you, and add it in ```.rootrc``` if you need one).
Then do
```
[0] gROOT->LoadMacro("sPhenixStyle.C") 
[1] SetsPhenixStyle()
[2] .x test_style.C  // give it a try
```
and you're good to go (even better, add this all into …

sPHENIX style file, introduced by Peter Steinberg

---

macros/g4simulations/G4_CEmc_Spacal.C

Major update on the SPACAL macro to enable 2017 design of SPACAL. Activation of this macro depending on
1. calibration database update: https://github.com/sPHENIX-Collaboration/calibrations/pull/23  (Done. installed in RCF noon May 22)
2. update in coresoftware and nightly build. (To be made)
By default, the 2017 design of 2-D projective SPACAL will be enabled. This would slow down the default simulation, which current default to a simplified 1-D projective SPACAL.

Accumulated changes on the SPACAL setup macro to enable 2017 design of SPACAL

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_40layer_KalmanPatRec.C

Version of tracking setup macro for 40 TPC layers instead of 60. Given a distinct name because it will not work for readback of the existing production with 60 layers. Use this version for all future tracking simulations.

40 layer TPC version

---

macros/g4simulations/G4_CEmc_Spacal.C

Enable tower by tower calibration for SPACAL by default. See coresoftware pull request for details. No user action required.
Plan to merge after the coresoftware build. 
@jdosbo  could you test it out once in nightly build?

Use tower by tower calibration for SPACAL. 

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

Increased TPC cell size by a factor of 2 to reduce memory size. Memory size for standalone tracking is now below 10 GB.
Added a second track evaluator when the "use_primary_vertex" flag is set to true. This processes the additional node containing tracks refitted with the event vertex included.
The change to the TPC cell size has no significant effect on tracking performance. See comparisons here:
[double_tpc_cell_size_tests_july11_2017.pdf](https://github.com/sPHENIX-Collaboration/macros/files/1146325/double_tpc_cell_size_tests_july11_2017.pdf)

Tpc memory reducer

---

macros/g4simulations/G4_CEmc_Spacal.C

From PR #69, we introduced tower-by-tower calibration for the new 2-D projective EMCal. However, in this process the reconstruction for 1-D projective SPACAL is inadvertently broken. This pull request fixes this problem. 
Thanks to @jpinkenburg for spotting this problem.

Fix running for 1-D projective SPACAL

---

macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C

This is for discussion in the HCal meeting: introduce digitization step for HCal simulation in full sPHENIX setting. 
Digitization step (photon statistics, ADC discretization and zero suppression) for HCal simulation was implemented in 2016 and 2017 HCal prototype simulations [arXiv:1704.01461](https://arxiv.org/abs/1704.01461). But it was never enabled in full sPHENIX simulation. The difference is small, as HCal resolution is dominated by sampling fluctuation. 
Nevertheless, as we go to new stage of studies, it is probably good time to introduce it. Also the sampling fraction is updated with visible sampling fraction for 16 GeV pions from the latest simulation production, which further improves the energy resolution (previous sampling fraction is muon sampling fraction from 2015 SBU …

Introduce digitization step for HCal simulation

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

The new review sims use a 40 layer TPC. In order to read them the Fun4All macros need to be changed. (In general we should read this from the DST and do the right thing, this is an awful kludge)

set number of TPC layers in Fun4All_G4_*.C to 40

---

macros/g4simulations/G4_HcalIn_ref.C

Change both instances of "material_Al" to true inside G4_HcalIn_ref.C to update your absorber material to "G4_Al". Default is still SS310.

Test switch for inner Hcal absorber material to Aluminum

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

Modifications to allow TPC readout shaping time and ADC clock time to be configured from the macro. The default parameters are set to represent the 80 ns SAMPA chip shaping time and 18.8 MHz ADC clock time, and the drift velocity is set to 3 cm / microsecond. This macro change is in conjunction with coresoftware PR #347.
Results presented in general meeting today. Plots added to coresoftware PR #347.

Changes to support realistic TPC readout time and Z smearing

---

macros/g4simulations/Fun4All_G4_sPHENIX.C

RAVE vertex finder has a known bug preventing it from handling a negative magnetic field along z-axis. Reversing the default field map direction in both simulation and reconstruction to make the B_z component positive in the vertex region.
Intend to be used with https://github.com/sPHENIX-Collaboration/coresoftware/pull/349

Reverse magnetic field direction to use a positive B_z field

---

macros/g4simulations/Fun4All_G4_sPHENIX.C

When reading DST files, automatically load the meta-lib that links to other libs needed for DST read back.

Load meta-lib that links to other libs needed for DST read back

---

macros/g4simulations/G4_Pipe.C

the duplicate PHG4CylinderSubsystem *cyl declaration does not bother root 5 but root 6 is very unhappy. Removed duplicate declaration.

remove duplicate cyl declaration

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

Change the default track projection module to `PHG4GenFitTrackProjection`.
This module project tracks using GenFit Runge-Kutta swimming instead of helix projection.
This module has been tested by @johnlajoie and Sasha.
It is more stable than `PHG4SvtxTrackProjection`

Substitute PHG4SvtxTrackProjection with PHG4GenFitTrackProjection

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

Replaced Argon gas with Ne:CF4 gas. The Ne:CF4 (90:10) gas mixture had already been added by Jin some time ago. Tested, and the results presented in the sims meeting today.

Change TPC gas to Ne:CF4 (90:10)

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

This pull request carry #89, but with a few adjustment on top of PR #89:
* Adjust the TPC outer layer thickness to 1.125 cm / layer, in order to keep max radius of the active region to R = 78 cm instead of 80 cm.
* Move many print out under verbosity checks, which hides from non-expert users. Tracking expert can enable them by flip the verbosity flag to 1 in the tracking macro
* In tracking evaluator, disable saving hits by default for non-expert users
* Recover the default calorimeter flags and behavior in the main macro
* Automatically use the drift speed setting in the tracking macro for calculating the pile up simulation time window
* Adapt sPHENIX coding style with clang-format (https://wiki.bnl.gov/sPHENIX/index.php/Codingconventions#Style_reformatting_tools)

Some adjustment on top of PR #89 - Updates pad segmentation (T Frawley). Updates gas character (T. Hemmick)

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_HIJetReco.C

These changes are in parallel with pull request 395 in the coresoftware repository: https://github.com/sPHENIX-Collaboration/coresoftware/pull/395
Summary: 
* in the main Fun4All module, HI jets no longer need the pp-style tower reco to be run (they now run their own reco using a retowerzized-CEMC before subtraction)
* the HI jet reco module now implements the full "2-iteration" UE removal procedure as described in nucl-ex/1203.1353

Updated macros for 2-iteration UE determination, subtraction & HI jet reco

---

macros/g4simulations/G4_CEmc_Spacal.C
macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C

As discussed in the simulation meeting today, this pull request switch to use the template-based clusterizer, or PHENIX clusterizer by Sasha Bazilevsky, for all three central calorimeter layers. A switch is added to each of the calorimeter macros to allow easy switch between graph and template-based clusterizer for comparisons. 
Tests are welcomed. 
Related developments:
* https://github.com/sPHENIX-Collaboration/coresoftware/pull/377 
* https://github.com/sPHENIX-Collaboration/coresoftware/pull/396
* https://github.com/sPHENIX-Collaboration/coresoftware/pull/397 
Related studies:
* https://indico.bnl.gov/contributionDisplay.py?contribId=2&confId=2724 
* https://indico.bnl.gov/contributionDisplay.py?contribId=1&confId=2723 
* https://indico.bnl.gov/contributionDisplay.py?contribId=1&confId …

Switch default clusterizer to the template-based clusterizer

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_PlugDoor.C

Jamie reminded that the flux return plug door of sPHENIX is not implemented in the default sPHENIX simulation (a thinned version is in fsPHENIX and ePHENIX simulation). Although flux return is outside the active acceptance of sPHENIX, recent tracking study does cautious us against albedo background originated from back scattering of heavy materials outside the tracking volume. 
This pull request introduce the plug door to the default sPHENIX simulation. Here is two detector display. The geometry of the plug door come from a preliminary engineering drawing which is about 30 cm thick. 
In engineering drawing:
In simulation:
Checking its effect on TPC tracking background. Since the plug door is far away from the TPC, the change in TPC clsuter multiplicity is minimal. Identical generated …

Add field return

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

There was a mismatch between the way the cells were defined and the cylindrical TPC geometry object. The cells were defined using the center radius of the layer, but the geometry object uses the inner radius. My misunderstanding. Fixed and now the cell phi values are calculated correctly.

Fixed error in TPC setup that caused cells to be slightly off itn phi

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

Update of the tracking macros to set up the TPC configuration we plan to build, i.e. 16 inner layers, 16 mid layers, 16 outer layers.
Removed obsolete lines allowing backward compatibility with ancient 60 layer hits files.
Added a switch at the top of tracking macro to allow backward compatibility with 40 layer hits files.
The configuration of the readout here is what will be used with zigzag pads. However the macro is backward compatible with the existing rectangular pad cell reco code. In the new cell reco code (PR#417) zigzag pads are used by default, so nothing has to be set in the tracking macro.

Tracking macro updates

---

macros/prototype4/Fun4All_TestBeam.C

Calorimeter beam test macro update: add leading order HCal energy scale calibration from Xu Sun (GSU). Xu's slides for details: [hcal_beamtest_energycalibration.pdf](https://github.com/sPHENIX-Collaboration/macros/files/1825603/hcal_beamtest_energycalibration.pdf)

Calorimeter beam test macro : add leading order HCal energy scale calibration

---

macros/g4simulations/G4Setup_EICDetector.C
macros/g4simulations/G4_CEmc_EIC.C

This PR introduces a shashlik sampling CEMC as an option to replace the default SPACAL CEMC (the actual sPHENIX CEMC). The PR is intended to extend the coverage of the CEMC from -1.1<eta<1.1 (default SPACAL) to -1.4<eta<1.1 to reduce the gap of EMCal coverage in the electron going direction. The calorimeter is composed of 40 layers of alternating SPACAL tungsten-epoxy and PMMA as the scintillator for light collection. 
Here is a picture of the calorimeter by itself:
and with the entire sPHENIX-EIC design:
The sampling fraction was tuned to be 4% to better demonstrate the stochastic term in the resolution. The resolution of this new sampling EMCal in simulation alone is shown here:

Shashlik CEMC for sPHENIX-EIC Configuration

---

macros/g4simulations/G4_FEMC.C
macros/g4simulations/G4_Tracking_EIC.C

fasttrack can work at unison with vertical/cylindrical detectors using different resolutions and efficiencies. Mod was needed to do tracking with EIC detectors at forward-central rapidities.
see also pull request #452 
https://github.com/sPHENIX-Collaboration/coresoftware/pull/452

adding support for fast tracking EIC using different detector responses at forward+central stations

---

macros/g4simulations/G4_CEmc_Spacal.C

This pull request would enable by default the 2018 SPACAL design, which increased tilt angle for 90 mrad to 9-degree. This is for discussion in the coming EMCal meetings. 
More details on mechanical discussion see Dan's talk https://indico.bnl.gov/event/4725/ . To use this macro, please run from a new log on into RCF which would pick up the recent calibration repository update as merged in https://github.com/sPHENIX-Collaboration/calibrations/pull/36
e+ (blue) /e- (red) shower in the EMCal. Both has pT = 5 GeV/c and launched at phi = 0:
Full detector view: 
Zoom into +x side: 
EMCal Zoom-in:
Further using muon to check the magnetic/geometric property without inducing showers. 
Here muons of both charges (red for mu- and blue for mu+) with pT = 0.5, 1, 2, 4 GeV is launched from vertex at …

sPHENIX 2018 SPACAL design, 9-degree-tilted approximate projective design

---

macros/g4simulations/Fun4All_G4_EICDetector.C

Use the fast tracking reconstruction tuned for EIC detector, instead of the default sPHENIX tracking in reconstruction.

Use track reco for EIC detector in EIC simulation

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

In preparation of containerized distribution of sPHENIX software outside RCF, the magnetic field map is relocated from the /phenix/upgrades/decadal/fieldmaps/sPHENIX.2d.root to the GitHub-hosted calibration repository (https://github.com/sPHENIX-Collaboration/calibrations/pull/39). This also removed the dependence of sPHENIX macros to the /phenix disk.
The change should be transparent to users.

Use field map from the calibration database

---

macros/g4simulations/G4_CEmc_EIC.C

Extend CEMC coverage to match preliminary 2018 LOI numbers (See table on Wiki at https://wiki.bnl.gov/sPHENIX/index.php/EIC_SPHENIX_LOI_2018#Detector_Acceptances_and_Designs).
Overlap check: Found overlap between Aerogel_Physical and hEcalTower_envelope. However, these volumes are not affected by this commit, so the overlap will be fixed elsewhere.
Aerogel_Physical ... 
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
Overlap is detected for volume Aerogel_Physical
with hEcalTower_envelope

Extend CEMC coverage to match preliminary 2018 LOI numbers

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

MVTX timing window increased to +/- 5 microseconds in the tracking macro.
Added some alternative INTT layer configurations to the macro - commented out.

Update to MVTX timing window in tracking macro

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

fix to use the enum to set the sensor type dependent cluster finding window in INTT

fix to use the enum to set cluster finding window in INTT

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C
macros/g4simulations/vis.mac

Macro changes to go with PR #477. The INTT sub-layers now all have their own layer number.
I also added a few lines to Fun4All_G4_sPHENIX.C so that if the bool "display_on" is set to true, the G4 configuration will be displayed. I changed the parameters in vis.mac to do a beams-eye view of the inner tracker, since that is currently being reconfigured a lot.

Intt sublayer to layer

---

macros/g4simulations/G4_Tracking.C

This pull request is intended to update the INTT digitization to fix following problems:
1. INTT digitized ADC is wrong (all hits has ADC = 7). Here reconfigure INTT ADC thresholds based on PHENIX/FVTX/FPHX documentation. 
2. This pull request also carry a fix to the threshold module which should not be applied to INTT
In the first try of this fix, https://github.com/sPHENIX-Collaboration/macros/pull/130, I found I misunderstood the use of V_ref in the ASIC circuit (baseline of the signal is shifted to V_ref after shaper and prior to the ADC). This should be fixed in this pull request, which significantly lowered the threshold when compared with #130 . To be sure this time, the digitization method was also applied to INTT test beam and compared with test beam data from Yorito Yamaguchi …

Set INTT threshold based on FPHX documentation - Try 2

---

macros/g4simulations/G4_Bbc.C
macros/g4simulations/G4_CEmc_Spacal.C
macros/g4simulations/G4_Global.C
macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C
macros/g4simulations/G4_Magnet.C
macros/g4simulations/G4_Pipe.C
macros/g4simulations/G4_PlugDoor.C
macros/g4simulations/G4_Tracking.C

First batch of macros to run Fun4AllG4_sPHENIX.C both under root5 and under root6. Tracking has rare last digits diffs in dca2d and dca2d_error, I assume its from the use of TMath (the root5 versions give a warning from TLorentzvector which seems to be suppressed in root6) go figure - really  please DO NOT USE TMATH

Root5 root6 combined

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Tracking.C

1) Following the collaboration meeting discussion, I updated G4_Tracking.C to have predefined layer setups for the INTT. The setups are switchable using a #define variable set on line 35. Setups are provided for:
8 sublayers of type ZZ-PP-PP-PP (the default configuration) 
6 sublayers of type ZZ-PP-PP
4 sublayers of type ZZ-PP
4 sublayers of type PP-PP   
0 sublayers (INTT removed)
As committed, the configuration that is enabled is 4 sublayers of type PP-PP.
2) I added to Fun4All_G4_sPHENIX.C the option to embed multiple Upsilons in an event, where each Upsilon has a unique embed flag. This is useful when running collisions with high pileup rate, where memory limitations make it hard to run a lot of events. As committed, one Upsilon per event is used if the "upsilon" flag is set.
Note …

Update tracking macro

---

macros/g4simulations/G4_FEMC.C

Adjusted the sampling fraction to 3%. 
Here's the fEMC tower energy sum for a sample of 30GeV incident photons 1.3 < eta < 3.0: 
and here's the distribution of the highest energy cluster in each of t he same events:

Tuned E864_fEMC sampling fraction

---

macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_HIJetReco.C
macros/g4simulations/G4_Tracking.C

small macro fixes for root6, the main change is an
#ifdef SVTXDEADMAP
around the PHG4SvtxDeadMapLoader since  this class does not exist and cling refuses to accept missing classes in a macro. With the PR in the coresoftware this show runs under root6 again

make it work under root6

---

macros/g4simulations/G4_Tracking.C

Changes in G4_Tracking.C for new MVTX configuration adopted to give a 2.0 mm of clearance from the sPHENIX aluminun beam-pipe. Values are taking from latest Walt's draws of Jan 3rd, 2019.

New MVTX configuration. Walt 3 Jan 2019

---

macros/g4simulations/G4_FEMC.C

This pull request updates the forward EMC (based on cut down E864 modules) tower geometry to use the tower structure suggested by @blackcathj.  There are corresponding changes in the coresoftware and calibrations  repositories.

Updated E864 fEMC tower geometry

---

macros/g4simulations/G4_Tracking.C

Found some empty nodenames on the node tree. They came from PHG4INTTDigitizer where Detector was not set.

Detector needs to be set to INTT to get nodenames right

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/G4Setup_fsPHENIX.C
macros/g4simulations/G4_FGEM_fsPHENIX.C
macros/g4simulations/G4_FHCAL.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking_EIC.C
macros/sPHENIXStyle/sPhenixStyle.C
macros/sPHENIXStyle/sPhenixStyle.h

In the recent tracking code reorganization (in particular, single vol TPC upgrade https://github.com/sPHENIX-Collaboration/coresoftware/pull/529 ), the EIC/fsPHENIX fast tracking simulation has been broken. This pull request is trying to fix both of them. 
Besides accumulated fixes on the EIC/fsPHENIX tracking setup, this pull request also changes the following aspect of the macros:
* Update GEM tracker to use 70um azimuthal resolution and 1cm radial strip, which has more dependable performance quote when compared with 50um as in the previous simulation. 
* Comment out the magnetic piston material in the fsPHENIX simulation, as it is not compatible with the jet program and current field map. 
* Make fsPHENIX use the same procedure for event display as sPHENIX and EIC
* Add header files …

Accumulated fixes on the EIC/fsPHENIX fast tracking module - macros repository

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking.C

The new tracking broke the macros for root5 due to missing libraries. This PR should take care of this, Fun4All_G4_sPHENIX.C, Fun4All_G4_fsPHENIX.C and Fun4All_G4_EICDetector.C

Fix macros

---

macros/g4simulations/G4_Tracking.C

The new tracking code does not apply the tpc space charge distortion anymore (which is just a memory leak). No intention to put this one back, removing it from the macro

remove obsolete tpc space charge distortion

---

macros/g4simulations/DisplayOn.C
macros/prototype2/DisplayOn.C
macros/prototype3/DisplayOn.C
macros/prototype4/DisplayOn.C

This PR adds a call to PHG4Reco::ApplyDisplayAction() which is needed to set the G4VisAttributes for subsystem using the new PHG4DisplayAction

add g4->ApplyDisplayAction() to DisplayOn.C

---

macros/g4simulations/G4_Tracking.C

This PR is needed for a name change - rather than living with two differently spelled versions of mvtx modules, lets go to MVTX

use MVTX for g4mvtx modules

---

macros/g4simulations/G4_FEMC.C

Previously the FEMC defaulted to using the graph clusterizer. I switched the FEMC to default use the template clusterizer, which has better performance, and also added an enum so that the two clusterizers can be easily switched between.

added enum to switch between template and graph clusterizer

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Tracking.C

This PR fixes the mix of source code and class names in g4tpc and g4intt. Now TPC and INTT is all caps in those packages

uniform source names in g4tpc (Tpc -> TPC)

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C

This PR stops the DSTReader from running by default until the memory leaks are fixed

set dstreader to false until its memory leaks are fixed

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking.C

This PR updates the macros for the decapitalized uniformly named Intt, Mvtx and Tpc in the coresoftware.

Decaps intt mvtx tpc

---

macros/g4simulations/G4_Tracking.C

G4_Tracking.C macro changes to allow use of truth tracking (set "use_track_prop" to false for truth tracking). This PR complements coresoftware PR #644.

Truth tracking

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C

This PR fixes an oversight in one of the macros where I had forgotten to replace TPC by Tpc in an include filename

TPC -> Tpc

---

macros/g4simulations/G4_Tracking.C

The parameter is supposed to be the module name, not the detector so one can see in printouts which module is running. The detector name is now initialized in the code, it's still hokey and will break if you rename the detector.

Fix InttHitReco module name

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking_EIC.C

Tracking for EIC macros was temporarily disabled in the `g4hough`-lib retirement process in PR #187 #186 . It turns out the dependence of EIC macro on the `g4hough`-lib is only due to unused header include files and lib load. 
Removed the used header files and recovered the tracking (fast pattern recognition + Kalman filter fit) for EIC.

Enable fast tracking for EIC macros again

---

macros/g4simulations/Fun4All_G4_EICDetector.C

This PR enables Sartre to run. It adds Sartre.cfg (copied from the sartre installation) and add the loading of the sartre library

load lib for sartre

---

macros/g4simulations/phpythia6.cfg

This PR adds the missing missing phpythia6.cfg copied from analysys/EICTrigger so it at least runs

Add missing phpythia6.cfg copied from analysys/EICTRigger

---

macros/g4simulations/sartre.cfg

This PR adds the sartre.cfg which I seem to have forgotten to add/commit. It is needed to run the sartre event generator in our standard macros

Add example sartre config file so the macro runs

---

macros/g4simulations/G4_HcalIn_ref.C

This PR changes the material chosen in the macro to Al (the code default still uses SS310). This was discussed in the simulation meeting yesterday

use Al by default

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C

This set of macro changes enables the forward EMCal (fEMC) for sPHENIX. The fEMC was originally developed for fsPHENIX but is potentially useful in determining the event plane outside the central barrel.  The changes are straightforward, and take advantage of the same macro and geometry used in the fsPHENIX macro.  There are no geometry conflicts between the fEMC and the existing sPHENIX setup (including the plug door, which is not enabled in the sPHENIX macro by default). 
I tested these changes by visual inspection (see figure), checking for overlaps between the fEMC detectors and other volumes (the fEMC is added last in the macros) and by running a handful of sHIJING events. Everything seems just fine.

Add fEMC to sPHENIX

---

macros/g4simulations/flowAfterburner.xml

This PR just adds a comment to the flowAfterburner.xml file to clarify that it only applies to the executable, not the flow afterburner module in the simulations

Add comment to clarify where the xml file applies

---

macros/g4simulations/G4Setup_EICDetector.C
macros/g4simulations/G4_FEMC_EIC.C

This PR literally copies the fsPHENIX FEMC code into the EIC FEMC macro, and sets the EIC G4Setup macro to read from the EIC FEMC macro. Previously, the EIC G4Setup was just reading directly from the fsPHENIX FEMC macro. This change will allow them to be separated, so that users can choose e.g. a particular FEMC setup for fsPHENIX or EIC separately.
Note that this PR continues to make the default FEMC for EIC the (currently being investigated) E864 cut towers. This was already the case since the EIC G4Setup was reading directly from the fsPHENIX FEMC macro, where this has been the default for several months now. 
Nonetheless, the macro contains all of the code available for the E864 cut towers or the originally proposed refurbished PHENIX PbSc towers (where the PbSc tower code is just …

Separate fsPHENIX FEMC from EIC FEMC

---

macros/g4simulations/G4Setup_EICDetector.C
macros/g4simulations/G4_FEMC_EIC.C

Jin pointed out a bug with running the EIC framework in root5 after the FEMC fsPHENIX/EIC separation. 
Tested with both root5 and root6 on rcas - bug of not working with root5 appears to be fixed.

Fixed FEMC Separation Bug

---

macros/g4jleic/DisplayOn.C
macros/g4jleic/init_gui_vis.mac
macros/g4simulations/DisplayOn.C
macros/g4simulations/init_gui_vis.mac

When using the qt based gui another opengl graphics driver needs to be used. PHG4Reco::StartGui() executes init_gui_vis.mac by default which so far called vis.mac which is used by the regular display. Now init_gui_vis.mac is standalone and calls the OGL graphics driver but nothing else. Our vis.mac has a bunch of additional calls (saving trajectories, filtering of tracks, cutting the detector), this needs to be either added or called in a separate macro (which is the preferred choice)
The DisplayOn.C has a new function QTGui() which starts the qt gui and returns a pointer to PHG4Reco (after the gui is x'ed out) so it can be restarted by g4->QTGui()

Qt initvis

---

macros/g4simulations/Fun4All_G4_sPHENIX.C

Following the discussion in the last meeting, enable printing of random seeds for rare problem debugging, such as the on-going debug for rare non-initialized variable in the tracking evaluator.
This is a 2nd try of https://github.com/sPHENIX-Collaboration/coresoftware/pull/717 following @pinkenburg 's suggestions

Enable printing of random seeds for rare problem debugging

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Tracking.C
macros/g4simulations/ReadClustersRunTracking.C

Changed Fun4All_sPHENIX.C and G4_Tracking.C to split clustering from track reconstruction to write files containing clusters. Also added a macro that reads cluster files and runs tracking + evaluation.

split clustering and tracking to write cluster files

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C

Fun4All_G4_fsPHENIX.C uses the same G4_Tracking.C and needs adjusting. Fun4All_G4_EICDetector.C uses a different tracking macro.

propagate change from Fun4All_G4_sPHENIX.C to here

---

macros/g4simulations/G4_CEmc_EIC.C
macros/g4simulations/G4_EEMC.C

Modified EEMC macro as discussed on slides 9-10 here:
https://indico.bnl.gov/event/7399/contributions/34257/attachments/26399/39954/sphenix_012820.pdf
The only difference is that I changed the line with v004->v005, instead of the other way.
In addition, for the CEMC, to keep a fixed eta acceptance for each layer requires a layer-dependent shift. This has been implemented here.

Modified EEMC and CEMC_EIC Geometry for consistency

---

macros/g4simulations/G4_Tracking.C

This PR removes the inclusion of the removed g4eval/TrkrEvaluator.h

remove obsolete TrkrEvaluator.h

---

macros/g4simulations/G4_Tracking.C

The TPC cluster resolution fudge factors that increase the resolution to 150 microns in r-phi and ~500 microns in Z have been re-tuned to compensate for Jin's introduction of variable GEM gain in coresoftware PR#705. The fudge factors are now (r-phi) 0.085 and (Z) 0.105 mm.  The performance with the new fudge factors is seen in the two figures. The efficiency is unchanged by the variable GEM gain modification.
[clusres_fudge_085_105.pdf](https://github.com/sPHENIX-Collaboration/macros/files/4391308/clusres_fudge_085_105.pdf)
[ups1s_fudge_085_105.pdf](https://github.com/sPHENIX-Collaboration/macros/files/4391310/ups1s_fudge_085_105.pdf)

Tpc fudge factor tuning

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/G4Setup_EICDetector.C
macros/g4simulations/G4_DSTReader_EICDetector.C
macros/g4simulations/G4_EEMC.C
macros/g4simulations/G4_FEMC_EIC.C
macros/g4simulations/G4_FHCAL.C
macros/g4simulations/G4_GEM_EIC.C
macros/g4simulations/G4_Pipe_EIC.C
macros/g4simulations/G4_RICH.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking_EIC.C

In the EIC 1st yellow report workshop, a detailed CAD model for the EIC beam pipe at 25mrad crossing angle was discussed: https://indico.bnl.gov/event/7449/contributions/36037/
This pull request import this beam pipe model to the Geant4 simulation and adjust the sPHENIX-EIC detector layout around the new beam pipe and its extension. This pull request also imports the [LANL FST forward vertex tracker](https://arxiv.org/abs/2002.05880).
The change should be transparent to analysis code. But one would notice the change in DCA (larger beam pipe), better forward momentum resolution (LANL FST) and reduced high psuedorapidity acceptance (accommodate beam pipe and crossing angle)
Note the Be-section of the beam pipe is always enabled in the simulation. The forward-backward Al extensions can be …

Mar-2020 EIC beam pipe and detector addition/adjustment

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Mvtx.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

This PR adds some plotting macros for the new MVTX clusters QA histograms
Residuals, errors and pulls are plotted in separate canvases. 
Vertical line at zero is added. 
For now there is no attempt at fitting the distrubitions, nor information plotted about histograms mean and RMS.
Those could easily be added in the future. 
(Remark: my editor is setup to automatically replace tab characters by space characters, and remove empty spaces/tabs at end-of-line. This creates unrelated changes in the resulting diff. I can disable this and resubmit the pull request, if needed)

Tracking low occupancy qa mvtx

---

macros/g4simulations/G4_FEMC_EIC.C
macros/g4simulations/G4_GEM_EIC.C

Fixing a problem left from https://github.com/sPHENIX-Collaboration/calibrations/pull/58 and https://github.com/sPHENIX-Collaboration/macros/pull/233 , where the Forward EMCal model was switched to the re-stacked PHENIX EMCal as implemented in `PHG4EICForwardEcalDetector::ConstructTower()`. However, the sampling structure appears there has too high Pb to Scintillator ratio. 
Therefore, this pull request switch the tower map to fit `PHG4ForwardEcalDetector::ConstructTowerType2()`, which has the proper sampling structure implemented and fits the digitization code. Mapping changes are in https://github.com/sPHENIX-Collaboration/calibrations/pull/59
Thanks to Barak Schmookler for pointing out this problem. 
Thanks to Xuan Li who suggested an update on the material thickness in the forward …

Two fixes for Pull Request #233

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Tracking_TruthMatching_NumOfClusters.C
macros/QA/tracking/QA_Draw_Tracking_nClus_Layer.C
macros/QA/tracking/QA_Draw_Utility.C
macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/G4Setup_EICDetector.C
macros/g4simulations/G4_DSTReader_EICDetector.C
macros/g4simulations/G4_EEMC.C
macros/g4simulations/G4_FEMC_EIC.C
macros/g4simulations/G4_FHCAL.C
macros/g4simulations/G4_GEM_EIC.C
macros/g4simulations/G4_Pipe_EIC.C
macros/g4simulations/G4_RICH.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking_EIC.C

Following #240 and sync it to the high occupancy QA.
Also updating the INTT-dependent tracking efficiency to cut on >=1 INTT hit (previously cut on >=2 hit, which is a bit tight)

Sync tracking high occupancy QA

---

macros/QA/tracking/QA_Draw_Intt.C
macros/QA/tracking/QA_Draw_Mvtx.C

This PR adds plotting for the cluster size histograms for MVTX and INTT , as added in https://github.com/sPHENIX-Collaboration/coresoftware/pull/820
Typical plots look like:

added cluster size histograms

---

macros/g4simulations/G4_Tracking_EIC.C

LANL FST_5 was missing in G4_DSTReader_EICDetector.C. Now, it is back in the macro.
To admin, I didn't plan to create a pull request for all the changes I made in this directory. If you can, please accept the changes on the G4_DSTReader_EICDetector.C (commit c6fd072) alone.

Add LANL FST_5 in DST tree

---

macros/g4simulations/G4_Tracking.C

This PR adds micromegas and reconstruction modules to G4_Tracking.C
By default micromegas are disabled. To enable, change enable_micromegas from false to true either in G4_Tracking.C or in the calling macro

added micromegas subsystem and reco modules

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/G4_Input.C
macros/g4simulations/GlobalVariables.C

This PR turns off the forgotten verbosity=1 setting for some input managers. It now uses INPUT::VERBOSITY for all of them

Inputmgr verbosity

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/G4_Tracking_EIC.C

Two tuning on the EIC macro: 
1. For the displaced vertex mode, exclude vertex in track fit and use not-smeared truth vertex for DCA calculation reference. Thanks to Håkan Wennlöf of University of Birmingham for verifying this setup.
2. For the main macro, use random seed by default and silence verbosity of input manager and simple event generator.
Here is an example 2D DCA from 20 GeV pions:

Fast tracking parameter update for EIC macro

---

macros/g4simulations/Fun4All_G4_EICDetector.C

This just puts the default back to not writing DSTs for the EIC detector

disable dst writing

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Tpc.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

Step 2/2: Resubmitting #268 to merge into tracking-high-occupancy-qa branch.
The result is already available from an earlier test in #269 : 
https://web.racf.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-tracking-high-occupancy-qa/296/QA_20Report/TPC/
The drop of cluster efficiency in the high occupancy events are significant:

Tpc cluster qa - merging high occupancy branch

---

common/G4_Input.C
common/G4_Pipe_EIC.C
detectors/EICDetector/Fun4All_G4_EICDetector.C

This PR reads the generator config files (phpythia6.cfg, phpythia6_ep.cfg, phpythia8.cfg and sartre.cfg) from CALIBRATIONSROOT so we do not need local copies anymore. The location can be changed in the Fun4All_G4 macro to read private configs.
The original gdml file for the eic beampipe had spaces in the filename. While legal this is asking for problems. The file was changed a while ago using underscores instead of spaces (the original file is now a softlink to this one). This PR now changes the filename in the macro accordingly

Generators config

---

common/G4_World.C

This PR adds a small modification to the world size readjusting. It now takes the gap between the detector and the black hole into account which is user adjustable. It needs to be added to the calculated black hole dimensions which are given by the detector size

Add gap for black hole to determine worl size

---

common/G4_Mvtx.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_MvtxService.C

Beta version of MVTX service barrel
This version contains three concentric cylinders of copper, water and finally polyethylene. The layers begin at r = 8.5cm and z = -25cm (the z-gap will likely be filled by the FPC extensions). Each layer is a solid ring, accounting for the total material contribution from 48 staves.
The number of service layers can be easily configured by setting the number of layers, layer start position and number of staves supplied by that layer. The calculations and placements are then done by the rest of the macro
Additionally, this macro contains code with parameters for all the individual cables and tubing but is currently commented out. For example, this means there is code for the number of ground wires with the inner and outer radii of the wire that each stave …

 Beta version of MVTX service barrel

---

common/G4_Mvtx.C

PHG4CylinderSubsystem is used explicitly later in the macro, so header should be there. 
Not having it prevents to load the macro "standalone" or for instance to load G4_Tracking.C without loading first G4Setup_sPHENIX.C (which is otherwise unnecessary when running standalone reconstruction, or evaluation macro).

added missing header.

---

common/G4_CEmc_Spacal.C
macros/g4simulations/G4_CEmc_Spacal.C

Pull request for variable zero suppression, pedestal, and GeV per ADC in CEMC. This request implements the changes made in PR #889 in coresoftware and PR #64 in calibrations. Previous structure with statically defined pedestal, zero suppression threshold, and GeV per ADC remains but is commented out. This may be useful for quickly testing new parameters since it does not require generating a new calibrations xml.

Variable CEMC parameters from calibrations file

---

common/G4_DSTReader.C
common/G4_EPD.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_DSTReader.C
macros/g4simulations/G4_EPD.C

add macros to init and register the EPD subsystem. the flags are set to false by default.

add event-plane detector to simulations

---

common/G4_Input.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR makes the necessary changes to the macros to use the improved pileup manager (copying vertex settings from foreground input manager, remove duplicated events)

Hepmc pileup fix

---

macros/g4simulations/Fun4All_G4_sPHENIX.C

This PR puts the vertex parameters which were previously hardcoded in the ctor as default into our legacy macro

put old hardcoded pileup manager vertex settings into macro

---

common/G4_Tracking.C

This PR makes Acts the default track fitter, with the TPCTracker for seeding and the silicon seed+TPC seed stub matcher to construct the full track for the Acts KF.
This PR should not be merged until we move the default environment to run on gcc8.3 and add the environment changes in the play build that Chris has implemented over the last few weeks.

Acts Default Track Fitter

---

macros/g4simulations/G4_Tracking.C

use_ca_seeding is still set to false by default, but now no further configuration is needed - just turn it to true and you have CA seeding.

Introduced CA seeding with tuning options

---

common/G4_Tracking.C
macros/g4simulations/G4_Tracking.C
macros/g4simulations/vis.mac

We should discuss this at the sims meeting before merging. Running this macro will require a special environment setup.
The G4_Tracking.C macro is updated so that it runs the Acts tracking chain by default. Track seeding is done by PHCASeeding (default), with the option of using PHTpcTracker instead. The Genfit track propagation and fitting chain can be run instead of the Acts chain after the seeding is done. The Hough seeding is dropped from the macro.
The truth track seeding works for the Genfit fitter, not for the Acts fitter. We will likely have to sett good enough starting track parameters in the truth seeding module (or after it) for Acts to function properly.

Acts tracking macro

---

detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C

That made the default macro crash with a weird flag error

accidentally left hepmc input active

---

common/G4_Tracking.C

This PR updates the G4_Tracking macro in accordance with [PR 949](https://github.com/sPHENIX-Collaboration/coresoftware/pull/949) to run MakeActsGeometry before PHActsSourceLinks as a standalone SubsysReco module. This way MakeActsGeometry doesn't have to be coupled to PHActsSourceLinks, in the event the geometry building needs to occur earlier in the tracking chain.

Update with MakeActsGeometry change

---

common/G4_Tracking.C

Remove the Acts CKF module from the macro so that others don't use it. It has not been tuned yet and regardless is too slow on the Acts side for our current purposes.

Remove Acts CKF

---

detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

I accidentally removed this INPUTGENERATOR::SimpleEventGenerator->Embed(2); which killed the evaluation for the embedding. This PR puts this back in the Fun4All macros

put embed flag =2 back for simple event generator

---

common/G4_Pipe.C

implement beam pipe out to +/- 2800 mm, based on drawings from slide 4 of [[slides]]. includes the 'vacuum' part inside the beam pipe.
no warnings came up in the overlap check.
[slides]: https://indico.bnl.gov/event/8496/contributions/37528/attachments/28093/43120/2020MAY15_BEAM_PIPE_DESIGN_STATUS_PRR_V1.pdf

beam pipe extension

---

common/G4_Magnet.C
common/GlobalVariables.C

The previous implementation which initialized the sPHENIX default for the G4MAGNET namespace in GlobalVariables.C ran into problems when other magnets try to overwrite those. The solution is to initialize the variables to some garbage (NAN and empty string) and then set them in MagnetInit() if there were not set.
If other macros use this without going through the magnet - they need to set those variables

initialize magnet in MagnetInit() not in G4MAGNET namespace

---

common/G4_Magnet.C
detectors/EICDetector/G4Setup_EICDetector.C
detectors/fsPHENIX/G4Setup_fsPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C

This PR fixes an unwanted side effect of the change of the initialization of the magnet fieldmap and scale factor. If the magnet is disabled in the Fun4All macro, those values were not initialized anymore leading to a crash. Now the those values are initialized in G4Setup no matter if the magnet volume is enabled or not

Fix magnet

---

common/G4_Input.C
common/G4_Pipe.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds the ion gun, the dzero generator and our very simple particle generator to the input choices. I revamped the base class and this was the easiest way to test them. I didn't add them to the Fun4All macros to not overload them.
The beam pipe extension had an overlap with the forward black hole. The reason is that from the old days to avoid overlaps we added a tiny gap at the end of the cylinders of the beam pipe. While this is fixed - we still need to look at this since this gap is filled with the world volume material (air). So now we have a thin layer of air in the vacuum which likely will have effects on the far forward particles

Add inputs fix overlap

---

common/G4_TPC.C
common/G4_Tracking.C

Defaults to normal tracking. To turn on space charge distortions in the TPC set "ENABLE_DISTORTIONS = true" in G4_TPC.C. The space charge calibration chain is still being developed.

Adds the flags to turn on distortions and run the silicon and Micromegas matching

---

common/G4_Tracking.C

PHGenFitTrackProjection was inside the Genfit tracking section, so when Acts tracking was run, the associations to the calorimeters were not being made. Moved it to the end of Tracking_reco() so that it will be run for either Genfit or Acts tracking.

Fix track associations to calorimeters

---

common/G4_Tracking.C

This PR adds a flag for running the ActsEvaluator. It also removes the SC flag for running the acts track fitting chain so that it can be run either with or without space charge distortions.

ActsEvaluator Flag

---

common/G4_Micromegas.C

- Change the default micromegas configuration to the 'baseline' configuration as passed to sphenix management
- added 7cm from the central membranes to the micromegas consistently with baseline configuration

Default micromegas config

---

common/G4_Bbc.C
common/G4_TPC.C
common/G4_Tracking.C

This PR adds the TpcSpaceChargeCorrection module to the GenFit tracking chain. 
For now, the module will make Acts tracking fail because of the inability to assign clusters to the right surface once they have been moved in "r". So the G4_Tracking automatically disable the module if not running GenFit chain.
Also: fixed missing include in G4_Bbc.C
Question: 
Default filenames for G4TPC::distortion_filename and G4TPC::reconstruction_filename are local name:
std::string distortion_filename = "fluct_average.rev3.1side.3d.file0.h_negz.real_B1.4_E-400.0.ross_phi1_sphenix_phislice_lookup_r26xp40xz40.distortion_map.hist.root";
std::string correction_filename = "fluct_average.rev3.1side.3d.file0.h_negz.real_B1.4_E-400.0.ross_phi1_sphenix_phislice_lookup_r26xp40xz40.distortion_map.hist.root"; …

Tpc distortion correction

---

common/G4_Tracking.C

This PR puts the acts track-to-calo projection module in the acts tracking chain and the previous GenFit track-to-calo projection module in the GenFit tracking chain. This PR depends on the corresponding coresoftware [PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/980).

Add Acts track-to-calo projection

---

common/G4_Tracking.C

This PR reverts the previous PR. It seems Jenkins found a bug in Acts in the way that Acts handles a particular error. Rather than returning an error, Acts just throws an exception which causes the code to crash. I've reported the bug and we will have to update versions once the developers fix things.
In the meantime, we'll revert this and just continue to use the GenFit track projection module.
Reverts sPHENIX-Collaboration/macros#334

Revert "Add Acts track-to-calo projection"

---

common/G4_Pipe.C

This PR replaces G4double in the macro. A change in the includes removed G4Types.hh and the use of G4double made it barf. Please do not use G4 typedefed variables

replace G4double by double

---

common/G4_CEmc_Spacal.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
common/G4_Input.C
common/G4_Intt.C
common/G4_Jets.C
common/G4_Mvtx.C
common/G4_TPC.C
common/G4_Tracking.C
common/QA.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This is the first of several steps to rebuild the standardized QA capability under the new macro setup [ #262 ]
QA modules are integrated in the common macros, part of each of the detector setup and jet/track reconstruction macros. They can be enabled/disabled in the main Fun4All macro like an eval step, which default to be enabled. Suggest enable these QA modules in the coming productions too. 
Next steps include introduce its jobs in Jenkins CI and build a new QA plot archival.

QA setup for new macros

---

common/G4_Tracking.C

This PR adds the acts vertex finding module to the acts tracking chain. It does not overwrite the `SvtxVertexMap` and instead creates a new map on the node tree.

Acts vertexing

---

common/G4_Input.C

This PR switches the ordering. The Fermi Motion and Flow Afterburner work on the HepMC Node (PHHepMCGenEventMap) which then get fed into G4 by the HepMCNodeReader. So the HepMCNodeReader needs to be called after the afterburners

flow and fermi afterburner need to run before HepMCNodeReader

---

common/G4_Input.C
common/GlobalVariables.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/fsPHENIX/G4Setup_fsPHENIX.C

Following the example of the sPHENIX macro, fixing the loading order of G4_Tracking in fsPHENIX setup. Currently it fails while looking for variables from G4_Input

Fix fsPHENIX loading order of G4_Tracking

---

common/G4_Input.C

For the x8664 container this lib needs to be loaded

load libFermimotionAfterburner.so in G4_Input.C

---

common/G4_TPC.C
common/G4_Tracking.C

This pull request updates the flags in G4_TPC and G4_Tracking needed to accomodate latest distortion code from Henry.
The latter can deal with either static and per-event distortion maps (or both at the same time) and thus the configuration flags must support both configuration.

updated flags to handle new distortions from Henry

---

common/G4_EEMC.C
common/G4_FEMC.C
common/G4_FEMC_EIC.C
common/G4_FHCAL.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds the use of the template clusterizer for the eemc and the fhcal. It removes the obsolete call reco for the forward calos (they go directly from g4hits to towers). The functions themselves and the enable is still in place so we don't break existing macros

Fix forward calos

---

common/G4_Tracking.C

This PR introduces the acts silicon seeding and initial vertexing into the macros. It is left off by default (i.e. we are still defaulting to the truth vertexing/silicon seeding for now). This will give experts a flag to switch on and off for testing it's performance with the full track fitting procedure.

Acts silicon seeding

---

common/G4_KFParticle.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds the KFParticle macro to perform Upsilon, D0 and Lc reco
The three reconstructions were tested and work without crashing although the Lc generator is still a work in progress. This will appear in a later PR to core software.
There are some base cuts which are realistic but might be tight for code testing so they can be loosened (or set to effectively no cut). The nTuple output is disabled by default while the DST output is enabled. Truth matching is also disabled by default, only enable it if you know there are truth variables. KFParticle will exit your run rather than skip the event if this is the case

KFParticle macro added

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

`ShowerCompress()` drop the calorimeter G4hits and G4Cells for a compact DST output. However, in the current call order, the hits are dropped before evaluator and the QA modules, both of which uses hits for check purposes. 
This problem show up in HF MDC1 production jobs where Geant4 QA plots for calorimeters are all empty:
https://github.com/sPHENIX-Collaboration/MDC1/pull/6  
Suggest change the order so hits remain in memory for the evaluator and the QA modules to dig on. Meanwhile, this carry the calorimeter hits in memory through the tracking stage and it may impact the overall memory foot print of the jobs, only when the DST compression is enabled.

Move `ShowerCompress()` to after evaluator and QA calls

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Running this module in Au+Au collisions causes the memory to blowup. Chris said it should be disabled by default.

Set TOPOCLUSTER to disabled as default.

---

common/G4_CEmc_Spacal.C

Last step following https://github.com/sPHENIX-Collaboration/coresoftware/pull/1050 and https://github.com/sPHENIX-Collaboration/coresoftware/issues/1048 to remove the built-in detector geometry of `PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map_2015_Chris_Cullen_2D_spacal()`

deprecate PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map_2015_Chris_Cullen_2D_spacal()

---

common/G4_Tracking.C

After discussion in the tracking meeting today, it was agreed upon that the acts silicon seeder should be made default so that we completely remove our dependence on truth information in the track reconstruction.

Make acts silicon seeding default

---

common/G4_TPC.C

Adding TpcClusterCleaner module to G4_TPC.C. This is the companion to coresoftware PR#1057, and should not be merged until after that one.

Add TpcClusterCleaner module to G4_TPC.C.

---

common/G4_Tracking.C

Alters G4_Tracking.C to include the option to use the PHHybridSeeding module, which contains the STAR seeding core and the ALICE simplified KF.
Now that there are more than two TPC seeding options, there also needed to be a guard against nonsensical configurations. If both PHTpcTracker and PHHybridSeeding are selected, it issues a warning and reverts to the default behavior (i.e. using PHCASeeding).

Added hybrid TPC seeding

---

common/G4_Tracking.C

This PR makes the default tracking run with the truth initial vertexing instead of the Acts reco initial vertexing. We will continue to debug why the tracking performance degrades using the initial IVF; however, for the time being, this will get everyone going with running the tracking in the ideal state.

Initial truth vertexing

---

common/G4_Tracking.C

This PR adds a flag to the second track fit pass so that the correct vertex node is picked up while leaving the Acts vertex writing to the `SvtxVertexMapActs` so that the QA can function with Acts and Rave.

fix second track fit vertex node access

---

common/G4_Tracking.C

After discussion in the impromptu tracking meeting today, we agreed that we should remove the final vertexer since it hasn't been tuned for AuAu yet and has only been robustly looked at in low multiplicity. This PR removes the module from the main tracking macro.
We should run a Jenkins QA job with the updated macro to ensure that none of the performance changes significantly. I did some local tests and didn't see anything, but the QA has a knack for finding things 😄

remove final IVF

---

common/G4_Tracking.C

This PR accompanies coresoftware PR 1077. It sets the search windows for PHTpcTrackMatching to the new values optimized for high occupancy.

Set PHSiliconTpcTrackMatching search windows to the new tune.

---

common/G4_Tracking.C

Add the vertex finder back in now that the MDC tracking has kicked off.

re-add vertex finder

---

common/G4_Barrel_EIC.C
common/G4_FEMC_EIC.C
common/G4_FGEM_fsPHENIX.C
common/G4_FHCAL.C
common/G4_FST_EIC.C

This PR removes the recently introduce TString interfaces. Options and settings should be set via namespaces. That maybe clunky and we can change this if there is a better idea but there should only be one way to set stuff up. Besides checking for substrings without any naming convention will lead to problems later on if options strings are not unique (or one is a substring of another otion)

Remove tstring

---

common/G4_Tracking.C

This macros PR accompanies coresoftware PR 1088. It implements the new module PHTpcTrackSeedVertexAssoc and sets it to run by default. It also changes the way that PHTpcTracker seeding is flagged, since the PHTpcTracker seeds no longer need special handling when PHTpcTrackSeedVertexAssoc is run after the seeder.

Modified G4_Tracking.C to add PHTpcTrackSeedVertexAssoc.

---

common/G4_Tracking.C

After tuning and testing the initial vertexer, this PR adds it to the tracking macro with a flag. The truth vertexing is still run by default in this PR so as to not cause any possible issues to users currently working with the MDC data - tracking experts can continue testing it.

Initial Vertexing

---

common/G4_Tracking.C

Dangers of a Friday push - missed an init_vtx flag which causes silicon truth seeding to overwrite the acts silicon seeding map.

missed init_vtx flag

---

common/G4_Tracking.C

Intermediate vertex associator module between seeding and propagation is also necessary since the propagator, for the sake of consistency, expects seeds to be defined at the vertex.

Added propagator to tracking reco sequence

---

common/G4_Tracking.C

Reverts sPHENIX-Collaboration/macros#380
This PR should remove the propagator so we can get back on our feet again without disrupting the debugging of the propagator

Revert "Added propagator to tracking reco sequence"

---

common/G4_FST_EIC.C
common/G4_GEM_EIC.C
common/G4_Tracking_EIC.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/EICDetector/G4Setup_EICDetector.C

This PR updates the current default EICDetector with an FST compatible with the TPC+MVTX+3 forward gems. The inner 4 FST disks are made smaller to fit inside the TPC inner field cage. The outer-most disk is moved to z=208cm to avoid a conflict with the last forward GEM. The inner radius of the second is decreased since no FST disk is nearby.
In addition, an option for a 5 FGEM setting is created with an Enable::FGEM_ORIG option, which can only be enabled if the FST is removed.
Lastly, track projection to the EEMC is also added.

Updated FST and forward GEM configurations.

---

common/G4_Input.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Following https://github.com/sPHENIX-Collaboration/coresoftware/pull/1087 , this pull request apply the beam parameters by default to the detector simulation macros. This is applied toany HepMC-based generator, e.g. `Fun4AllHepMCInputManager`, `Fun4AllHepMCPileupInputManager`, `PHPythia8`, `PHPythia6`, `PHSartre`, `ReadEICFiles`
Two functions defines the parameters: 
* `Input::ApplysPHENIXBeamParameter(PHHepMCGenHelper *HepMCGen)` applies the 2mrad sPHENIX beam crossing as defined in sPH-TRG-2020-001
* `Input::ApplyEICBeamParameter(PHHepMCGenHelper *HepMCGen)` applies the 25mrad beam crossing and beam parameters as defined in EIC CDR
Users are allowed to override these beam parameters in the main macro by commenting out or adding more parameter calls following interface defined in …

Applying beam parameters (e.g. crossing angle) to detector simulation macros

---

common/G4_FST_EIC.C
common/G4_Tracking_EIC.C

Few minor clean ups on tracking and FST macros
- allow overlap checks for FST via flags
- propagate verbosity to fast tracking module
- clang-format

Clean up for tracking and FST macros

---

detectors/EICDetector/Fun4All_G4_EICDetector.C

Reverse changes in the Fun4All macro to the default setup.
- Switch off the forward beam pipe
- Switch on the TPC and MVTX

switch off forward pipe and switch on MVTX and TPC

---

common/G4_hFarFwdBeamLine_ip6_EIC.C

This pull request implements the IP6 magnets and detectors following the design as created in eicROOT:
* magnets are read from the calibration folder
* 3 detectors: 1 ZDC plane, 2 Roman Pot planes, 4 B0 dipole planes
It also has a commented out beam pipe which has quite a few overlaps but may be useful to have if someone wants to fix it in the future. 
Figure of setup:
TODO:
* adjust/integrate with the large f4a framework (line 174 sets the world Z axis -- does this break anything?)
* generalize code to allow for IP6 or IP8 selection when calling the macro

Macro for hadron far forward beamline and detectors

---

common/G4_Input.C
detectors/EICDetector/Fun4All_G4_EICDetector.C

By default applying the EIC beam parameters, such as the beam crossing angle, to the EICSmear event generator intputs. 
Thanks to Wenqing Fan at LBNL for pointing out this feature is missing for the EIC smear generator event, although applied to other event generator input interfaces as in https://github.com/sPHENIX-Collaboration/macros/pull/381 
A test case is https://github.com/blackcathj/macros/pull/new/beam-xing-detector-eicsmear

Apply EIC beam parameter by default to EICSmear event generator inputs

---

common/G4_Intt.C
common/G4_Micromegas.C
common/G4_Mvtx.C
common/G4_TPC.C

This PR moves the digitization so that it is enabled by the <subsystem>_cells flag, not the <subsystem>_clustering flag. Now the _cells flag causes both hit reconstruction and hit digitization to be run. The _clustering flag now causes only clustering (and cluster cleaning, in the case of the TPC) to be run.

Moved the digitization from the _clustering to _cells.

---

common/G4_CEmc_EIC.C
common/G4_CEmc_Spacal.C
common/G4_EEMC.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

This PR makes the digitizer configurable via the G4* namespace. The default is what was previously hardcoded (RawTowerDigitizer::kSimple_photon_digitization). Previously the cemc with its many channels adds close to 30GeV which are also picked up by the clusterizer. This makes single particle sims very impractical when just looking at grand totals

make digitisation configurable via G4* namespace

---

common/G4_Tracking.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR implements the necessary changes to run the Acts tracking in the new Acts-Svtx object scheme. It removes the need for `PHActsSourceLinks` and `PHActsTracks`. 
This PR should not be merged until the corresponding coresoftware PR is merged. Note also that the default `Fun4All` macro has been changed in this PR, to accommodate the fact that the Acts geometry must be built before any of the clustering is performed.

Acts objects in tracking

---

common/G4_Micromegas.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR enables the Micromegas by default in th QA low occupancy branch. This way one should be able to see the Micromegas Layers in the Tracking QA, and monitor changes to the Micromegas chain in Jenkins. 
It also adds a Micromegas-specific QA module, to run together with the other existing QA modules
Modifications to Jenkins/Jupiter plots will be the subject of a different PR
This change must also be ported to QA-tracking-high-occupancy

Micromegas qa

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C

This is a follow up to https://github.com/sPHENIX-Collaboration/macros/pull/402 in separation of the EIC specific parts from the sPHENIX software repository and moving them to the EIC repositories. This pull request remove the link of sPHENIX macros to the FEMC modules, which will be located in the EIC repository ( https://github.com/eic/fun4all_eicdetectors/pull/2 )
Full list of relocation pull requests: 
- https://github.com/sPHENIX-Collaboration/calibrations/pull/77
- https://github.com/eic/fun4all_eiccalibration/pull/1
- https://github.com/sPHENIX-Collaboration/coresoftware/pull/1138
- https://github.com/eic/fun4all_eicdetectors/pull/2
- https://github.com/sPHENIX-Collaboration/macros/pull/402
- https://github.com/eic/fun4all_eicmacros/pull/31

Remove FEMC from sPHENIX setup

---

common/G4_HcalIn_ref.C
common/GlobalVariables.C

This PR starts the proper handling of support structures. So far absorbers which came from the calorimeters have been used to also characterize support structures. This PR adds a global bool SUPPORT and the first implementation in the inner hcal

start differentiating between calorimeter absorber and support structures

---

common/G4_Tracking.C

Fallout from the tracking reorganization from Tony - if this switch is false, the SvtxVertexEvaluator defaults to the wrong vertex map name and thus there is no vertex evaluation. Only affects the vertex evaluation, so this PR just flips the switch to true by default.

fix vertex eval

---

common/G4_Tracking.C

Remove this header as it is not used by default anymore (and is being removed from the trackreco Makefile)

remove acts evaluator header

---

common/G4_Tracking.C

Remove other headers that is needed for the cleanup PR. Apparently my local tests are getting confused by the build libraries (which still contain these header files) and my local compiled libraries (which don't).

remove other headers

---

common/G4_KFParticle.C

KFParticle_sPHENIX updates have removed functions with fixed-length arrays in favor of functions with vectors. The KFParticle macro had to be updated to match this. At the same time, I switche the decay topology declarations from individual functions to decay descriptors

Updated KFParticle macro

---

common/G4_Tracking.C

- load libtpccalib.so
- set proper path to include PHTpcResidulals (it is now in tpccalib)
This change is necessary for https://github.com/sPHENIX-Collaboration/coresoftware/pull/1193 to succeed.
Problem is: it will crash any other build untill the previous PR is merged. @pinkenburg @blackcathj: not sure how you usually handle this.

Fix tracking macro to match moving PHTpcResiduals to tpccalib

---

common/G4_Tracking.C

I did not realize that PHTpcResidual modules was defined in two places in the macro (either with full or truth track finding) and thus the output root file name for space charge reconstruction matrices was only set in the first occurence
now fixed.

Also pass output root file name to PHTpcResiduals when running in truth tracking mode

---

common/G4_Tracking.C

This PR make PHTrackCleaner a normal part of the Acts tracking chain. It is run after the first Acts track fit. It finds the best match for each TPC track seed to the silicon track stubs, and deletes all other tracks corresponding to that track stub.

Add PHTrackCleaner to normal Acts tracking chain.

---

common/G4_Tracking.C

Adds PHSimpleKFProp to the CA seeding chain, along with an intermediate PHTpcTrackSeedVertexAssoc module ("PrePropagatorPHTpcTrackSeedVertexAssoc"). Also adds an option, use_propagator (default: true) that turns on the usage of this propagator and alters the CA seeder settings to pass much shorter seeds, which the propagator will lengthen.

Adding propagator to CA seeding

---

detectors/sPHENIX/G4Setup_sPHENIX.C

This implements the choice to read the newest sphenix 3d fieldmap (the previous 3d fieldmap name was just a placeholder). The fieldmap itself is chosen in the Fun4All macro

implement selection of 3d fieldmap

---

common/G4_Tracking.C

There is now a flag in the SvtxEvaluator for the ntp_gtrack tuple. If this primary flag is not set, it outputs junk for simple events. This PR sets it to default run over primary particles, which was the case before a recent a coresoftware PR.

default to primaries

---

common/G4_Mvtx.C

This is part of a series of PRs to allow MVTX alignment simulation. Currently, we can move any stave anywhere, independently, and tilt it.
Calibrations PR: https://github.com/sPHENIX-Collaboration/calibrations/pull/82
Coresoftware PR: https://github.com/sPHENIX-Collaboration/coresoftware/pull/1277
To do:
Alter MVTX sim to read different stave GDML files. This requires changing how the simulation is setup as a single GDML file is read in BEFORE looping over all stave placements

Updated MVTX sim for alignment

---

common/G4_BeamLine.C
common/G4_Pipe.C

This PR fixes an overlap of the forward beampipe enclosure with the epd. Now the Al beampipe from sPHENIX is extended through the epd (added 30 cm in length). The forward enclosure is larger to accommodate the magnets

Fix overlap

---

common/G4_Tracking.C

This changes the default track reconstruction chain to be vertex independent. The initial vertex finder and second track fit are removed completely and replaced by Tony's new simple vertex finder and a new module which propagates the track parameters from the position WRT to the beam line to the vertex position.  This PR needs the changes in coresoftware from the corresponding [PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1288) to function.

Track Fitting Without Vertex

---

common/G4_Tracking.C

Swap the genfit track projection module to the Acts track projection module.
Note that this module previously had a bug in it where it would cause crashes on a very rare basis as uncovered by Jenkins. I think this has been fixed, but it is hard to test locally. I'd like to merge this and over the course of the next ~week see if Jenkins finds any issues, local tests with 100k tracks show no crashes.

Swap to Acts track projection module

---

common/G4_Tracking.C

That PR removes an unused include. The include itself is removed in the next PRs which then crashes jenkins

remove obsolete PHActsInitialVertexFinder.h include

---

common/G4_Tracking.C

Remove the second track fit from the truth track seeding chain, since it is now obsolete.

Remove second track fit which is obsolete

---

common/G4_Tracking.C

This PR is the result of try and error. We had the old problem that for unknown reasons the singularity containers running off a local installation stopped working, filling the screen with root6 gibberish:
root [0] .x Fun4All_G4_sPHENIX.C(1)
GFRaveRootDict dictionary payload:67:44: error: static_cast from 'TObject *' to 'genfit::Track *', which are not related by inheritance, is not allowed
const Track* getTrack() const {return  static_cast<Track*>(originalTrack_.GetObject());}
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
coreRootDict dictionary forward declarations' payload:24:24: note: 'Track' is incomplete
namespace genfit{class Track;}
^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class genfit::GFRaveVertex with content:
For some unknown reason this works …

R__LOAD_LIBRARY libraries before include files, seems to fix the container behavior

---

common/G4_KFParticle.C
common/G4_Mvtx.C
common/G4_TrackingService.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C

This PR enables HF QA for D0, Lambda_c and Upsilon decays as well as decay finder triggers for them all. The corresponding HF reco must run first so flags are in place which should ensure this can't crash things.
I'm still working on the full sim of the tracking service (almost there) but I had staged a fast sim without realizing which got pulled into this. I decided to do a little work on this so we can use the fast sim for the MDC2

Added HF QA and fast sim tracking service

---

common/G4_Intt.C

The Intt had an overlap with the surrounding black hole when running standalone. The outer envelope had changed with the new support structures, This PR increases the outer radius from ~17.4 to 20 cm. This was read off the display, it can be made a bit smaller but this should be good enough

adjust the outer radius for envelope to new supports

---

common/G4_Micromegas.C

- Allow to configure micromegas radius position from calling macro
- increase micromegas radius from 82 to 85cm to leave room for TPC supporting rods
This is a temporary solution to avoid Geant4 conflicts in https://github.com/sPHENIX-Collaboration/coresoftware/pull/1364 and while waiting for a more permanent Micromegas implementation

increase micromegas radius

---

common/G4_KFParticle.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

There was a clash from KFParticle. My macro used a namespace ```KFParticle``` which apparently is used in the KFParticle software. I changed this to all uppercase and it now works (plus some additions where I forgot the namespace entirely)

Fixed KFParticle clash between macros and compiled class

---

common/G4_Intt.C

Currently if you try to run without the new INTT dead map the macro just exits. This PR adds an if statement to check if the INTT dead map loader should be run at all based on the setting of the `G4INTT::InttDeadMapOption` enum.
Note that this PR does not change the default behavior of running with the dead map enabled, it simply allows one to choose to not run with the dead map if they would like to.

Run without INTT Dead Map

---

common/G4_Micromegas.C
common/G4_Tracking.C

This PR removes all the TPOT/Micromegas configuration options, tile definitions and parameters, as all will be hardcoded in the new geometry implementation. 
Depends on https://github.com/sPHENIX-Collaboration/coresoftware/pull/1400 to run
Is necessary for the coming coresoftware changes to the TPOT geometry

Tpot new geometry

---

common/G4_TrackingService.C

Somehow the part of the MVTX support that connects to the staves is overlapping with the MVTX wrapper. If this part is even 1 micron long it will overlap so this is strange and seems like something else is happening. Regardless, this config stops the overlaps and should help the tracking team

Disable cylinder supports

---

common/G4_Micromegas.C

This PR increases the radius of the surrounding black hole by 2 cm. This is only relevant if the micromegas is running standalone otherwise the black hole radius is determined by the outermost detector (outer hcal)

surrounding black hole cylinder radius needs a 2cm increase

---

common/G4_Input.C
common/G4_TrackingService.C

Missed an ```or``` to pass Sartre generated events to Geant

Patch to use built-in Sartre generator

---

common/G4_TPC.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

root 6.24.06 generates a warning. Since this warning does not exist for gcc it is hard to suppress in the include itself. The underlying includes are from acts which will change with the next acts version. Then we can look for a more permanent solution dealing with this in the acts includes
In file included from ./G4_TPC.C:24:
In file included from /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/release/release_play/play.4/include/tpc/TpcClusterizer.h:7:
In file included from /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/release/release_play/play.4/include/trackbase/ActsTrackingGeometry.h:5:
In file included from /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/release/release_play/play.4/include/Acts/Utilities/BinnedArray.hpp:14:
In file included from /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/release/release_play/play.4/include/ …

Suppress cling warning

---

common/G4_KFParticle.C

at least with root 6.24.06 the missing load generated warnings

load libqa_kfparticle.so and libdecayfinder.so to resolve macro content

---

common/G4_TPC.C

The macro produced a missing lib warning, also move TimeOrderedDistortions.root from private area in /sphenix/user to CALIBRATIONSROOT (we should stop doing this)

need to load libtpccalib.so for TpcDirectLaserReconstruction

---

common/G4_Tracking.C

With the new Acts version, there should be a catch in Acts now which returns an error if the rare track projection to the calos fails. This PR swaps the Genfit track projection module to the Acts track projection module.

Acts Track Projection

---

common/G4_Tracking.C

This PR removes all rave related code from the tracking macro as we do not use it anymore.

Remove RAVE Dependence

---

common/G4_Tracking.C

This PR accompanies coresoftware PR 1459. It removes some obsolete set commands for PHSiliconTpcTrackMatching.

Remove obsolete set commands for PHSiliconTpcTrackMatcher.

---

common/G4_Intt.C
common/G4_Mvtx.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR puts the readout of the intt support and absorber (layer wise support structures) into the ENABLE namespace.
Also adjusted and put the envelope Black hole dimensions back into the MVTX. Please adjust them next time the dimensions change and not just comment this out to "fix overlaps". If they are commented out you cannot run the detector standalone (the black hole envelope is created inside the detector so no particle will reach it).

Intt support

---

common/G4_Input.C

This PR tries that again. Having a default embedding id of 0 is too disruptive and interferes with the pileup analysis. Now the embedid starts at 2 if Enable::EMBED is set to true so the embedded particles can be distinguished from the underlying event

start EmbedId = 2 if Input::EMBED is set

---

common/G4_Input.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR makes the input manager repeat flag accessible from the outside. By default it is set to true so one never runs out of embedding events (the input manager will just repeat the files it read). If one wants to run till the embedding file is exhausted (e.g. embedding pythia8 generated events into a hijing background file), one sets this to false and the number of events to run to 0. This will then process events until the embeddign file is exhausted

Embed repeat

---

common/G4_TPC.C
common/G4_Tracking.C

Moved loading distortion corrections from G4_TPC::TPC_Clustering to G4_Tracking::Tracking_Reco
The reason is that the distortion corrections are actually irrelevant to TPC clustering and relevant for the tracking.
This is particularily important if we split the clustering and the tracking to two different macros
Also added a flag to disable TPC hit_to_cluster association from the steering macro
And a flag to disable initializing the ACTS magnetic field
Both are needed to simplify the clusterize_only macro

Moved loading distortion corrections from G4_TPC to G4_Tracking

---

common/G4_Tracking.C

Do not run anything in tracking chain after PHTpcResiduals when SC_CALIB_MODE is on
Whatever runs is unused anyway. 
The only purpose of running with SC_CALIB_MODE is to produce tracks with distortions on, fit them with the TPC out, and use the residuals to calculate distortion corrections.

Cleanup tracking chain when SC_CALIB_MODE is on

---

common/G4_Tracking.C

This PR splits the G4_Tracking.C macro into a 
- seeding part: Tracking_Reco_TrackSeed()
- tracking part: Tracking_Reco_TrackFit()
This is necessary for writting Job A, B and C macros for our workflow. 
The possibility to run truth_track_seeding is kept. 
The original method "Tracking_Reco()" is kept to minimize disruption on existing macros. It is just a wrapper around the previous two methods

G4 tracking split

---

common/G4_Tracking.C

From https://github.com/sPHENIX-Collaboration/coresoftware/pull/1490 , it will require evaluator to use the high level truth tracking association table, if the table is present on the truth tree. A consequence is that `SvtxTruthRecoTableEval` need to be called before any evaluator calls. As the order is reversed in the default macro, evaluator output lack the track association output. 
This pull request make a quick work around on the macro level: just disable the `SvtxTruthRecoTableEva`, in which case evaluation will still work but trace truth association will analyze through the full reco layers of G4Particle-G4hit-hit-cluster-track
In addition, if `SvtxTruthRecoTableEval` is used, this table should be called before any evaluator calls, as reflected in the order changes. 
To make the …

Adjust order of high level truth table building

---

common/G4_Tracking.C

Companion to coresoftware PR#1511. This removes PHTpcClusterMover from the macro. Its function is replaced by the utility class tpc/TpcClusterMover.

Removed obsolete PHTpcClusterMover.

---

common/G4_Tracking.C

This PR adds the truth-reco DST tables to the QA function. If it is not added, the QA will crash as it looks for the tables but can't find them in the new coresoftware [PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1507).

add tables to QA

---

common/G4_CEmc_Spacal.C
common/G4_Magnet.C
common/GlobalVariables.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds Enable::XPLOAD which will enable reading from our conditions DB. The necessary parameters (tag, config, timestamp) are in the XPLOAD namespace. By default all is off. In our code (until we have a better idea), if a filename is set to CDB it will request the files from the conditions DB. That's so far only implemented for our big fieldmap in the sims and for the cemc profile thesholds

Add xpload

---

common/G4_CEmc_Spacal.C

Moving to enabling the CDB. I don't want to propagate unused options forever. Removing the 1d projective option makes this a lot simpler

remove obsolete 1d projective option to simplify cemc macro

---

common/G4_Micromegas.C
common/G4_Tracking.C
common/GlobalVariables.C

This PR moves the module which creates the ACTS geometry into its own function. It is also used by the micromegas so it makes sure it's just called once. Some micromegas variables had to move to GlobalVariables to make this work. No changes in the top level macros are needed

initialize acts geometry via common function

---

common/G4_Intt.C

Reverts sPHENIX-Collaboration/macros#532
This crashes our evaluator - it needs further investigation before we can use that

Revert "The phi offset of the INTT barrel changed"

---

common/G4_ParticleFlow.C

This PR removes the truth efficiency setter from the particle flow algorithm in conjunction with the change to using reconstructed tracks.

Remove truth efficiency from PF

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

This PR makes the energy source for the hcal towers configurable (energy deposition, ionization energy, raw light output, light output + mephi maps). Default stays light output + mephi maps

make tower_energy_source configurable in Fun4All macro

---

common/G4_CEmc_Spacal.C

This PR enables reading of the RawClusterPositionCorrection parameters from the CDB if Enable::XPLOAD=true

read cluster correctons from cdb

---

common/G4_Mvtx.C

This macros PR implements MvtxHitPruner. It accompanies coresoftware PR#1606. 
It should not be merged until after PR#1606 has been merged.

Add MvtxHitPruner to G4_Mvtx.C.

---

common/G4_CEmc_Spacal.C

This PR adds reading he cdb for g4 subsystems which inherit from phg4detectorsubsystem and its generic reading from the db. It relies on changes in coresoftware - please resync your local coresoftware copy with our master repo

use CDB for phg4detectorsubsystem derived G4 implementations

---

common/G4_Input.C
common/G4_Intt.C
common/G4_Mvtx.C
common/G4_TPC.C
common/G4_Tracking.C
common/GlobalVariables.C

This PR sets a single flag, "TRACKING::pp_mode", in GlobalVariables.C that selects either AuAu or pp running with extended readout. Depending on whether that flag is true or false, the subsystem macros automatically set the pileup time window and the g4hit time windows in the tracking HitReco modules. 
During reconstruction, if the pp flag is set to true, the silicon-TPC track matching takes all bunch crossings. If it is set to false, it takes only crossing zero - the triggered crossing. Temporarily, if the pp-mode flag is set to true, the truth TPC seeding is selected because the CA seeder at the moment does not find seeds that point to large absolute z values - cutting out crossings beyond about 2 microseconds from the triggered crossing. This will be fixed when the CA seeding is …

Set time windows for AuAu or pp running with a single flag

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C

We need to remove crud from our macros instead of leaving obsolete options. The Trackingservice has been obsolete for a while, time for it to be removed from our steering macros. I left the G4_TrackingService.C so existign macros won't crash.
Also the jet reconstruction is now disabled if the modules which produce the required input (the vertex) are disabled, so you don't keep on getting errors from the jet reco just because you disabled the tracking

remove obsolete TrackingService

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds the SyncReco, HeadReco and FlagHandler to the Fun4All_G4_sPHENIX.C macro. The runnumber is set to 1, SyncReco and HeadReco are only called for sims, not when reading from a file. The FlagHandler should always be registered, it reads the flags from the DST (if they exist) and adds them to the recoConst flags. At the End() it saves the flags on the DST (removed flags are discarded).
Fixes a problem in the G4_HcalIn_ref.C/G4_HcalOut_ref.C where phistart was set during the G4 simulation setup. If reading from a DST this is skipped, leading to NAN's in phi of the inner hcal and the phistart value for the old outer hcal in the outer hcal. Now this is set right before the tower reco is set up.

Add common modules

---

common/G4_Bbc.C

This PR fixes the overlap of the bbc cables with the surrounding black hole. The cables stick out 120cm upwards, the black hole radius was adjusted accordingly. If run with other (larger radius) detectors (e.g. sPHENIX) this doesn't matter

fix bbc black hole overlap

---

common/G4_ActsGeom.C
common/G4_Micromegas.C
common/G4_TPC.C
common/G4_Tracking.C
common/GlobalVariables.C

This PR separates the ActsGeomInit() into its own macro. Variables which are used by more than one macro were moved to GlobalVariables.C so macros can be included in random order. That should take care of the observed problems like:
https://chat.sdcc.bnl.gov/sphenix/pl/edugauo5ujd5uytf3fq5rdrxxw

Separate acts geom

---

common/G4_ActsGeom.C
common/G4_Tracking.C

This PR removes the fake surface setter function as a forthcoming coresoftware PR will do this check automatically

Update with no fake surface call

---

common/G4_ActsGeom.C

Return the static check for building of acts geometry, so that we don't run it more than we need to.

Return check for geometry building

---

common/G4_HcalOut_ref.C

This PR makes a minute adjustment for phistart for the outer hcal from gdml to center the tower phi around the geantinos (straight line from vertex)

adjust phistart for fixed outer hcal from gdml

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR makes the gdml based hcals the default The old geometry based hcals can be run by setting
ENABLE::HCALIN_OLD = true;
ENABLE::HCALOUT_OLD = true;
in the Fun4All_G4_sPHENIX.C macro

Gdml hcals

---

common/G4_Tracking.C

This PR updates the G4_Tracking macro to work with the track seed converter for seed specific studies that utilize the evaluation machinery. It also adds a vertexing function which can be called anywhere. It accompanies the coresoftware PR [here](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1669).

Update with TrackSeedConverter

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

This PR adds examples how to change the mephi maps in the macros after they are changed from hardcoded to PHParameters. Added the overlap check option to the inner hcal support rings (let's see how this goes)

Hcal updates

---

common/G4_Tracking.C

Now that the CA seeder works in pp collisions, this removes the switch that defaulted to truth seeding in pp collisions.

Removed default to truth seeding in pp

---

common/G4_Tracking.C

These functions are not used and don't do anything, cleaning up in preparation for commissioning PR

Remove unused functions

---

common/G4_Tracking.C

This PR modifies some of the search windows and associated tunable parameters of the seeding workflow to find track seeds in low occupancy environments. Shown below is the seeding efficiency with this macro where random normally distributed 150 micron misalignment is assigned to each subsystem.
[full_seed_eff_misalignment150micron.pdf](https://github.com/sPHENIX-Collaboration/macros/files/10007159/full_seed_eff_misalignment150micron.pdf)

Tune commissioning search windows

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

This is needed for the fix to the HCal mapping after rotating the detector.

resetting hcal phi starts to zero to be compatible with new hcal mapping

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

This should take care of the small phi shift. It is based on geantinos. To work properly it needs the hcal PR in the coresoftware

phi offset from geantinos for gdml hcals

---

common/G4_Tracking.C

Introduces pp_mode for PHActsTrkFitter, which is necessary for TPC-only track fitting.

Introduce pp_mode switch for PHActsTrkFitter

---

common/G4_Tracking.C

Add a commissioning flag to the fitter to produce alignment information. Off by default.

Add commissioning flag to fitter

---

calibrations/calo/emc_pi0_tbt/Fun4All_pi0tbt_SIMPLE_EMBED.C
calibrations/calo/emc_pi0_tbt/G4Setup_sPHENIX.C

This PR fixes the Fun4All_pi0tbt_SIMPLE_EMBED.C macro so it runs out of the box. One problem in this macro is that it removes the inner detectors, so we do not get e.g. conversions which will likely worsen the pi 0 calibration. I leave this for others to decide

fix macros so they work out of the box

---

common/G4_ActsGeom.C

This PR adds settable (from the main macro) parameters for arbitrarily blowing up cluster covariances in the alignment scheme. This is needed for testing an actual alignment workflow.

Settable calibrator factors

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

Adding in an approximation of the HCal support rings to the simulation. Old versions of the support (currently commented out) have been moved from G4_HcalIn_ref.C to G4_HcalOut_ref.C and updated with dimensions from actual support used in the detector.
The support rings in the detector are aluminum partial rings:
These are approximated as solid rings in the simulation:
A cut out at the top of each ring is done to approximate that in the real detector, based on the phi value where the largest part of the ring ends in the real detector (the 43.17 inch gap shown in the model below).
The rings on each side are implemented as two separate PHG4CylinderSubsystem due to part of the ring being inside the outer HCal envelope and requiring special treatement to avoid overlaps between the ring and …

adding in HCal support rings

---

common/G4_TPC.C

Added macro call to function which changes modulo for CM hit generation. Call sets modulo to 1 so that CM hits will only be generated every event. Corresponding pull request to coresoftware will be submitted shortly. (previously submitted PR on wrong github account, closed that request and resubmitting)

Added event modulo to CM hit generation

---

common/G4_Input.C
common/GlobalVariables.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Follow up to last software meeting discussion: unifying beam parameter configuration selections for pp/pA/AA collisions: 
* Explicitly select the nominal pp/pA/AA collision beam parameter configurations with `Input::BEAM_CONFIGURATION` in the main macro
* The same parameter is applied to event generator, hepmc inputs and pile ups, while it is possible to override for special studies
* Should be compatible with older user macros which default to emulate the nominal AuAu collision beam parameter configuration 
* The QA macro branches may need a sync update after merge to resolve merge conflicts

Unifying beam parameter configuration selections for pp/pA/AA collisions

---

common/G4_EPD.C

This PR adds the EPD_Tiles() to the G4_EPD.C macro whcih runs the epd tile reconstruction. It is not added to Fun4All yet - this will come once this works

Add function which calls the epd tile reco

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This way if the EPD is turned off everything is turned off similarly to the other subsystems.

Add extra flag for epd tile

---

common/G4_HIJetReco.C
common/HIJetReco.C

Adjusting the Jet macros to implement changes made in the jet reconstruction chain in the coresoftware

updated jet macros to use towerinfo objects

---

common/GlobalVariables.C
detectors/sPHENIX/G4Setup_sPHENIX.C

In order to properly interface the macros with the EvtGen for the [newly merged pull request](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1833) to the sPHENIX coresoftware, we create this pull request for the sPHENIX macros.
We add the EVTGENDECAYER class in GlobalVariables.C, which is similar to G4P6DECAYER, to set user defined decay file to customize the EvtGen decay. Also, we add the line 
g4Reco->CustomizeEvtGenDecay(EVTGENDECAYER::DecayFile); 
in the G4Setup_sPHENIX.C to call the user define decay file.
The default value of the DecayFile is an empty string, which means the EvtGen will use the DECAY.DEC from the official EvtGen software. We can find the official EvtGen Decay Table here: 
https://gitlab.cern.ch/evtgen/evtgen/-/blob/master/DECAY.DEC 
User can change the …

Updated with EVETGENDECAYER class to customized user defined decay files

---

common/G4_ActsGeom.C

Forgot to add the commit which removes the function call to `MakeActsGeometry` regarding TPOT building.

Remove MM function

---

CDBTest/README

Clarification in the cdb macro readme

TestCDBInsert sends benign errors when run twice bc existing global tag and payload type

---

common/G4_Bbc.C

This PR adds the bbc sim reco to G4_Bbc.C. It still needs to be enabled in the Fun4All macro, so this should not have any effect on our standard running

Add BbcSimReco if BBCRECO flag is enabled

---

common/G4_Bbc.C
common/G4_Global.C

This PR adds in GLOBAL_VERBOSITY to the Enable namespace so it can be set for our global reco. Set BbcReco verbosity to BBC_VERBOSITY in G4_Bbc.C

propagate verbosity to G4_Global and G4_Bbc

---

common/G4_Tracking.C
common/Trkr_Eval.C

This turns the hit eval to false by default, which drastically improves the speed and output file size of the evaluator. These are expert functions and shouldn't be on by default.

Turn hit eval to false by default

---

common/G4_Tracking.C
common/G4_TrkrVariables.C
common/Trkr_Reco.C

Title says it all.
This affects PHTpcResiduals only

removed calls to obsolete methods and corresponding global variables

---

common/G4_Bbc.C

This PR separates the BBC reconstruction and digitization into two separate modules. Performance is the same, i.e. only one vertex is reconstructed.

Reorganize BBC Reco

---

common/Trkr_Reco.C

Adds missing flag for silicon+TPOT fit after reverting the PR.

Add missing flag

---

common/G4_CEmc_Spacal.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

macro update for this PR:https://github.com/sPHENIX-Collaboration/coresoftware/pull/2026
Also since the evaluator is looking for RawTower objects which are not created in the new stepping action, we only turn on the eval while using the default stepping action for now.

Macro update for new stepping 

---

CaloProduction/Fun4All_CaloProduction.C
common/Fun4All_CaloProduction.C

Macro designed to run the calorimeter reconstruction over PRDF data and produce the towerinfocontainer objects for the EMCal, IHCal, and OHCals. Can run without issue over files that contain any subset of those systems without issue.

Initial Calorimeter Reconstruction Macro

---

CDBTest/CDBUtils.C

This PR adds 2 functions to the CDBUtils macro - cloning a global tag and listing IOVs for debugging

add cloning of tag and listing of IOVs

---

common/G4_HIJetReco.C
common/G4_Jets.C
common/G4_ParticleFlow.C
common/HIJetReco.C

to update macros to work with moving most jet functions from g4jets to jetbase

Move libraries to jetbase (except simulation left in g4jets)

---

CaloProduction/Fun4All_CaloProduction.C

Creates one CaloGeomMapping for each calorimeter. These add the corresponding tower geometry information to the nodetree.

Added calls to CaloGeomMapping in CaloProduction/Fun4All_CaloProduction.C

---

common/GlobalVariables.C
common/Trkr_Clustering.C
common/Trkr_Eval.C
common/Trkr_LaserClustering.C
common/Trkr_QA.C
common/Trkr_Reco.C
common/Trkr_TruthReco.C

The cluster version bloat leaves us open to mistakes or areas of code where the correct version is not properly addressed or propagated. This is a first PR to remove this and use whatever version we are currently using, which our EDM allows us to do anyway to do the base class + version inherited structure.

Remove cluster version

---

common/G4_TrkrVariables.C
common/Trkr_Eval.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

May optionally generate a file with a TTree that recorded which track are matched (and which are not). May additionally put the clusteres of these tracks on the tree, along with which are, and are not, matched.

Option in driving macro to do track matching w/ clusters

---

detectors/sPHENIX/G4Setup_sPHENIX.C

This PR fixes something which has bugged me a long time - it contains old macros which are commented out with a surrounding /* */, means every time I grep for G4_Intt.C, I think there is a macro which still uses this. Since the previous PR will break the QA with merging conflicts in the Fun4All macro, I can just sneak in this other change which will likely break this as well.

remove commented out includes to de-confues grep

---

CDBTest/mycdb.json

This PR adds 
"logger": "terminal",
"log_level": "INFO"
to mycdb.json in the CDBTest area. They are needed for the new client. If someone uses the old client from an old ana build they are ignored (but then the old client cannot read our DB, so this is mute

add two new required entries

---

CaloProduction/Fun4All_CaloProduction_PreQM23.C

This adds the initial commit of the pre-QM production macro. It starts off after the DST creation step in the already-committed CaloProduction module. Production steps:
1. Calibration of each central barrel calorimeter (EMCal+HCals, no ZDC yet)
2. Hot/cold tower masking
3. EMCal clusterization
4. Cluster position dependent correction and residual correction
5. Bad cluster removal
6. Addition of geometry node
Note that for the initial pull request, there is no MBD z-vertex information creation. We are trying to get an officially-sanctioned MBD subsysreco for that.

Initial commit of pre-QM production macro

---

common/QA.C

Following work of https://github.com/sPHENIX-Collaboration/coresoftware/pull/2296 , updating the location for header file `qautils/QAHistManagerDef.h`
PS: It is very interesting this mismatch was not caught in CI check for https://github.com/sPHENIX-Collaboration/coresoftware/pull/2296

New location for `qautils/QAHistManagerDef.h`

---

CaloProduction/Fun4All_Year1.C

From the next build on the mbd will be split into an libmbd_io.so and libmbd.so, so we don't have to load the whole universe when just looking at a DST. The reconstruction needs the libmbd which contains all modules.

use libmbd instead of libmbd_io

---

TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C

This is a macro which unpacks the RawHits from the INTT TPC and TPOT and fills the TrkrHitSets, and then runs an ntuplizer for quick look at the output. There are issues with the INTT and TPOT unpackers that need to be debugged but this allows anyone to take a look at the cosmic data at scale.

feat: add hitset unpacker macro for cosmic tracks

---

TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C

As titled. This will be reported at the end of the Fun4All run and tracked as function of time in the Jenkins CI

Enable per-module time tracking in `TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C`

---

common/G4_TrkrSimulation.C
common/G4_TrkrVariables.C

Remove the (incorrect) setting of offsetphi for the INTT ladders from the macro. The default in the subsystem code is correct. 
This will cause all future simulations to be run with the correct INTT ladder phi offsets.
This does not affect the readback of existing g4hits files, because those files already contain the INTT geometry object that was produced in the simulations. When the READHITS flag is set in Fun4All, the INTT geometry is obtained from the input file.
For reading real data, this macro will produce the correct (ideal) INTT geometry object.

Remove setting of INTT offsetphi from macro. 

---

CaloProduction/Fun4All_Year1.C

This PR adds the header reconstruction (run, event header, sync object and flag saving) to the Fun4All_Year1.C

add header reco to Fun4All_Year1.C

---

TrackingProduction/Fun4All_TrkrClusteringSeeding.C
TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C

Updates the unpacker macro to only create an output hitset dst. Copies the current macro to a new file which can still be checked in the CI. To be discussed at the software meeting today

feat: update unpacker to create output hitset DST

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

When attempting to isolate the tracking portion of the main Fun4All macro from the rest of the modules, it took a while to realize that SvtxEvaluator (part of Tracking_Eval()) requires global reco to run properly; if a global vertex isn't present, SvtxEvaluator silently crashes. The proposed one-line change makes this dependency explicit in the conditions of the TRACKING_EVAL switch; TRACKING_EVAL can now only be on if GLOBAL_RECO is enabled.

Emphasize dependence of SvtxEvaluator on global reco

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

With global_reco not explicitly set before the tracking evaluator, it evaluates to false by default right now. Fixing for nightly qa

fix: order of global_reco

---

common/G4_TrkrVariables.C
common/Trkr_Reco.C

This introduces a function that can call iterative silicon seeding. The second iteration includes the INTT and thus picks up some seeds that couldn't be found due to either leaving <3 clusters in the MVTX or due to some dead areas that we will have to deal with in real data.

feat: iterative siliconseeding

---

common/Trkr_Reco.C
common/Trkr_Reco_Cosmics.C
common/Trkr_TruthReco.C

Moves the seed->track converter out of g4eval so that we aren't accidentally pulling in this dependency, since it only uses reco information.

refactor: move seed->track converter

---

common/CDBUtils.C

This PR just adds the CDBUtils.C macro to our common macros, so we don't have to spread local copies

add CDBUtils.C to common macros

---

common/G4_TrkrSimulation.C

This PR adds Enable::SUPPORT and Enable::ABSORBER to the G4_TrkrSimulation.C so supports and absorbers can be enabled globally

propagate globel support and absorber enable

---

CaloProduction/Fun4All_Year1.C

This adds the CentralityReco and MinimumBiasClassifier modules to the year1 calorimeter production macro. Allowing the CentralityInfo and MinimumBiasInfo nodes to be included into the DSTs.

djl -- Added centrality reco and minimum bias classifier to Year1 macro

---

TrackingProduction/Fun4All_TrkrClusteringSeeding.C
TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C

Adds a preliminary hot map created from early in run 23 for the INTT, still some hot channels present in the cosmics but this is at least a starting point

feat: add prelim hot map

---

TrackingProduction/Fun4All_TrkrClusteringSeeding.C
TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C
common/Trkr_Clustering.C

This adds common hit unpacking functions for any macro to call, so that they only need to be updated in one place.
It also updates the tpc drift velocity in the clustering example macro such that the residuals in z line up better.

feat: common hit unpackers

---

common/G4_Tracking.C
common/G4_Tracking_Cosmics.C
common/G4_TrkrSimulation.C
common/G4_TrkrVariables.C
common/Trkr_RecoInit.C

This PR adds a flag to select the format of the distortion corrections (namely using either radian or cm for the phi distortions), which is the propagated to the relevant modules. 
The default value is "true" which is also what's in the modules, so behavior is unchanged.

Distortion flags

---

common/Trkr_Clustering.C
common/Trkr_Reco_Cosmics.C

Updates cosmic seeding for slightly tighter windows which removes some number of spurious hits in the silicon. 
Adds the preliminary INTT hot map into the hit unpacking by default.
Coupled with https://github.com/sPHENIX-Collaboration/coresoftware/pull/2537

feat: update cosmic seeding

---

common/Trkr_Reco.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Macro changes for pp extended readout running. Adds PrelimDistortionCorrection module that makes preliminary distortion corrections to TPC track seeds after the initial seeding and KFProp fit, refits them and replaces the fit parameters on the node tree before silicon-TPC track matching.

Macro changes to enable distortion corrections in extended readout pp running

---

common/G4_HcalOut_ref.C

Updated G4_HcalOut_ref.C so that the Enable::HCALOUT_RING flag will only turn off the outer section of the HCal support ring (which is replaced with the gdml implementation) and the inner section will always be used

updating so the inner section of HCal support ring is always used

---

common/G4_HcalOut_ref.C

This PR makes the old outer hcal (without parts of the support ring) the current default. Needed to avoid overlaps when the new hcal comes online tomorrow

use old gdml file when full ring in macro is enabled

---

common/G4_HcalOut_ref.C

This PR makes the new inner hcal support ring the default, the old support ring can be selected by setting
Enable::HCALOUT_RING = true;
in the Fun4All macro

make new inner hcal support ring the default

---

common/G4_HcalOut_ref.C

This PR effectively reverts back to the old outer hcal gdml file (and puts the complete old inner hcal support ring back). The new gdml file kills the hits in the outer hcal if the inner hcal is enabled, not sure about the mechanism, the diff shows a magnet volume made of aluminum which didn't exist in the old gdml file

revert back to previous outer hcal gdml file

---

common/G4_CEmc_Spacal.C

The second of three pull requests to add TowerInfoV2 compatibility to simulation. This adds a boolean to the G4CEMC namespace which can be set by the Fun4All_G4_Calo.C module used to steer MC production, which then in turn tells RawTowerCalibration whether or not to store a TowerInfoV2 or V1 object

Updated to include TowerInfoV2 flag for RawTowerCalibration class

---

common/G4_Magnet.C
common/GlobalVariables.C
detectors/sPHENIX/G4Setup_sPHENIX.C

This PR adds the hooks to read the tracking fieldmap via G4MAGNET::magfield_tracking from file or the cdb and adds some safety against inconsistent usage of the global fieldmap and the tracking fieldmap (e.g. not sure how the current macros behave for constant fields). Once the new fieldmaps are in the cdb - this will allow testing of the new fieldmaps even before the tracking fieldmap reading from the cdb is implemented

prepare for fieldmaps from cdb

---

common/G4_ActsGeom.C

This PR enables testing of the new magnetic fields, the field for tracking now uses its own string G4MAGNET::magfield_tracking. WIth this change the new fieldmaps can be tested without interfering with the tracking

use G4MAGNET::magfield_tracking for magnetic field

---

common/G4_Tracking_Cosmics.C
common/G4_TrkrVariables.C
common/Trkr_RecoInit.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Following today's discussion at the distortion meeting workgroup: 
this updates distortion correction flags to allow loading static distortion corrections and average distortion corrections independantly. 
For now, load from files.
Note (@adfrawley , @jdosbo, @pinkenburg etc.): 
if you have modified steering macros that change the correction flags, they will break 
Explicitly one must replace 
- G4TPC::ENABLE_CORRECTIONS  by G4TPC::ENABLE_STATIC_CORRECTIONS 
- G4TPC::correction_filename  by G4TPC::static_correction_filename
One can now also set and load ENABLE_AVERAGE_CORRECTION and average_correction_filename
TODO: 
- MDC macros might need modifications (I can do that if pointed to the right place)
- allow for using CDB instead of hardcoded root file path.

Distortion correction flags

---

common/G4_Magnet.C

Thanks to @pinkenburg , the new field map [[discussed in this notebook](https://nbviewer.org/github/sPHENIX-Collaboration/analysis/blob/master/FieldMap/FieldMapConversion_202404Extension.ipynb)] is now deployed through the CDB and CVMFS. This PR enable it. 
Note to @osbornjd , the tracking field variable is not enabled here yet, which I assume will be done with the tracking field map update in a separate step. 
Making this PR to allow for checking through Jenkins CI first....

Follow up #795, enable the new field map

---

common/G4_ActsGeom.C
common/G4_TrkrSimulation.C
common/G4_TrkrVariables.C

This PR sets the reference radii for the INTT layers to the actual survey values that were implemented into the geant4 geometry. This should make the reconstruction geometry objects consistent

fix: set intt ref radii to survey values

---

common/G4_ActsGeom.C

The magnetic field needed initializing in G4_ActsGeom.C if run outside of the sims (where the magnet will initialize the field)

initialize magnetic field in ActsGeomInit in case we do not run the sims

---

common/G4_CEmc_Spacal.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
common/G4_Jets.C

Somehow the CI did not (and has not?) caught that these include paths are wrong. This apparently only comes up when running some individual macros... this fixes the include paths

fix: qa include paths

---

common/G4_TrkrSimulation.C

An one-line modification to G4_TrkrSimulation.C to load the hot channel map for simulation

Load the hot channel map for simulation

---

SpinProduction/Fun4All_xingshift.C

This macro uses the XingShiftCal class to write spin-related variables to spinDB and CDBTTree.

macro for spinDB and xingshift CDB logging

---

calibrations/tpc/DistortionCorrectionMatrixInversion.C

This PR provides the necessary macro to
- take the agregated distortion correction matrix files from Job A (in our production workflow),
- aggregate and invert them to derive distortion corrections in the TPOT acceptance
- load central membrane 2D corrections 
- extrapolate the 3D corrections from TPOT acceptance to the full TPC acceptance
See https://indico.bnl.gov/event/22887/contributions/90413/attachments/54020/92443/distortion_extrapolation_hp.pdf for details. 
The macro was tested and works. It is ready for inclusion in the tracking workflow.

Job B macro

---

calibrations/intt/Fun4All_Intt_BCOFinder.C
calibrations/intt/Fun4All_Intt_HitMap.C
calibrations/intt/G4Setup_sPHENIX.C

InttBCOFinder
https://github.com/sPHENIX-Collaboration/coresoftware/tree/master/calibrations/intt/InttBCOFinder
InttHitMap
https://github.com/sPHENIX-Collaboration/coresoftware/tree/master/calibrations/intt/InttHitMap
InttBCOFinder won't be used for streaming readout mode.
InttHitMap creates the hitmap distribution and hitmap is used to classify hot/dead/cold channel and so on.
ROOT macro to pick up the bad channel will be added.

Macro to run InttHitMap InttBCOFinder modules added

---

calibrations/mbd/recal_mbd_mip.C

Fixed bug where the text based mbd_qfit.calib (for internal, local use) is now being written out properly.

MBD: now writing out mbd_qfit.calib file

---

TrackingProduction/Fun4All_ZFAllTrackers.C
common/Trkr_Reco.C

This adds a zero field track seeding function and a macro which runs that seeding function and can run either the seed->track converter or the Acts track fitter on the track seeds. Can be used on the zero field data including all the tracking systems

feat: zero field tracking function

---

MvtxProduction/Fun4All_MvtxVertex.C
TrackingProduction/Fun4All_FieldOnAllTrackers.C
TrackingProduction/Fun4All_ZFAllTrackers.C

Call `TrackingInit` instead of just the acts geometry initialization, which includes the distortion initialization also.

fix: call tracking init

---

common/sPhenixStyle.C
common/sPhenixStyle.h

This PR fixes the sPHENIX style macro so it can be included by our code (QAhtml so far)

use quotes for include, put include guard around sphenix style C macro

---

SpinProduction/Fun4All_xingshift.C

This PR handles incorrect run numbers from the gl1 decoder.

xingshift - runnumber error handling

---

common/G4_CEmc_Spacal.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

As agreed in the software meeting - we make the TowerInfov2 the default for the sims. It's needed for the embedding and since it is a superset of v1, code assuming a v1 TowerInfo will keep working with it

create TowerInfoV2 by default

---

validation/calo/plot_nodes.C

Companion macro to make the h_nodes_exists histogram that has the label of nodes for each bins. There are 11 bins with each bin dedicated to nodes name for this histogram. For each event, if the node exists, then the count on that corresponding bins increases by 1. 
Related coresoftware PR: [master](https://github.com/sPHENIX-Collaboration/coresoftware) ([#2789](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2789))

Add macro to plot the h_nodes histogram with labelled nodes per bin

---

common/HIJetReco.C

updating the HIJetReco.C macro to allow for user configured tower node names. This requires the changes in coresoftware in: https://github.com/sPHENIX-Collaboration/coresoftware/pull/2803

making tower prefix configurable

---

TriggerProduction/Fun4All_Prdf_Combiner.C

Thus PR enables the syncing by default for the Fun4All_Prdf_Combiner.C

enable resyncing for triggered readout

---

CaloProduction/Fun4All_Year2.C

Need to find out why Fun4All does not set the timestamp rc flag, this patch here gets us going again

put timestamp back

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Per posted slides at https://indico.bnl.gov/event/23720/ , this gives two lines in the default macro that can be uncommented to turn on the TPC static corrections.  The TPC module edge corrections are already enabled by default.

added steering macro lines to turn on static corrections

---

common/HIJetReco.C

Small change requested in the JSTG to deal with negative energy towers in data. Goes from
`towerjetreco->add_algo(new FastJetAlgo(Jet::ANTIKT, 0.2), "AntiKt_TowerInfo_HIRecoSeedsRaw_r02");`
to
`towerjetreco->add_algo(new FastJetAlgoSub(Jet::ANTIKT, 0.2), "AntiKt_TowerInfo_HIRecoSeedsRaw_r02");`

Change towerjetreco algo to FastJetAlgoSub

---

JetProduction/Fun4All_JetProductionYear2.C
common/HIJetReco.C
common/Jet_QA.C
validation/jet/Fun4All_CaloOnlyJetValid.C
validation/jet/Fun4All_TrackAndCaloJetValid.C

This PR introduces two new changes:
1. Introduces the `Fun4All_JetProductionYear2.C` macro and makes relevant changes to `HIJetReco.C`;
2. Factorizes the jet QA into `Jet_QA.C`, which consolidates all jet-QA related routines into a single macro which can be deployed across multiple Fun4All macros; and finally
3. Updates both example jet QA macros to include modules recently added to the jet QA package in `coresoftware` as well as propagate changes to exisiting modules.

Create Jet Production Macro

---

common/Trkr_RecoInit.C

The macro calls CDBInterface::instance()->getUrl("TPC_Module_Edge") but did not include <ffamodules/CDBInterface.h> and was relying on other includes to include this one

add CDBInterface include

---

common/G4_TopoClusterReco.C

New options for TopoCluster reconstruction:
* ignore hot towers as inputs to TC reconstruction (thanks Antonio!)
* include negative-energy towers (by considering |E| rather than E for the purpose of thresholds)
These have default parameters if not specified by the analyzer, but I make them explicit here in the macro for transparency.

new options for TopoCluster reconstruction

---

StreamingProduction/Fun4All_Stream_Combiner.C
StreamingProduction/make_list.sh

This PR adds a flag to select either the pool based intt input manager or the rcdaq based one. Default is pool based, so this macro will work as before (and therefore doesn't need my PR)

Intt pool flag

---

TrackingProduction/Fun4All_Cosmics.C
TrackingProduction/Fun4All_FieldOnAllTrackers.C
TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C
TrackingProduction/Fun4All_FieldOnAllTrackers_KFP.C
TrackingProduction/Fun4All_ZFAllTrackers.C

TPC drift velocity calibrated values are ready for some of the runs. I modify the macro that allow us to get calibrated TPC drift velocity values from CDB if it is accessible. If no, still use default value.

yuxd: get TPC drift velocity from CDB

---

JetProduction/Fun4All_JetProductionYear2.C
common/Jet_QA.C
validation/jet/Fun4All_CaloOnlyJetValid.C
validation/jet/Fun4All_TrackAndCaloJetValid.C

This PR integrates feedback received during the 07.10.2024 Jet Structure TG, 07.12.2024 Physics Coordination, and 08.12.2024 Production meetings. Also implements a few minor improvements.
**Changes:**
- Moved trigger tag selection to dedicated function
- Added jet singles to default trigger selection
- Added ability to either use a flat minimum jet pt or tie the minimum to the trigger threshold
- Added ability to restrict eta acceptance by jet resolution parameter
- Updated production macro to ingest input lists rather than single files

Integrate 07.10 JS TG, 07.12 PCM, and 08.12 Production Meeting Feedback

---

common/G4_TrkrVariables.C
common/Trkr_Clustering.C

Adds laser clustering to main clustering macro so that it will be run with Job 0 by default. Turned on the laser clustering by default (static correction is needed for the laser matching, which is not done in Job 0, so it is left off by default)

Laser Clustering

---

TrackingProduction/Fun4All_TrackAnalysis.C

As discussed in last week's tracking meeting, here is a macro that one can use to run over the cluster and track seed DSTs. For people who are less familiar with the details of the tracking code, this is a smaller macro that uses the higher level production DST files and just runs the track fitting + tree dump. It is naturally therefore much faster and simpler. You can still choose whether or not to use Acts or a helix fit in the track fitting.

feat: track macro for processing higher level DSTs

---

common/G4_KFParticle.C

I updated KFParticle functions so users dont have to specify true/false anymore which breaks our macros repo
Associated coresoftware PR: [https://github.com/sPHENIX-Collaboration/coresoftware/pull/3103](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3103)

CD: Updated G4_KFParticle to match coresoftware updates

---

common/G4_TrkrVariables.C

Reverts sPHENIX-Collaboration/macros#932 as it wreaks havoc on the QA, need to understand why

Revert "Turn on diffuse laser clustering"

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C
common/G4_TrkrVariables.C
common/Trkr_RecoInit.C

We didn't anticipate using the simulated average spacecharge correction, which is intended to come from direct processing of data, so this pull req adds flags to control reading those files, which were not previously present in the macros.  This also harmonize the naming of the flags used to control the input type for the static correction with those used for the average correction.

allowing radian vs cm control for both static and average maps

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Removes laser call since this is being added into the laser event identifier itself

fix: remove laser call

---

common/G4_Input.C
common/GlobalVariables.C

This PR sets the beam crossing angle to what was used in 2024 (1.5mRad), adds zero crossing angle selection (pp_ZEROANGLE) to select the no crossing angle for our jet triggered calo only dataset

2024 beam xing angle and vertex distribution

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Changes settings of PHSiliconTpcTrackMatching in Fun4All_FieldOnAllTrackers.C. Removes setting of the "use_old_matching" flag - it is only for testing, not for normal use. Changes the pp_mode flag setting so it is not hard coded to true. 
Adds PHTrackCleaner after the Acts track fitter.

Change silicon-TPC matcher settings and add track cleaner in Fun4All_FieldOnAllTrackers.C

---

common/G4_TrkrVariables.C

It is consistent with the default file being loaded. This way you do not need to overwrite it in the steering macro.
It is very confusing to have inconsistent default values in our official macros.
This will be updated consistently with future correction files, whenever available.

Set USE_PHI_AS_RAD to false 

---

common/G4_TrkrSimulation.C

We didn't run any physics data with a 5 mus strobe, so setting 10 mus as the default for now.

fix: extend strobe to 10 mus

---

CaloProduction/Fun4All_Year2_Calib.C

This macro takes the previous caloTreeGen and moves it to the QA section of coresoftware, where it can ride alongside the production and produce nTuples for fast analysis. Some specifics:
For Run 22 it will amount to approximately 60TB of additional output, adding an additional 4% of data. It runs over 100 events from each segment. 
It currently gathers tower-by-tower information for the EMCal, HCal, and ZDC, as well as cluster information from the EMCal. In order to decrease data volume, the following thresholds are in place:
EMCal tower: 0.07GeV
EMCal Cluster: 0.500GeV
OHCal Tower: 0.500GeV
IHCal tower: 0.100GeV
With no cuts on the ZDC information because it has so few towers. Really the EMCal benefits from this cut the most. I will merge the corresponding primary macro and production …

Implementation of caloTreeGen Into QA System

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C
TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C

Set pp_mode flags for CA seeder and KFProp to true always. Call the preliminary distortion correction module before silicon matching always.

Set pp_mode flags to handle distortion corrections properly

---

common/G4_CEmc_Spacal.C
common/G4_Centrality.C

This PR is the next step in getting rid of the PHParameters cdb dependence. Use PHParameterUtils to load PHParameters from the cdb

use PHParameterUtils to load PHParameters from cdb

---

JetProduction/Fun4All_JetProductionYear2_AuAu.C
common/Jet_QA.C

This PR adds a parallel macro for jet QA production in year 2 AuAu production. This follows [coresoftware#3190](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3190), which fixes memory issues with the seed counter.

Add jet macro for year 2 AuAu running

---

CaloProduction/Fun4All_Year2.C
CaloProduction/Fun4All_Year2_Fitting.C

This adds the trigger run info to the Year2 macro. Before anything else to ensure any module that wants to use the trigger info has access to the TriggerRunInfo node. 
At this moment, it prints out the trigger menu with names, prescales and scalers to the output file.

djl -- added trigger runinfo to year2 macro

---

CaloProduction/Fun4All_Year2_Fitting.C

QA module CaloFittingQA (included in coresoftware [here](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3196)) to now be included in Fun4All_Year2_Fitting pass of calorimeter production. Changes to the macro arguments to allow for histogram QA file name in same manner as Fun4All_Year2_Calib macro.

Update to Fun4All_Year2_Fitting macro to include QA module 

---

detectors/sPHENIX/G4Setup_sPHENIX.C

Please do not use #include "" for root macros, this breaks our scheme to override default includes with local copies. Always use #include <>

do not use quotes for includes in root macros

---

StreamingProduction/Fun4All_SingleStream_Combiner.C
StreamingProduction/Fun4All_Stream_Combiner.C

The bco ranges are set automatically based on the strobe width extracted from the daq db now, in conjunction with 
https://github.com/sPHENIX-Collaboration/coresoftware/pull/3211

feat: set MVTX BCO range automatically

---

common/G4_Pipe.C

I've extended the beam pipe to go out as far as our drawings allow. This is for MVTX background studies so we can fire gold ions at all the tapers. I didnt see any overlaps on the overlap check so it should be OK. There is an RF shield inside the bellows that I've not simulated yet but it would be tricky as it extends into multiple regions where we have vacuums

CD: Added more beam pipe info

---

common/Trkr_Clustering.C

This PR gives a unique name to each hit unpacker, in the event that it is needed (e.g. for running parallel streams)

fix: give unique name to each hit unpacker

---

common/G4_TrkrVariables.C
common/Trkr_Clustering.C

Now that we automatically run a DB query for the MVTX to figure out if it is in triggered or streamed mode as part of the pooling and unpacking modules, we should remove this call from the macros

Removed flags to set the MVTX to triggered mode

---

common/G4_Input.C

This PR comments out pythia6 and readeicfiles. eicsmear does not build with alma9 and root 6.32.06, root discontinued pythia6 supprt

comment out pythia6 and readeicfiles for alma9

---

common/G4_PlugDoor.C

The hole in our plugdoors is too large, the implementation accidentally used its diameter as radius

correct plugdoor inner hole (12'' diameter)

---

TrackingProduction/Fun4All_FullReconstruction.C

This puts the laser identifier in the right place and renames the macro to be more descriptive, pending a new macro to run over higher level DSTs. We'd like to move away from people using this macro to reduce confusion, and to have people run over the higher level fixed build DSTs (e.g. cluster DSTs)

fix: laser identifier before tpc clustering

---

common/G4_PlugDoor.C

This PR fixes an overlap of the surrounding black hole with the new plug door absorber. The absorber sticks out a bit, so the black hole needed to grow in z by a few cm

make black hole cover plugdoor absorber if enabled

---

common/Calo_Calib.C

Update Process_calo_calib function to work for both data and MC. Uses reco const TIMESTAMP variable to differentiate between data and MC so TIMESTAMP variable in reco const instance in f4a macro must be set to runnumber in order to do calibrations.

Update Calo_Calib macro to work as both data and simulation calibration afterburner using timestamp

---

common/Trkr_Clustering.C

Trigger mode and streaming mode has to be set before hit unpacking.
In order to use INTT triggered mode data, data taking mode is loaded from database and set the data taking mode in unpacker.

Trigger mode/streaming mode setup added in InttUnpacker

---

StreamingProduction/Fun4All_Stream_Combiner.C
common/Trkr_TpcReadoutInit.C

This separates the tpc readout init part to only include the relevant pieces for the event combiner, so that we don't have to have a db tag for the event combining

fix: run without db tag

---

common/Trkr_TpcReadoutInit.C

As title, the default drift velocity was used in TpcClusterZCrossingCorrection module which should be updated in macro

Set correct TpcClusterZCrossingCorrection::_vdrift in macro level

---

CaloProduction/Fun4All_Year2_Fitting.C

This PR updates the Fun4All_Year2_Fitting.C to use a more recent input file which doesn't generate tons of warnings about missing objects. Removes obsolete set_debug() call (replaced by Verbosity())

new input file, remove obsolete set_debug call

---

StreamingProduction/Fun4All_SingleStream_Combiner.C
StreamingProduction/Fun4All_Stream_Combiner.C

Use https://github.com/sPHENIX-Collaboration/coresoftware/pull/3357 to set the intt bco ranges automatically based on the db setting for triggered or streaming mode

feat: use db to set intt bco ranges

---

common/Calo_Calib.C

- For simulation runs added a default bad tower map that is generated from the average live area of the EMCal over run 24 pp.
- Use of systematic variations are also possible as detailed in the comments.
- Reference (JS TG Update 01/22/25): https://indico.bnl.gov/event/26310/contributions/101677/attachments/59550/102310/01-22-25-Hot-Tower.pdf
- Reference (Calorimeter Calibrations Update 12/09/24): https://indico.bnl.gov/event/25840/contributions/100349/attachments/59034/101381/12-09-24-Hot-Tower.pdf

Calo_Calib.C - Added MC Tower Status for CEMC

---

TrackingProduction/Fun4All_ZFAllTrackers.C

Boundaries set at 3 sigma. Used a fit to the Delta distribution of form: ped+A*exp(-b*|Delta|) to get an equivalent to 3-sigma cuttoff (at 0.9973 percent of the non-pedestal curve).

Update the windows to use the new criteria.

---

common/G4_CEmc_Spacal.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

The current real data based pedestal is an over estimate for the noise level we have in data, this PR scales the pedestal noise level to match the data for 0 mrad and 1.5 mrad crossing data.

Waveform Sim: scale the pedestal noise level to match data

---

common/Trkr_Clustering.C

This PR removes the pruning module from the clustering, as discussed today. It goes with https://github.com/sPHENIX-Collaboration/coresoftware/pull/3409 to produce the results showed in the tracking meeting

feat: remove MVTX pruner

---

common/Trkr_Clustering.C

Reverts sPHENIX-Collaboration/macros#1056
This apparently breaks the QA, meaning we aren't ready to remove it from the simulation yet. Will update the corresponding data macros so that they get into the new build

Revert "feat: remove MVTX pruner"

---

TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_TrackSeeding.C

Update data reco macros to use strobe by strobe seeding and remove mvtx hit pruner

fix: use strobe by strobe seeding

---

common/Trkr_Clustering.C

This should be enough to accomodate extended readout hits.
I will show a few plots at the next tracking meeting.

Increased TPOT timing window. 

---

TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C
TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_TrackSeeding.C
TrackingProduction/Fun4All_ZFAllTrackers.C
calibrations/tpc/TpcDVCalib/Fun4All_FieldOnAllTrackersCalos.C
common/Trkr_Reco.C

This ensures that the TPC cluster's z, used to extrapolate to TPOT, is properly accounting for non zero bunch crossing corrections.
This will improve the beam crossing distribution for tracks matched to TPOT.

properly set pp_mode to PHMicromegasTpcTrackMatching

---

TrackingProduction/Fun4All_TrackAnalysis.C
TrackingProduction/Fun4All_TrackSeeding.C
common/G4_ActsGeom.C
common/GlobalVariables.C
common/Trkr_TpcReadoutInit.C

Accompanies coresoftware PR #3438, should not be merged until after that.
Enables the application of the TPC time zero offset using alignment transforms.

Implement TPC time zero offset via alignment transforms in macros

---

common/SaveGitTags.C

For the sims we want to save the tag/commit id from the mdc2 macros as well. The SaveGitTags() now takes an optional string argument which is saved under MDC2_GITTAG

save git tag given by cmd line

---

TrackingProduction/Fun4All_TrackAnalysis.C
TrackingProduction/Fun4All_TrackSeeding.C
common/Trkr_RecoInit.C

When average corrections are applied, move center of phi matching window to zero.
Add flag to enable linear interpolation of 2D average corrections to 3D.

Set phi matching window conditionally when average corrections applied 

---

calibrations/tpot/ConvertTpotAlignment.C
calibrations/tpot/ExportTpotAcceptanceRange.C

- ConvertTpotAlignment.C Converts translation offsets as provided by e.g. Pedro into global translations suitable for ACTS
- ExportTpotAcceptanceRange.C prints out each TPOT Tile's phi and z acceptance in global coordinates, based on the latest geometry. It is needed for e.g. extrapolating distortions in the full TPC acceptance.
This has no impact on any steering Fun4All macro and can be merged immediately.

Two TPOT utility macros

---

TrackingProduction/Fun4All_TrackAnalysis.C
TrackingProduction/Fun4All_TrackSeeding.C

Updates the track analysis macro to the latest and greatest, and adds the zsize = 1 and max seeds cuts into the seeding propagator

fix: update macros to latest seeding/vertexing

---

common/Jet_QA.C

This PR removes `JetQADefs::GL1::Random` (which I forgot to do after earlier upstream changes).

Bugfix: remove JetQADefs::GL1::Random

---

common/G4_TrkrSimulation.C

This one line change takes care of an overlap between the tpc and the surrounding black hole if the tpc is the outer detector

increase tpc black hole radius to cover the tpc hangers

---

calibrations/tpc/jobB/DistortionCorrectionMatrixInversion.C
calibrations/tpot/ExportTpotAcceptanceRange.C

Need to enable applying MVTX misalignments for the surface mapping to work
It is irrelevant for the rest of the macro, which focuses on TPOT geometry anyway.
Thanks to Xudong for pointing this out.

fix_tpot_calibration_macro

---

TrackingProduction/Fun4All_TrackAnalyzer.C
TrackingProduction/Fun4All_TrackFitting.C

This PR moves the name of the track fitting macro to be more appropriately named, and adds a macro that demonstrates how to run over the QM track DST production

feat: add macro to run over track dst

---

TrackingProduction/Fun4All_ZFAllTrackers.C

1. Using existing ZF cluster DST as default input
2. MVTX misalignment flag as default
3. pp_mode set to true by default
4. update CDB tag
5. remove Misalignment blow up factor
6. comment out hit unpacker and clusterizer (depends on input DST)

fix tracking ZF macro

---

common/G4_CEmc_Spacal.C

Changed the flag for the TowerInfo reconstruction to have objects that can access MC information. With the change the EMCal will follow the same procedure done with the HCal.

Changed CaloTowerBuilder type to kWaveformTowerSimv1

---

common/Trkr_Clustering.C

This macro adds the MvtxClusterPruner in the Mvtx clustering part of the macro, as a replacement for the now removed MvtxHitPruner. 
I'll check the impact on the tracking QA when available, before merging.

added MvtxClusterPruner, as a replacement to the removed MvtxHitPruner.

---

TrackingProduction/Fun4All_PRDFReconstruction.C

Remove unused analysis functions from this macro, which is used for jenkins testing right now

fix: remove unused analysis functions

---

TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_PRDFReconstruction.C
TrackingProduction/Fun4All_TrackFitting.C
TrackingProduction/Fun4All_TrackSeeding.C
TrackingProduction/Fun4All_ZFAllTrackers.C
TrackingProduction/run3auau/Fun4All_PRDFReconstruction.C
TrackingProduction/run3auau/Fun4All_raw_hit_KFP.C

The set_use_legacy_windowing method in the silicon-tpc matcher has been removed in coresoftware PR 3669. This macro change does not change any behavior.

Remove calls to set_use_legacy_windowing in silicon-tpc matcher. 

---

calibrations/calo/hcal_calib_year2/genTSCalib/get_tsFiles_flat.sh
calibrations/calo/hcal_calib_year2/genTSCalib/run.sh
calibrations/calo/hcal_calib_year2/genTSCalib/run_cosmicsTS.C

Add flags to toggle HCALIN and HCALOUT analysis in run_cosmicsTS workflow
Updated run_cosmicsTS.C, get_tsFiles_flat.sh, and run.sh to support these boolean flags for selectively running HCALIN, HCALOUT.

Add flags to run HCALOUT or HCALIN analysis

---

TrackingProduction/Fun4All_Cosmics.C
TrackingProduction/run3auau/Fun4All_raw_hit_KFP.C

Fixed issue that was skipping segment *39 due to issue with identifying TPOT ebdc. Instead of identifying TPC files as ones that contain "ebdc" but not ones that contain "39", still identify as containing "ebdc" but don't include ones that contain "ebdc39"

Fix TPC unpacking skipping segment *39

---

TrackingProduction/Fun4All_FieldOnAllTrackers_KFP.C
TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_PRDFReconstruction.C

If PHActsTrkFitter is run,  then PHActsVertexPropagator must be run also, to get the track DCA values right.

If PHActsTrkFitter is run,  then PHActsVertexPropagator must be run

---

calibrations/tpc/jobB/DistortionCorrectionMatrixInversion.C
calibrations/tpot/ConvertTpotAlignment.C
calibrations/tpot/ExportTpotAcceptanceRange.C

Following Joe's email, prodA_2024 changed into newcdbtag.
@osbornjd there are many macros in our repository that use ProdA_2024 as a tag. Should they all be updated "blindly" ? 
If yes I can easily append it to this PR. 
(the one below are those that I am directly responsible of :))

Fix cdb tag

---

common/Calo_Calib.C

Invoke the isSim flag for the EMCal CaloTowerStatus when the run is simulation.
Related PR in coresoftware: https://github.com/sPHENIX-Collaboration/coresoftware/pull/3741

Update Calo_Calib.C - Propagate isSim flag to CaloTowerStatus

---

common/G4_Pipe.C

This PR forces the beam pipe to be misaligned when the MVTX is misaligned by the 6mm offset. It should allow for us to make this the default, the tracking seems to be okay enough with this change to at least proceed with the more correct material in our simulation

fix: pipe misaligned when mvtx misaligned

---

common/G4_BeamLine.C
common/G4_Pipe.C

This should take care of the overlaps we had between the sPHENIX beam pipe an the forward vacuum enclosure when the beam pipe is misaligned (or better correctly positioned). It's a major cleanup of G4_Pipe.C, the shift is now applied in the initialization (as was the design), replacing all the previous of if(misaligned) blocks. The beam pipe is in fact asymmetric which lead to gaps between the en of the sPHENIX beam pipe and the beginning of the vacuum enclosure (which is made worse with the new shift). The problem is that the forward/backward beam magnets and the zdc's are positioned relative to the vacuum enclosure and closing this gap would mean asymmetric vacuum enclosures with possible changes of the location of the magnets an the zdc. I left this symmetric but if we ever run …

Fix pipe overlap

---

common/Trkr_TpcReadoutInit.C

This is a small changes that creates CDDBTree on the stack rather than heap to access drift velocity and t0. 
Those were never deleted. This fixes a (small) memory leak.

Create CDB tree on the stack to query content. This fixes a memory leak.

---

calibrations/tpot/ConvertCalibrationToJSon.C
calibrations/tpot/ConvertTpotCalibrationToJSon.C
calibrations/tpot/Fun4All_TpotCalibration.C

Two macros are added: 
- One macro to run over TPOT raw (non-zero suppressed, baseline-corrected) data, extract per channel mean and RMS suitable for per-channel threshold determination and store them in the right CDBTree object
- One macro to load a TPOT calibration CDBTree object and convert it to a per FEE threshold suitable for FEE configuration online.

Added scripts to extract pedestal and ZS thresholds from TPOT clock raw data
