macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C

best to wait for the next new build

update macros for magfield rescale setting

---

macros/g4simulations/G4_Svtx.C
macros/g4simulations/G4_Svtx_ITS.C
macros/g4simulations/G4_Svtx_ladders.C
macros/g4simulations/G4_Svtx_maps+strips.C
macros/g4simulations/G4_Svtx_maps+tpc.C
macros/g4simulations/G4_Svtx_pixels+strips.C
macros/g4simulations/G4_Svtx_pixels+tpc.C

This pull request is to follow the coresoftware pull request for the SVTX thresholds. I'll try to organize the merges to that a new build goes through before merging this side.

New SVTX threshold defaults

---

macros/g4simulations/Fun4All_G4_sPHENIX.C

Update Fun4All_G4_sPHENIX.C to include option for using Pythia6 as event generator

Add option to use Pythia6 event generator

---

macros/prototype2/Fun4All_TestBeam.C

Online production macro is now separated from the code development location. See more here: 
https://github.com/sPHENIX-Collaboration/coresoftware/pull/134

Online production macro for T1044 beam test

---

macros/g4simulations/G4_Bbc.C

BBC code base moves to g4bbc from g4vertex.

new G4Bbc library

---

macros/g4simulations/G4_HcalIn_ref.C

Updated comments on parameters for the new flat plate inner HCAL.  This pull request is paired with a corresponding pull request in *coresoftware*.

updated for flat inner HCAL

---

macros/prototype2/Fun4All_TestBeam.C

The lines instantiate the TempInfoUnpackPRDF subsysreco so the temperature gets recorded on the DST.

mlp -- added the temperature info to the macro

---

macros/g4simulations/G4_Svtx_maps+tpc.C

Accumulated updates to the TPC macro, from discussions of the past days:
* Allow a central place to set inner radius for the field cage in ```SvtxInit()```. This is used for both geometry setup as well as when loading the corresponding space charge distortion map from the calibration repository. Lower inner radius seems help reduce multiple scattering effect on the momentum-amplitude resolution too. 
* Correct TPC full length to 160 cm, rather than previous 400 cm. This would help reduce multiplicity in HIJING too. 
* If inner radius of field cage is lower than the inner instrumented-readout radius, add a layer of TPC gas without readout. 
* A central flag to activate / disable space charge residual distortion (```const bool do_tpc_distoration```). Default is DISABLED and NO space charge …

Add option of space charge distortion and use smaller inner radius

---

macros/g4simulations/G4_CEmc_Spacal.C
macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C

Some small changes for the timing interface on the cell recos. Pardon the dust.

new timing window interface

---

macros/g4simulations/G4_Svtx_maps+tpc.C

Changes to the MAPS+TPC macro for the new clustering approach.

TPC Memory Reduction (Macro Changes)

---

macros/g4simulations/G4_Svtx_maps_ladders+intt+tpc.C

Added macro to implement sPHENIX tracker as (maps ladders + INTT + TPC). See pull request 218 for tracking performance plots.

new macro for maps ladders+intt+tpc

---

macros/g4simulations/G4_Svtx_ladders.C

G4_Svtx_ladders.C is modified to be consistent with the latest INTT ladder geometry.

INTT ladder geometry.

---

macros/prototype3/Fun4All_TestBeam.C

See https://github.com/sPHENIX-Collaboration/coresoftware/pull/241

2017 calorimeter prototype production code base

---

macros/g4simulations/G4_CEmc_Spacal.C

macro change needed for coresoftware pull request

use new parameters for cell reco

---

macros/g4simulations/G4_Svtx_maps+IT+tpc.C
macros/g4simulations/G4_Svtx_maps+tpc.C

Contains update for the cylindrical geometry central tracking detectors
Additional update for ladders and true hough will come later

updating constructor call for clusteringTPC

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

This is the macro that was used to generate the performance plots shown in the tracking meeting today.
It has Haiwang's latest initialization of the KalmanPatRec code - it just uses all the defaults.
It runs with the latest new libraries.

latest initialization of KalmanPatRec

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_CEmc_Spacal.C

Added a function into G4_CEmc_Spacal.C to run the CEMC cluster recalibrator. Also added a flag into the Fun4All macro that allows users to run the recalibration.

Updated macros to run with RawClusterRecalibrator

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_HIJetReco.C

(and a small tweak which requires CEMC towers for calo trigger simulation)

Adding HI Jet Reco sub-macro with switch in master macro

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

Also uncommented the track projections module (it works).
Modified the TPC clusterizer parameters to match Carlos new TPC clustering code. The code is a little slower with the new TPC clusterizer, but has much better efficiency and better momentum resolution.

Updated TPC clusterizer parameters to match Carlos new code.

---

macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C

the default for the hcals was adjusted to reflect the changes in their size. Update the - commented out - defaults with the new values

update with new default parameter settings in hcals

---

macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C

just keeping the macro up to date in terms of default values - no functional change

update commented out default for  ncross and tilt angle

---

macros/g4simulations/G4_TPC.C

Just getting the tpc out there, macro not added to any G4Setup macro

implement new tpc

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_EICDetector.C
macros/g4simulations/G4Setup_fsPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_CEmc_Spacal.C

Introduce Pileup simulation and new HepMC input work flow. Works with https://github.com/sPHENIX-Collaboration/coresoftware/pull/364

Pileup simulation and new HepMC input work flow

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_CEmc_Spacal.C
macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C

Update the macros for new calorimeter structure https://github.com/sPHENIX-Collaboration/coresoftware/pull/403 
Plan to merge after PR403 becomes part of nightly build

Update the macros for new calorimeter structure

---

macros/g4simulations/G4_FGEM_fsPHENIX.C
macros/prototype2/Fun4All_G4_Prototype2.C
macros/prototype3/Fun4All_G4_Prototype3.C

Thanks Xu Sun (GSU) for pointing out the prototype and fsPHENIX macros have not been updated to current coresoftware changes. This pull request patch both: 
* Magnetic field setting update in fsPHENIX tracking module following https://github.com/sPHENIX-Collaboration/coresoftware/pull/349
* Calorimeter lib updates following https://github.com/sPHENIX-Collaboration/coresoftware/pull/403 
Further test welcomed.

Accumulated updates on macros

---

macros/prototype4/DisplayOn.C
macros/prototype4/Fun4All_G4_Prototype4.C
macros/prototype4/Fun4All_TestBeam.C
macros/prototype4/vis_prototype3.mac

Preview macro for the data production for the 2018 calorimeter test beam. Calibration files are still place holders, and many aux signals are commented out pending on final channel mapping. 
Details see pull request in https://github.com/sPHENIX-Collaboration/coresoftware

2018 test beam production code

---

macros/prototype4/Fun4All_TestBeam.C

As titled. Getting ready to migrate from test productions to official productions. 
Note, there are calibration constant hardcoded in this macro, which should be migrated to calibration repository when EMCal and HCal calibration arrives.

Accumulated update on 2018 test beam analysis

---

macros/prototype4/Fun4All_TestBeam.C

More information in https://github.com/sPHENIX-Collaboration/calibrations/pull/31

use tower-by-tower calibration for EMCal

---

macros/prototype4/Fun4All_TestBeam.C

update leading order energy calibration constant 
[c_hcal_total_8GeV_uncalib.pdf](https://github.com/sPHENIX-Collaboration/macros/files/1839014/c_hcal_total_8GeV_uncalib.pdf)
before calibration
[c_hcal_total_8GeV_uncalib.pdf](https://github.com/sPHENIX-Collaboration/macros/files/1839019/c_hcal_total_8GeV_uncalib.pdf)
after calibration

update leading order calibration constant

---

macros/prototype4/Fun4All_G4_Prototype4.C

Macro changes needed for new inner hcal prototype

Change to prototype3 for inner hcal, add Al option for Al plates only

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

Modified the tracking macro to use the new TPC digitizer (see coresoftware PR #455).
Tested and working.

Modifications to tracking macro use the new TPC digitizer

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C

New tracking macro to run new INTT and new MVTX code. Tested and working.

New intt new mvtx

---

macros/g4simulations/flowAfterburner.xml

just adding an example flow xml file

add flow afterburner xml file

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_CaloTrigger.C
macros/g4simulations/G4_DSTReader.C
macros/g4simulations/G4_HIJetReco.C
macros/g4simulations/G4_Jets.C

That should be it for the Fun4All_G4_sPHENIX.C and the macros it loads

Root5 root6 combined

---

macros/g4simulations/G4_Tracking.C

Changes to G4_Tracking.C to accommodate the simulations code reorganization (PR#529). The new code will not run without these changes, since module names and include paths were changed.

Tpc sims reorganization

---

macros/g4simulations/G4_Tracking.C

minor change, just including a bunch more include files, needs coresoftware PR to work

root6 needs a few more includes

---

macros/g4simulations/G4_HIJetReco.C

G4_HIJetReco.C was missing an include

add missing include

---

macros/prototype2/Fun4All_G4_Prototype2.C
macros/prototype2/Fun4All_TestBeam.C
macros/prototype2/run_dump.C

adjust hte macros to run under root6 (sim and reco), add dumping macro to generate those ascii lists for comparison

Root6 prototype2

---

macros/prototype3/Fun4All_G4_Prototype3.C
macros/prototype3/Fun4All_TestBeam.C
macros/prototype3/run_dump.C

adjusted the macros to run under root5 and root6

Root6 prototype3

---

macros/prototype4/Fun4All_G4_Prototype4.C
macros/prototype4/Fun4All_TestBeam.C
macros/prototype4/run_dump.C

macros work with root5 and root6

Root6 prototype4

---

macros/g4simulations/G4_HIJetReco.C
macros/g4simulations/G4_Tracking.C

These patches allow us to run this under root6 without having to switch to a specialized branch

Finally fix root6

---

macros/g4simulations/G4_Tracking.C

the G4_Tracking.C macro implements the modularized tracking. The other macros in that branch were outdated which made merging difficult. So I just copied the only relevant macro over

copy G4_Tracking.C from ModularizedTrackReco branch

---

macros/g4simulations/G4_Tracking.C

Reverts sPHENIX-Collaboration/macros#165

Revert "copy G4_Tracking.C from ModularizedTrackReco branch"

---

macros/g4simulations/G4_Tracking.C

Thanks to Yasser and Tony fixing the infinite loop in the modularized track reco module at https://github.com/sPHENIX-Collaboration/coresoftware/pull/612 . Therefore, let's try again to enable the modular tracking as the default tracking reconstruction, following the thread of https://github.com/sPHENIX-Collaboration/macros/pull/165 and https://github.com/sPHENIX-Collaboration/macros/pull/167

Modularized track reco: try2

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_Tracking.C

Changes to G4_Tracking.C to accompany implementation of new tracking containers in coresoftware PR#614

Trackbase implementation

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/Fun4All_ReadBack.C

This PR uncomments the output managers and adds a generic readback macro so we can test if we can actually read the DSTs we produce

Readback check

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking.C

This PR introduces changes in G4_Tracking following up new maps subsystem implementation (coresoftware PR #626)

Modifications needed after new MVTX detector group module

---

macros/g4simulations/Fun4All_G4_EICDetector.C
macros/g4simulations/G4_Tracking_EIC.C

This PR comments out the removed G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C so jenkins does not keep on failing in its tests

comment out eic tracking until it is fixed

---

macros/g4simulations/phpythia8.cfg

This PR just adds the pythia8 configuration needed by PHPythia8 so we can run the macro selecting pythia8 as input

add phpythia8.cfg so pythia8 runs when selected

---

macros/g4simulations/G4_HcalIn_ref.C

Apply Chris's fix for the Al set to false inner hcal. The change to the Fun4All_G4_sPHENIX.C macro needs to be rethought

set material to SS310 if Al is set to false

---

macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4_FEMC.C

This PR adds the complete FEMC reco chain (cell, tower,cluster,eval)

Add all femc

---

macros/g4simulations/Fun4All_G4_sPHENIX.C

This PR restores the original default where the femc is not enabled.

set the femc to false by default

---

macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
macros/g4simulations/G4_Tracking.C

Changes in macros to cover new change in MVTX code

New Mvtx simulation code

---

macros/g4simulations/Fun4All_G4_fsPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

This PR changes the input files used for embedding to files on the phenix web server so this macro can also run remotely

Embed file

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Mvtx.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

Same as https://github.com/sPHENIX-Collaboration/macros/pull/232, but apply to high occupancy tracking QA

Tracking high occupancy qa mvtx

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Tracking_TruthMatching_NumOfClusters.C
macros/QA/tracking/QA_Draw_Tracking_nClus_Layer.C

This PR adds the macro for plotting ncluster/track/layer as also discussed in https://github.com/sPHENIX-Collaboration/coresoftware/pull/805

added macro to plot number of clusters per layer per track.

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_DCAZ.C
macros/QA/tracking/QA_Draw_DCA_Resolution.C
macros/QA/tracking/QA_Draw_DCArPhi.C
macros/QA/tracking/QA_Draw_Utility.C

Adding DCA plots for Z and rPhi directions, DCA resolution plot, and QA_Draw_ALL.sh updated

Adding DCA plots to tracking-low-occupancy-qa branch

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_DCAZ.C
macros/QA/tracking/QA_Draw_DCA_Resolution.C
macros/QA/tracking/QA_Draw_DCArPhi.C
macros/QA/tracking/QA_Draw_Utility.C

Introducing DCA to high occupancy QA

---

common/DisplayOn.C
detectors/EICDetector/DisplayOn.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/EICDetector/G4Setup_EICDetector.C
detectors/EICDetector/init_gui_vis.mac
detectors/EICDetector/vis.mac
detectors/fsPHENIX/DisplayOn.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/fsPHENIX/G4Setup_fsPHENIX.C
detectors/fsPHENIX/init_gui_vis.mac
detectors/fsPHENIX/vis.mac
detectors/sPHENIX/DisplayOn.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C
detectors/sPHENIX/init_gui_vis.mac
detectors/sPHENIX/vis.mac

This PR copies the new Fun4All macros (and their respective G4Setups) into separate directories. They use the commonly installed subsystem macros which makes this much cleaner. The old macros are unchanged and are still under g4simulation. Once this is approved we will use git mv to move the old originals to preserve their history

New macros

---

common/DisplayOn.C
common/G4_Bbc.C
common/G4_CEmc_EIC.C
common/G4_CEmc_Spacal.C
common/G4_DSTReader_fsPHENIX.C
common/G4_EEMC.C
common/G4_FEMC.C
common/G4_FEMC_EIC.C
common/G4_FGEM_fsPHENIX.C
common/G4_FwdJets.C
common/G4_GEM_EIC.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
common/G4_Input.C
common/G4_Jets.C
common/G4_Magnet.C
common/G4_PSTOF.C
common/G4_Pipe_EIC.C
common/G4_Piston.C
common/G4_PlugDoor.C
common/G4_PlugDoor_EIC.C
common/G4_PlugDoor_fsPHENIX.C
common/G4_Production.C
common/G4_Tracking.C
common/G4_Tracking_EIC.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR creates the HepMC input manager in the G4_Input.C InputInit() so options can be set in the Fun4All macro. By default vertex smearing is enabled

Add hepmc options

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
macros/g4simulations/G4_HcalIn_ref.C
macros/g4simulations/G4_HcalOut_ref.C

As discussed in https://github.com/sPHENIX-Collaboration/coresoftware/pull/867

retire zero suppression in the calibration module

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Tpc.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

Resubmitting #268 to merge into tracking-low-occupancy-qa branch

Tpc cluster qa - merging low occupancy branch

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Tracking_RecoTruthMatching.C
macros/QA/tracking/QA_Draw_Tracking_TruthMatchingOverview.C

Updated QA_Draw_ALL.sh and QA_Draw_Tracking_TruthMatchingOverview.C to be able to plot new histograms and added new file QA_Draw_RecoTruthMatching.C to create tracking purity plot

Plotting code for tracking purity and tracking efficiency histograms

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_Tracking_RecoTruthMatching.C
macros/QA/tracking/QA_Draw_Tracking_TruthMatchingOverview.C

Same as #265 but apply to high occupancy QA branch

Step 2/2: Plotting code for tracking purity and tracking efficiency histograms

---

macros/QA/tracking/QA_Draw_ALL.sh
macros/QA/tracking/QA_Draw_DCA_Resolution.C
macros/QA/tracking/QA_Draw_DCArPhi.C
macros/QA/tracking/QA_Draw_SigmalizedDCA.C
macros/QA/tracking/QA_Draw_Tracking_RecoTruthMatching.C
macros/QA/tracking/QA_Draw_Tracking_TruthMatchingOverview.C
macros/QA/tracking/QA_Draw_VertexResolution.C
macros/QA/tracking/QA_Draw_nVertex.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

Adding plotting code for ntracks, gntracks, gntracksmaps, and vertex resolution.
Also added slight changes to Fun4All simulation to include the new vertex tracking class

Plotting code for Vertex tracking class added, Fun4All_G4_sPHENIX.C updated for vertex class as well

---

common/G4_Micromegas.C

Changed default configuration to have full z coverage and one sector

Added enumeration for Micromegas tiles configuration.

---

common/sPhenixStyle.C
common/sPhenixStyle.h

This PR copied the style macros to the common area

Add style macro to common macros

---

common/G4_EPD.C
macros/g4simulations/G4_EPD.C

add flags to perform overlap checks with the EPD (off by default).

epd: add possibility for overlap checks

---

common/G4_TPC.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

See discussion in https://github.com/sPHENIX-Collaboration/coresoftware/pull/915

Macros for TPC endcap in simulation

---

detectors/EICDetector/Fun4All_G4_EICDetector.C

Making the Display easier with 1) add `Enable::DISPLAY` 2), automatically run `DisplayOn()` similar to that of the sPHENIX macro.

Update display for EIC macro

---

common/G4_Input.C

This PR adds the capability to use also listfiles for reading hits and Embedding

Add listfile for dst input managers (readhits and embed)

---

common/G4_Micromegas.C

The "maximal" configuration corresponds to placing two tiles in front of each sector of the TPC and on both sides of the TPC.
This correspond to 48 tiles in total and a nearly full coverage of the acceptance
The "baseline" configuration corresponds to placing one tile in front of  each sector of the TPC and on both sides of the TPC. In one sector of the TPC two more tiles are added in order to have full z coverage. This corresponds to 26 tiles in total.

Added "baseline" and "maximal" configurations for Micromegas tiles

---

README.md
macros/QA/calorimeter/QA_Draw_Utility.C
macros/g4simulations/Fun4All_G4_sPHENIX.C

Reverts sPHENIX-Collaboration/macros#302

Revert "Fix readme"

---

README.md

try this again - this time from the correct branch

fix bad doxygen links, add new location of detector macros

---

common/G4_TPC_EIC.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds the sPHENIX tpc endcap to the eic tpc. By default it is disabled, so the results will not change. But the endcap can be enabled in the Fun4All macro

Add tpcendcap eic

---

common/G4_Input.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

As discussed in the meeting - the HepMC hijing file is now /sphenix/sim/sim01/sphnxpro/sHijing_HepMC/sHijing_0-12fm.dat

New hepmc files

---

common/G4_Tracking.C

This PR prints out the correct shell script to source for all our cvmfs volumes and supported shells

better Tracking warning

---

common/G4_User.C
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds a UserAnalysisInit() function where users can create and register their modules

Add user analysis

---

common/G4_Bbc.C
common/G4_DSTReader.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C
macros/g4simulations/Fun4All_G4_sPHENIX.C
macros/g4simulations/G4Setup_sPHENIX.C
macros/g4simulations/G4_Bbc.C
macros/g4simulations/G4_DSTReader.C

Added MBD/BBC

---

common/G4_User.C

Add Fun4AllServer instance to give users a head start

add Fun4AllServer instance, make it load standalone

---

common/G4_Input.C
detectors/fsPHENIX/Fun4All_G4_fsPHENIX.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR sets a unique embedding id across generators

Uniq embed

---

common/G4_TPC.C
common/G4_Tracking.C

This PR adds in the module to run the space charge residual determination in the Acts track fitting chain.

Space Charge Residuals

---

common/G4_TPC.C

look for default distortion maps in $CALIBRATION_MAIN

---

common/G4_Input.C

This PR adds the flow and fermi motion afterburner to the HepMC input manager. Needs coming Fermi Motion commit o work

Add flow, fermi and listfile for hepmc input mgr

---

common/G4_BlackHole.C

For the mdc we want to disable the forward/backward black holes. This PR adds an Enable flag for that

enable forward black holes separately

---

common/G4_EEMC.C

This PR adjusts the macro for the modified crystal calorimeter, not compatible with the old macro - the eic detector will crash if this is used with the old implementation

Crystal phparameter

---

common/G4_Barrel_EIC.C
common/G4_TPC_EIC.C

This should fix the building of https://github.com/sPHENIX-Collaboration/coresoftware/pull/1009

removed unused and now obsolete headers

---

common/G4_Tracking.C

This PR adds a setting for the magnetic field when running with the TpcTracker seeder. The PR updates the tracking macro such that the Acts tracking default chain works with all combinations of TPC seeders and either running the simulation with the field map or constant 1.4T field.

Update magnetic field for Acts

---

common/G4_Tracking.C

This PR updates the tracking macro with a second fitting pass. The second fit pass improves the DCA by 10-20%.

Update tracking macro with second fit pass

---

common/G4_FEMC_EIC.C
common/G4_FHCAL.C
common/G4_FST_EIC.C
common/G4_FwdJets.C
common/G4_GEM_EIC.C

- adapted several detector systems to be able to configure them at setup time regarding their geometries for EIC studies:
1. FEMC
2. FHCAL
3. EGEM
4. FST
- added first version of forward jet finder (currently only calo based)

Adaptions for more modular running

---

common/G4_Barrel_EIC.C
common/G4_FST_EIC.C

- rewrote BARREL tracker geom setup to be done for each layer separately 
- implemented pitch, geom and geom according to arxiv:2009.0288 for both FST & BARREL setup

added FST and Barrel tracker version according to 2009.0288

---

common/G4_FHCAL.C

The fhcal needs to be set to active now. Minor style change: use {} even for single lines in if blocks, just indenting is too error prone, I have seen to many times users wedging cout statements there and wondering why only the printout is selected

fix for new fhcal implementation

---

common/G4_Tracking_EIC.C
detectors/EICDetector/Fun4All_G4_EICDetector.C

fixed bug that caused the barrel couldn't be registered in G4_Tracking_EIC.C.

Bug fixed in G4_Tracking_EIC.C

---

common/G4_HcalOut_ref.C

fix typo HCALIN -> HCALOUT

---

calibrations/README.md

This PR just adds a calibrations top dir - the calibration macros should go into subdirs here

add calibrations subdir

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

https://indico.bnl.gov/event/10723/contributions/49304/attachments/34285/55606/sampling_fraction.pptx

use sampling fraction from electron sims for no digitization for hcals

---

common/G4_Tracking.C

This PR adds a few flags and variables to the G4_Tracking macro, namely:
- a global string to be able to set the Space Charge reconstruction matrices output filename
- a global flag for MakeActsGeom::add_fake_surfaces
It also addapts the GenFit toolchain to run the Space Charge reconstruction code when SC_CALIBMODE is set to true

G4_Tracking new flags

---

common/G4_ZDC.C

Added ZDC Digitization

---

common/G4_TPC.C

This PR adds the two TPC lasers g4hit generation modules discussed in https://github.com/sPHENIX-Collaboration/coresoftware/pull/1253: 
PHG4TpcDirectLaser and PHG4TpcCentralMembrane
They are controlled by two flags: 
G4TPC::ENABLE_CENTRAL_MEMBRANE_HITS and G4TPC::ENABLE_DIRECT_LASER_HITS
The flags are false by default. 
Setting any to true will enable the corresponding module, adding the relevant G4Hits in TPC_Cells() on top of whatever is already in there, before calling PHG4TpcElectronDrift, responsible for converting G4Hits into Hits

add TPC lasers g4hit generation modules

---

common/G4_Micromegas.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/README.md

Qa tracking mbhijing from Joe Osborn

---

common/G4_Micromegas.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/README.md

Create branch Qa tracking pythiajet

---

common/G4_ZDC.C
common/G4_hFarFwdBeamLine_sPHENIX.C

New method: fbZDCSetup() to build the ZDCs in the hFarFwdBeamLineEnclosure and hFarBwdBeamLineEnclosure.
Added digitization for SMDs.
sPHENIX-Collaboration/coresoftware/pull/1278

build ZDC one at a time. seperated foward and backward mother volume

---

common/G4_Tracking.C

Macro change to accompany coresoftware PR 1281.

Add ghost track rejection module.

---

common/G4_Mvtx.C

Reverts sPHENIX-Collaboration/macros#437

Revert "Revert "Updated MVTX sim for alignment""

---

common/G4_EPD.C

The epd needs to be set to active in the macro

set epd to active

---

common/G4_Tracking.C

Remove the Acts IVF from the macro as we don't use it anymore.

Remove Acts IVF

---

common/G4_Tracking.C

Reverts sPHENIX-Collaboration/macros#448

Revert "Remove Acts IVF"

---

common/G4_Tracking.C

Reverts sPHENIX-Collaboration/macros#447

Revert "Swap to Acts track projection module"

---

common/G4_BeamLine.C
common/G4_Pipe.C
detectors/sPHENIX/DisplayOn.C

This PR should take care of the overlap check failure for the forward beam pipes

Fix beampipe overlap

---

common/G4_TPC.C
common/G4_Tracking.C

Should not be pushed before https://github.com/sPHENIX-Collaboration/coresoftware/pull/1337
this PR
- includes a parameter to alter the drift velocity used in the TPCClusterizer
- allows to configure TPCResiduals histogram saving and output file
- allows to run SC corrections without the Micromegas
- adds the PHTPCDeltaZCorrection module in the reconstruction chain.

Tpc deltaz correction

---

common/G4_Tracking.C

include what you use

---

common/G4_TPC.C

Updates G4_TPC.C to use new Distortion Correction code.
Goes together with https://github.com/sPHENIX-Collaboration/coresoftware/pull/1341

update TPC Distortion Correction code

---

common/G4_Tracking.C

title says it all. This will allow to clean the offline code too.

removed unused include

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

title says it all
thanks to Joe to pointing this out in the first place

enable micromegas by default.

---

common/G4_Bbc.C

Simple change to enable global overlap check in BBC/MBD.

added overlapcheck

---

common/G4_Micromegas.C

added overlap check

---

common/G4_TrackingService.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds the CYSS to the MVTX service material and connects the layers to the service barrel. Some small changes else where to avoid overlaps

MVTX service update

---

common/G4_Intt.C

added the function for loading intt deadmap. Note: g4intt/PHG4InttDeadMapLoader.h is currently not in $OFFLINE_MAIN/include. Running fun4all with this update alone will leads to PHG4InttDeadMapLoader.h not found error.  A separate update on oresoftware/simulation/g4simulation/g4intt/Makefile.am will cure it and pull request coresoftare: #1374 has been made.

G4_Intt.C: update to include deadmap

---

common/G4_Micromegas.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Porting Micromegas QA #403 to master branch, so it will automatically used in all QA runs and user analysis

Porting Micromegas qa #403 to master branch

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR sets the tag and config string for the later use by our conditions DB.

set string flags for later conditions DB use

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR sets sets the correct conditions DB flags (until we change them again)

set correct conditions DB flags

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C
detectors/sPHENIX/G4Setup_sPHENIX.C

This PR prepares the macros for the use of the conditions DB for the magnetic fieldmap

add 64 bit timestamp and cdb option for magnetic fields

---

common/G4_Input.C
common/G4_TrackingService.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

MVTX support has been moved to core software
[Coresoftware PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1440)

Disabled MVTX support

---

common/G4_TPC.C

Updated default distortion and correction files to working combination

---

common/G4_Tracking.C

This PR adds the new module which fills the truth/reco track tables. The new module is introduced in this [PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1465)

Add truth table module

---

common/G4_TPC.C

this is meant for testing purpose when investigating direct laser reconstruction

added flag to run "simple" clusterizer instead of default clusterizer

---

common/G4_Mvtx.C

This PR gives an option to enable streaming readout for the MVTX. A core software PR will appear from Yasser shortly

Enable MVTX SRO mode

---

common/G4_Mvtx.C

Reverts sPHENIX-Collaboration/macros#514

Revert "Enable MVTX SRO mode"

---

common/G4_TPC.C

added central membrane clusterizer and matcher to TPC_Clustering, when running central membrane flashes

added central membrane clusterizer and matcher

---

common/G4_BeamLine.C
common/G4_Pipe.C

Checked and there were no overlaps.

New beam-pipe based on STAR beam-pipe. Original was damaged in fire.

---

common/G4_Pipe.C

I got Dan to get CAD to change the SS pipes to Aluminum, which will reduce material in the far forward regions for mostly the EPD, and a little of the MBD.

Updated with aluminum outer pipes to replace the steel ones

---

common/G4_Tracking.C

This PR updates the truth seeding container names to match the new reconstruction seeding scheme

Change truth seeding container names

---

common/G4_Input.C
common/G4_TPC.C
common/G4_Tracking.C
common/G4_Tracking_Genfit.C

This PR modifies the tracking related macros to match the code changes in software PR #1557. They should be tested together.

Realistic drift velocity

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

This PR addds the geantino based phi offsets to the tower geom of the inner and outer hcals. With a flag  HCALIN_OLD=false the new hcals from gdml are used. With 
G4HCALIN::phistart=...; the phioffset can be changed
G4HCALIN::emin = ... sets the minimum energy for towers (for geantinos set to -10)
same for HCALOUT

add geantino based phi offset, run with gdml hcals on demand

---

common/G4_CEmc_Spacal.C
common/G4_Magnet.C

This PR is a cleanup, using CDB to explicitly access the CDB not needed anymore

CDB access now handled differently - no more CDB string for DB access

---

common/G4_CEmc_Spacal.C
common/G4_Centrality.C

This PR adds 2 more CEmc calibs and the centrality to the ones we can read from the cdb

more uses of cdb

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Commit QA for streaming pp branch and corresponding macro

QA tracking streamingpp

---

common/G4_Intt.C
common/G4_Micromegas.C
common/G4_Mvtx.C
common/G4_TPC.C
common/G4_Tracking.C
common/GlobalVariables.C

add settable global variable to select cluster version

add settable global variable to select cluster version

---

common/G4_Micromegas.C

Fixes a typo issue from PR 556

fix missing subsystem

---

common/G4_Tracking.C

remove obsolete function

---

common/G4_Input.C

This PR removes the retired sartre from G4_Input.C

remove sartre - it is retired

---

common/G4_Tracking.C

This PR adds a commissioning seeding function that can be called from the main macro level. The various parameters that could be further tuned are listed with initial values based on some short studies. The function will allow for further testing and tuning from a broader user base.

Commissioning function

---

common/G4_CEmc_Spacal.C

Minor tweak to point to the new directory containing the new calibration files (Geometry_2023ProjTilted rather than Geometry_2018ProjTilted).

Updated pointer to the new EMCal geometry xml file

---

calibrations/calo/emc_pi0_tbt/Fun4All_pi0tbt_SIMPLE_EMBED.C
calibrations/calo/emc_pi0_tbt/README.md
calibrations/calo/emc_pi0_tbt/newtestscript.csh
calibrations/calo/emc_pi0_tbt/runLCELoop.C
calibrations/calo/emc_pi0_tbt/save_corr_val_add96.C
calibrations/calo/emc_pi0_tbt/save_corr_value2.C
calibrations/calo/emc_pi0_tbt/save_correc_value.C

first check-in of pi0 tower by tower macros

first checkin of pi0 tower by tower calib macros

---

common/HIJetReco.C

Straight forward jet reconstruction module for reconstructing jets following the JS TG recommended procedure. Designed to handle, via enable flags, both data and MC jet reconstructions.

added a new module designed for jet reconstruction with flexability for data and MC

---

CDBTest/README
CDBTest/TestCDBHistos.C
CDBTest/TestCDBInsert.C
CDBTest/TestCDBRead.C
CDBTest/TestCDBTTree.C
CDBTest/mycdb.json

This PR adds an area for testing the CDB with macros and a config file (which needs to be modified)

Add CDB play macros

---

common/G4_TPC.C
common/G4_Tracking.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This PR adds flags to enable filtering of conversion electrons to a new SvtxTrackMap on the node tree.

Filter conversion electrons

---

common/G4_Tracking_Cosmics.C

Macro is in common/G4_Tracking_Cosmics.C. Note that it must be included in _both_ the standard Fun4All macro _and_ common/G4_Micromegas.C to function.

Added standalone cosmics tracking macro

---

common/G4_Tracking.C
common/G4_TrackingDiagnostics.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Pull request related to: https://github.com/sPHENIX-Collaboration/coresoftware/pull/1886

Macro tracking diagnostics

---

common/G4_Tracking.C
common/Trkr_QA.C

Adds a distortion QA function for testing track based distortion residual determinations

Add distortions qa function

---

common/G4_TPC.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

Changes to G4_TPC.C to include calls to new setting functions in CM Clusterizer and matcher.

CM Flash Reco

---

detectors/sPHENIX/Fun4All_G4_sPHENIX.C

changed pt range

---

CDBTest/TestCDBInsert.C
CDBTest/TestCDBRead.C
CDBTest/mycdb.json

This PR updates the CDBTest macros with the new client

update CDB macros for new sphenixnpc client

---

common/Trkr_Reco.C

Fix silicon seeding workflow to work with latest dealignment files

Misaligned Seeding

---

CDBTest/TestCDBRead.C
common/G4_CEmc_Spacal.C
common/G4_Centrality.C
common/GlobalVariables.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This switches our macros over to the new calibrations DB client

remove xpload interface

---

common/G4_Global.C

This PR accompanies
https://github.com/sPHENIX-Collaboration/coresoftware/pull/1990
which refactors the global vertex map object

Refactor global vertex reco

---

CDBTest/TestCDBHistos.C

This is just another update for the CDB macros

clean up CDBTTree and CDBHisto example

---

common/G4_TrkrSimulation.C

Files Affected:
- common/G4_TrkrSimulation.C
Changes:
- option to read laser angles from root file (line 381)
- number of angles from root file, 13802 angles is max (line 382)
TODO:
- general clean up

Adding option to read direct laser angles from root file

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

The macro update for PR: https://github.com/sPHENIX-Collaboration/coresoftware/pull/1998

macro update for the new stepping

---

common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C

This request is in conjunction with my request to edit g4eval/CaloEvaluator.h

allow user to set the value of the event number

---

common/G4_ActsGeom.C

Suppress alignment verbosity

---

CDBTest/README
CDBTest/TestCDBInsert.C
CDBTest/TestCDBRead.C
CDBTest/mycdb.json

This PR updates the macros in CDBTest to work with the new client

Cdb example macros

---

CDBTest/CDBUtils.C

This PR adds the forgotten CDBUtils.C macro

add CDBUtils.C

---

macros/sPHENIXStyle/README.md
macros/sPHENIXStyle/sPHENIXplots.C

PR adds a plotting macro to standardize approved plots plotting scheme. Initiating after recent plot approval process.

add plotting macro

---

CDBTest/CDBUtils.C

This PR just adds clearCache() to CDBUtils

Add clearCache()

---

common/Trkr_TruthReco.C

Updates truth seeding macro to work out of the box

Update truth reco to run

---

common/G4_Global.C

This PR includes GlobalVariables.C in G4_Global.C to resolve Enable::VERBOSITY

include GlobalVariables.C for VERBOSITY

---

InttProduction/Fun4All_Intt_Combiner.C
InttProduction/intt0.list
InttProduction/intt1.list
InttProduction/intt2.list
InttProduction/intt3.list
InttProduction/intt4.list
InttProduction/intt5.list
InttProduction/intt6.list
InttProduction/intt7.list

This PR adds an example how to run the current intt combiner

Add InttProduction

---

common/Trkr_Reco_Cosmics.C

Add cosmics reconstruction macro

Adapt cosmic macro to new macro scheme

---

common/G4_Bbc.C

This needs to be approved before the MBD changes in coresoftware can pass Jenkins, since those changes depend on this.

renamed BbcReconstruction to BbcReco

---

common/Trkr_Reco_Cosmics.C

Update cosmics macro with const field settings so we can turn the field down towards 0T

Update cosmics macro

---

common/Trkr_Reco.C

Update main tracking macro to reflect constant field changes in coresoftware
https://github.com/sPHENIX-Collaboration/coresoftware/pull/2201

Update main tracking macro

---

InttProduction/Fun4All_Intt_Combiner.C
InttProduction/intt_makelist.sh

The PR keeps this up to date, script and macro work, tested with run 20445

update InttProduction with latest macro/script

---

TpcProduction/Fun4All_Tpc_Combiner.C
TpcProduction/tpc_makelist.sh

This PR just adds a directory for the combining of Tpc raw data

Add Tpc Combiner macro

---

CDBTest/CDBUtils.C

This PR updates the CDBUtils.C macro with the new delete functions (handle with care)

add delete functions to CDBUtils.C

---

InttProduction/Fun4All_Intt_Combiner.C

This PR replaces the old intt reader with the new pool based input reader

use intt pool input

---

CaloProduction/Fun4All_CaloProduction_PreQM23.C

- Removed bad local run number look up
- Added CDB interface to handle addition of tower geometry

Update to Calo Production Module

---

TpcProduction/Fun4All_Tpc_Combiner.C
TpcProduction/tpc_makecosmics.sh
TpcProduction/tpc_makelist.sh

This PR is an update of the tpc reading - it now uses the working tpc pool input (Martins pool still coming)

Tpc combiner

---

CaloProduction/Fun4All_Year1.C

This PR cleans up the Fun4All_Year1.C macro

use utility to parse filename for run number/segment, create proper output filename

---

CaloProduction/Fun4All_Year1.C

This PR sets the cdb tag to the latest locked tag

set cdb tag to 2023p002

---

common/G4_TrkrSimulation.C
detectors/sPHENIX/G4Setup_sPHENIX.C

Reverts sPHENIX-Collaboration/macros#695

Revert "Rename intt"

---

CaloProduction/Fun4All_Year1.C

This PR adjusts the Fun4All_Year1.C for the new calo tower builder and calo tower calib

Fix year1 macro

---

CaloProduction/Fun4All_Year1.C

This PR updates the gt of the calo production

set global tag to 2023p003

---

StreamingProduction/Fun4All_Stream_Combiner.C
StreamingProduction/gl1_makecosmics.sh
StreamingProduction/intt_makecosmics.sh
StreamingProduction/make_cosmics.sh
StreamingProduction/tpc_makecosmics.sh
StreamingProduction/tpot_makecosmics.sh

This PR adds the current streaming combiner (Gl1, Intt, Tpc, Tpot)

add streaming combiner

---

MvtxProduction/Fun4All_Mvtx_Combiner.C

minor changes to MVTX combine macro

ycm lowering verbosity and change output file name

---

MvtxProduction/Fun4All_Mvtx_Combiner.C
MvtxProduction/Fun4All_SingleMvtx.C
common/G4_Input.C
detectors/sPHENIX/Fun4All_G4_sPHENIX.C

This adds an option to run Shuhangs hijing flipper (flips every second event to get symmetric z-distributions)

Add hijingflipper

---

TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C

Update macro to add clustering and MVTX after reprocessing of DSTs.

Add MVTX and Clustering

---

TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C
common/Trkr_Reco_Cosmics.C

Reconstructs cosmic tracks on a test 40 event sample, running over a larger sample now.

feat: Update Cosmic Unpacker

---

TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C

Removes filelist option since Jin is setting up jenkins pipelines and we need a stable API (unpacking is too slow to run filelists anyway at the moment).

fix: remove filelist

---

CaloProduction/Fun4All_Year1.C

This PR updates the cdb tag to our current version of calibrations

update cdb tag to 2023p004

---

CaloProduction/Fun4All_Year1.C

Just moving the se->registerSubsystem(clusterCorrection) to where this module is created, clang-format

move se->registerSubsystem(clusterCorrection)

---

calibrations/calo/calib_nov23/towerslope/rings_do_eta_fit2_emc.C
calibrations/calo/calib_nov23/towerslope/towerslope_dst_runner.C
calibrations/calo/calib_nov23/towerslope/tsdst_plus_tsfit.C

macros for fall 23 production-based Emcal calibration

Frantz nov23 1

---

common/Trkr_Reco_Cosmics.C

Update cosmic reco macro to use new cosmic propagation module. Also fixes a bug with the constant field setting

feat: update cosmic reco macro to use new module

---

common/G4_TrkrSimulation.C

This adds the missing mvtx absorber activation if set

Add absorberactive setting for mvtx

---

TrackingProduction/Fun4All_TrkrClusteringSeeding.C
TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C

Updates the cosmic macros with the latest production filepath and some other fixes, e.g.
1. Additional tree creator module
2. clang-format
3. Some comments indicating the purpose of each macro

feat: update cosmic macros with new filepath

---

common/Trkr_Reco_Cosmics.C

This introduces a new cosmic seeding scheme which seems to work pretty well in finding straight tracks while minimizing duplicates.  Goes with https://github.com/sPHENIX-Collaboration/coresoftware/pull/2463

feat: new cosmic seeding scheme

---

CaloProduction/Fun4All_Year1.C

djl -- fixed order of MBC and CentralityReco modules

---

common/G4_TrkrSimulation.C
common/G4_TrkrVariables.C

This PR adds the enabling of hits in the micromegas support structures

Add enabling of support structure hits for micromegas

---

common/Trkr_Reco_Cosmics.C

Updates the cosmic macro to check for field status and run accordingly. In conjunction with https://github.com/sPHENIX-Collaboration/coresoftware/pull/2504

feat: update cosmics macro for nonzero field

---

TrackingProduction/Fun4All_TrkrClusteringSeeding.C

Adds the QA modules to the clustering+seeding macro to be optionally run, also demonstrates how to use the Fun4All QA manager

feat: add qa modules

---

Gl1Production/Fun4All_Gl1_Combiner.C
InttProduction/Fun4All_Intt_Combiner.C
MvtxProduction/Fun4All_Mvtx_Combiner.C
StreamingProduction/Fun4All_Stream_Combiner.C
TpcProduction/Fun4All_Tpc_Combiner.C
TpotProduction/Fun4All_Tpot_Combiner.C

This PR adjusts the new pool input managers to use the subsystem enum from fun4allraw/InputManagerType.h

Inputmgr enum

---

InttProduction/Fun4All_Intt_Combiner.C

This is a corresponding PR to [https://github.com/sPHENIX-Collaboration/coresoftware/pull/2524](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2524).
This will allow analysers to make INTT standalone DSTs with TrkrHits and TrkrClusters for dN/deta and v_n analyses

CD: Made INTT combiner work standalone

---

common/Trkr_TruthReco.C

set magnetic field parameter to relevant modules, to prevent exception when reading

Fix truth reconstruction chain

---

common/G4_TrkrSimulation.C
common/G4_TrkrVariables.C
common/GlobalVariables.C

This PR reads the static and time ordered distortions from the cdb (using new files from Mariia)

Distortions

---

common/G4_CEmc_Spacal.C

Reverts sPHENIX-Collaboration/macros#776

Revert "Updated to include TowerInfoV2 flag for RawTowerCalibration class"

---

calibrations/mbd/Fun4All_MBD_CalPass.C
calibrations/mbd/Fun4All_MBD_Prdf.C
calibrations/mbd/cal_mbd.C
calibrations/mbd/get_runstr.h
calibrations/mbd/plot_calibgains.C
calibrations/mbd/read_dstmbd.C
calibrations/mbd/recal_mbd_mip.C
calibrations/mbd/run_mbdcalpass.sh
calibrations/mbd/runfun4all.sh
calibrations/mbd/update_t0constants.C

macros which run on fun4all output and are used during mbd calibrations.

mbd calibration macros

---

StreamingProduction/Fun4All_Stream_Combiner.C
StreamingProduction/gl1_makecosmics.sh

This PR adds the headreco, sync and flag module so it can be read as a DST without special precautions

Streaming macro 1

---

TriggerProduction/Fun4All_Prdf_Combiner.C
TriggerProduction/cemc_makelist.sh
TriggerProduction/gl1_makelist.sh
TriggerProduction/hcal_makelist.sh
TriggerProduction/make_list.sh
TriggerProduction/mbd_makelist.sh
TriggerProduction/zdc_makelist.sh

This PR adds scripts to create file lists for a given run and a general macro which uses those files to run the combining. Missing files are handled

add TriggerProduction (new combiner macro)

---

calibrations/mbd/Fun4All_MBD_CalPass.C
calibrations/mbd/cal_mbd.C
calibrations/mbd/update_t0constants.C

The final slew corrections sometimes need iterations between the t0 offset corrections and the slew.

added additional iterative slew passes

---

calibrations/mbd/Fun4All_MBD_CalPass.C
calibrations/mbd/recal_mbd_mip.C
calibrations/mbd/run_mbdcalpass.sh
calibrations/mbd/run_qcal.sh
calibrations/mbd/run_slewcal.sh
calibrations/mbd/run_tcal.sh

Added various scripts that generate the calibrations, and some updates to macros.

Mods to prepare for 2024 calibrations

---

StreamingProduction/Fun4All_Stream_Combiner.C
TriggerProduction/Fun4All_Prdf_Combiner.C
TriggerProduction/cemc_makelist.sh
TriggerProduction/gl1_makelist.sh
TriggerProduction/hcal_makelist.sh
TriggerProduction/make_list.sh
TriggerProduction/mbd_makelist.sh
TriggerProduction/zdc_sepd_makelist.sh

create filelists named after the node which ran rcdaq for the prdf combining  (in line with the streaming readout)

Triggerproduction

---

common/G4_ActsGeom.C
common/G4_CEmc_Spacal.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
common/G4_Jets.C
common/G4_KFParticle.C
common/QA.C
common/Trkr_QA.C

Updates QA paths and library names to conform to https://github.com/sPHENIX-Collaboration/coresoftware/pull/2641

refactor: update QA libraries and paths

---

common/Trkr_TruthReco.C

Finish changing magnetic field flages in Trkr_TruthReco.C

---

CaloProduction/Fun4All_Year1.C

Updates Fun4All_Year1 macro to conform to using the Fun4All QA framework

refactor: update CaloValid macro

---

TrackingProduction/Fun4All_TrkrClusteringSeeding.C

fix: update qa libs

---

common/G4_KFParticle.C

fix: qa include

---

calibrations/mbd/calmbd.sh
calibrations/mbd/plot_calibgains.C
calibrations/mbd/recal_mbd_mip.C
calibrations/mbd/run_mbdcalpass.sh
calibrations/mbd/run_mbdlaser.sh

Changed directories to be portable for any user to run, etc.

Updates to run with production calibration

---

CaloProduction/Fun4All_Year2.C

This PR makes the Fun4All_Year2.C macro not crash

make year 2 macro work

---

MvtxProduction/Fun4All_MvtxVertex.C

Adds the Mvtx vertexing macro used to generate the triplet vertex plots.

feat: mvtx vertex macro

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Field on macro that runs with the nominal field map and nominal production seeding workflow. Track matching likely needs to be tuned, but can get us going with silicon/tpc seed containers.

feat: field on macro

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Still asleep, left verbosity on

fix: verbosity off

---

TrackingProduction/Fun4All_FieldOnAllTrackers_KFP.C

Added an adaptation of the field on tracking macro which will perform a K-short reconstruction with KFParticle

Added K-short reco to track prod

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C
common/Trkr_Reco.C
common/Trkr_TruthReco.C

Accompanies https://github.com/sPHENIX-Collaboration/coresoftware/pull/2765

feat: update silicon seeding on real data

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Updates seeding windows to get fully connected tracks and improve TPC seeding efficiency

feat: New seeding windows

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

fix: add flag

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

This fixes the slow down in the CA seeder so that everyone isn't stuck with hanging jobs

fix: caseeder slow down

---

CaloProduction/Fun4All_Year2.C
common/Calo_Calib.C

I will remove the local Calo_Calib.C from CaloProduction after it is installed tomorrow.

adding Calo_Calib to common, cosmetic changes to F4A Y2

---

TriggerProduction/Fun4All_Prdf_Combiner.C

This PR enables the deletion of packets which have a clock counter mismatch

delete bad packets

---

common/G4_TopoClusterReco.C

Reverts sPHENIX-Collaboration/macros#898
It crashes jenkins

Revert "new options for TopoCluster reconstruction"

---

TrackingProduction/Fun4All_Cosmics.C

Generalizes the cosmic reco macro for both field on and field off. Other general improvements using cosmic runs from last month

feat: cosmic reco

---

TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C

We add a new Fun4All macro to do track and calo related analysis.
- tracking
- track projection
- topo cluster reconstruction
Also provide option to do
- TPC-only tracking or full tracking
- TPC drift velocity correction
- EMcal radius correction in track projection

yuxd: Add Fun4All macro for track+calo study

---

common/G4_TrkrSimulation.C
common/G4_TrkrVariables.C
common/Trkr_Reco.C
common/Trkr_TruthReco.C

This PR should match with https://github.com/sPHENIX-Collaboration/coresoftware/pull/3002
This will set the TPC to use 75:20:5 Ar:CF4:isobutane as its default gas mixture. Some strings exist to use other mixtures

Added some flags to run different TPC gas mixtures

---

common/Trkr_Clustering.C

Set to nothing by default so should not modify current default workflow. Will run jenkins anyway to make sure

feat: add option to set unpacker node name

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Added relevant modules to have residuals in the TPC measured with TPC clusters taken out of the ACTS fit.
To enable this one must
- change convertSeeds to false (in the macro arguments) in order to enable full track fit with ACTS
- G4Tracking::SC_CALIBMODE to true (in the macro body) in order  to remove TPC clusters from the ACTS fit and add the PHTpcResiduals module, responsible for extrapolating the acts fit track parameters to the TPC layers that contain a cluster.

TPC residuals

---

calibrations/intt/condor.sh
calibrations/intt/shell.sh

Increased the default number of events in the shell script, adjusted the condor script to put the log file in local subdirectory

(INTT) Increased default number of events from 50k -> 200k for calibrations module

---

common/G4_TopoClusterReco.C

Reverts sPHENIX-Collaboration/macros#900

Revert "Revert "new options for TopoCluster reconstruction""

---

TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C

remove lib which is not in coresoftware

---

common/Trkr_Clustering.C

Changed debug mode to be off by default and removed forced high verbosity

Laser Cluster Debug

---

common/Trkr_Clustering.C

Reverts sPHENIX-Collaboration/macros#917

Revert "Laser Cluster Debug"

---

common/G4_TrkrVariables.C
common/Trkr_Clustering.C

Reverts sPHENIX-Collaboration/macros#913
Reverts as it breaks the sim chain

Revert "Laser Clustering"

---

common/GlobalVariables.C
common/Trkr_Clustering.C

Adds an optional flag to set the zero suppression hit unpacking option in the tpc

feat: add tpc zero supp option

---

TrackingProduction/Fun4All_TrackAnalysis.C

As discussed in the HFTG, let's enable static distortion corrections by default

enable static corrections by default

---

calibrations/tpc/TpcDVCalib/Fun4All_TrackAnalysis.C
calibrations/tpc/TpcDVCalib/README.md
calibrations/tpc/TpcDVCalib/condorJob/condor-data-trkrana.job
calibrations/tpc/TpcDVCalib/run_data_trkrana.sh

In this PR, we provide a new Fun4All macro which use trkr cluster and trkr seed DST files. The processing speed will be much more faster than the previous Fun4All macro which starts from hit unpacker.

TpcDVCalib - use cluster/seed DST

---

BcoQA/Fun4All_Gl1QA.C
BcoQA/Fun4All_TpcQA.C
BcoQA/condor/README
BcoQA/condor/condor.job
BcoQA/condor/create_condorlist.pl
BcoQA/condor/gl1_makelist.sh
BcoQA/condor/intt_makelist.sh
BcoQA/condor/make_list.sh
BcoQA/condor/mvtx_makelist.sh
BcoQA/condor/run_gl1qa.sh
BcoQA/condor/run_tpcqa.sh
BcoQA/condor/tpc_makelist.sh
BcoQA/condor/tpot_makelist.sh

This runs the fast bco dumping into TTrees and has a condorized version to submit full runs

Add bco qa

---

BcoQA/condor/Fun4All_InttQA.C
BcoQA/condor/make_list.sh
BcoQA/condor/run_inttqa.sh

Adds a macro and script to run intt qa bco dump, can be used analogously to the tpc

feat: intt bco dump

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Adds some other tpc qa modules for offline feedback

add other qa modules

---

StreamingProduction/Fun4All_SingleStream_Combiner.C
StreamingProduction/Fun4All_Stream_Combiner.C
TpotProduction/Fun4All_Tpot_Combiner.C

Increased TPOT matching BCO range 5 -> 10 to account for additional offset from ENDAT BCO.

Increased TPOT matching BCO range

---

common/G4_TrkrVariables.C

Turn on the diffuse laser clustering by default

Turn on diffuse laser clustering

---

common/G4_TrkrVariables.C
common/Trkr_Clustering.C
common/Trkr_LaserClustering.C

Changed to a new flag for laser clustering so that old flag is just for turning on generation of lasers hits in sim.

New Laser cluster flag

---

common/G4_TrkrVariables.C
common/Trkr_Clustering.C

Adds calls to the new laser event identifier so that laser events are flagged and info about the time sample of the laser peak are stored

Laser event identifier

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C
TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C
TrackingProduction/Fun4All_FieldOnAllTrackers_KFP.C

As title, related with [coresoftware PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3143)

add laser event identification

---

TrackingProduction/Fun4All_FieldOnAllTrackers_KFP.C

Adjusted macro (doesn't run in current state due to KFParticle_sPHENIX function handle changes from 3 weeks ago)

(TrackingProduction) FieldOnAllTrackers_KFP fix

---

calibrations/intt/macro.C
calibrations/intt/shell.sh

Small changes to shell/macro, removed condor script as it was not compliant with new practices and I am not going to maintain it should they change

(calibrations/intt) Small changes, removed condor submission script

---

common/G4_Input.C

We have a negative beam crossing angle (switched from 2 mRad to -1.5 mRad)

replace 1.5mRad by -1.5mRad xing angle

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

title says it all. 
As per discussion with Tony, Joe, during tracking meeting.

readed preliminaryDistortionCorrection

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

Fit with ACTS by default as we discussed in the tracking meeting today

fix: fit with acts by default

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

We also discussed switching pp_mode to be true in the meeting today. This swaps that flag

feat: switch to pp_mode

---

calibrations/intt/Fun4All_Intt_Calib.C
calibrations/intt/gl1_makelist.sh
calibrations/intt/intt_makelist.sh
calibrations/intt/macro_Calib.C
calibrations/intt/make_list.sh

This PR changes the intt calib macro to use file lists provided by the production. It passes valgrind (a few static memory leaks but no problem)

Intt calib macro

---

TrackingProduction/Fun4All_FieldOnAllTrackers_KFP.C
common/G4_KFParticle.C

I changed some member functions in KFParticle and this change will keep us up to date. I checked this runs locally without complaining.
Requires https://github.com/sPHENIX-Collaboration/coresoftware/pull/3168

KFP: Updates to refelct coresoftware changes

---

StreamingProduction/Fun4All_Stream_Combiner.C
TriggerProduction/Fun4All_Prdf_Combiner.C

This PR adds a protection to the combining macros to prevent them from running without file lists

No input check

---

common/Trkr_TpcReadoutInit.C

... based on discussion with Tony, Xu-Dong.

changed default drift velocity for all Ar/CF4/iC4H10 runs,

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C

increase TPC to TPOT matching windows (0.4/0.3cm -> 3cm)

---

JetProduction/Fun4All_JetSkimmedProductionYear2.C

partition the output to a higher and lower level DST files

Skimmer macro: partition the output

---

common/G4_TrkrVariables.C
common/Trkr_Clustering.C

Added a switch to set MVTX in the triggered mode for HitUnpacking
Corresponding software part: https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

Mvtx triggered mode flag

---

common/G4_TrkrVariables.C
common/Trkr_Reco.C

Moved laser event rejection into new module and made global flag to turn on/off. New function in Trkr_Reco.C to execute this module if flag is on

Laser Event Rejection

---

CaloProduction/Fun4All_HCalCosmics.C

Make the pipeline similar with calofitting and calib for more consistent auto production

update cosmic production macro for auto production

---

common/G4_PlugDoor.C

beam pipe absorber

---

TrackingProduction/Fun4All_FieldOnAllTrackers.C
TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C
common/Trkr_TpcReadoutInit.C

This adds the tpc drift velocity lookup to the tpc readout init function

feat: add cdb drift velocity lookup

---

TrackingProduction/Fun4All_TrackSeeding.C

Made Joe's Requested Changes to TrackSeeding macro

Track seeding

---

common/G4_BeamLine.C
common/G4_Pipe.C

2nd try for extended beam pipe

beam pipe extended, detector id collisions fixed

---

TrackingProduction/Fun4All_ZFAllTrackers.C
common/Trkr_Reco.C

Updated driving scripts for doing zero field track reconstruction and matching.

Updated ZF macro -- meeting with Dave and Tony

---

common/GlobalVariables.C

make TPC baseline correction default

make TPC baseline correction default

---

TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C
TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_TrackSeeding.C
TrackingProduction/Fun4All_ZFAllTrackers.C
calibrations/tpc/TpcDVCalib/Fun4All_FieldOnAllTrackersCalos.C
common/Trkr_Reco.C
common/Trkr_TruthReco.C

Take two.
Values changed only for hte TrackingProductions macros

Tpot matching

---

common/GlobalVariables.C
common/Trkr_Clustering.C

Corresponds to https://github.com/sPHENIX-Collaboration/coresoftware/pull/3299

feat: add t0 hook

---

common/G4_TrkrVariables.C
common/Trkr_LaserClustering.C

New variables to hold the lamination fit output name and debug file name. New function in Trkr_LaserClustering.C that will perform the lamination clustering, which will be put into job0

Lamination Fitting

---

TrackingProduction/Fun4All_ZFAllTrackers.C

Implemented mm_match->zeroField(true);

Implemented the micromegas zeroField flag

---

common/HIJetReco.C

Updates to HIJetReco to allow for user-specified global vertex type in the TowerJetInput of the JetReco modules. Flag in HIJETS namespace to allow for global vertex type to be selected and specified or to use default behavior which is to use the "best" vertex available in the global vertex map. Needs changes to coresoftware from [PR 3316](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3316).

Update HIJetReco macro to allow for user-specified global vertex type

---

TrackingProduction/Fun4All_ZFAllTrackers.C
common/Trkr_Reco.C

Make some changes on ZF macro
1. add lines to turn on distortion corrections, which are off by default
2. set correct convertSeeds in TrackResidual module
3. add preliminary distortion module, which is on by default

ZF macro fix - distortion

---

CaloProduction/Fun4All_Year2.C
CaloProduction/Fun4All_Year2_Calib.C

Updates for gcc 14 (new input file, caloTreeGen does not work with root 6-32, gcc 14)

Caloprod macros

---

TrackingProduction/Fun4All_FieldOnAllTrackersCalos.C
TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_TrackSeeding.C
TrackingProduction/Fun4All_ZFAllTrackers.C

Reverts sPHENIX-Collaboration/macros#1041 per @david-stewart request

Revert "Updatematchwindows"

---

common/Trkr_LaserClustering.C

**Files Affected:**
- macros/common/Trkr_LaserClustering.C
**Changes:**
- L11, L42 - 53. Adding option for simulation direct laser. This was a long time coming and I did not update this when the infrastructure was changed.

Adding option for line laser hits

---

common/CDBUtils.C
common/Calo_Calib.C
common/G4_ActsGeom.C
common/G4_DSTReader.C
common/G4_Global.C
common/G4_HcalIn_ref.C
common/G4_HcalOut_ref.C
common/G4_Input.C
common/G4_Magnet.C
common/G4_Production.C
common/G4_TrkrVariables.C
common/G4_World.C
common/G4_ZDC.C
common/GlobalVariables.C
common/QA.C
detectors/sPHENIX/G4Setup_sPHENIX.C

This PR add fix to some clangs LSP complaints
all changes are mostly cosmetic so they will not break compatibility

ycm - apply clang-format, add missing std and some includes

---

TrackingProduction/Fun4All_PRDFReconstruction.C

Adds qa enabled by default for jenkins pipeline

fix: add QA

---

TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_PRDFReconstruction.C
TrackingProduction/Fun4All_TrackSeeding.C

Adds the line to print the CDB used files at the end of our usual macros

feat: add cdb print

---

TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/make_rawhit_filelist.sh

Updates in prep for run 25 data analysis

feat: update raw hit reco macro

---

TrackingProduction/Fun4All_Cosmics.C

Updates the cosmic macro to run on the latest raw hit production

fix: update raw hit cosmic reco

---

calibrations/mbd/cal_tail.C
calibrations/mbd/make_cdbtree.C

Determine calibration parameters for tail of waveform from prev event.

calibrate tail from prev event pileup

---

TrackingProduction/Fun4All_TrackSeeding.C

This PR:
1. remove silicon misalignment factors
2. add cdb space charge distortion correction
3. reduce vertexing windows. These still should be tuned/studied
4. add vertex propagation module to get final track position

feat: update seeding macro

---

common/HIJetReco.C

Add tower_prefix switch to HiJetReco macro.

add tower prefix to rho calculation

---

TrackingProduction/Fun4All_TrackAnalysis.C
TrackingProduction/Fun4All_TrackSeeding.C

Increases PHSimpleVertexFinder windows a bit. Adds ~ 5-10% more vertices.

Open up vertex finder cuts a bit.

---

JetProduction/Fun4All_JetProductionYear2.C
JetProduction/Fun4All_JetProductionYear2_AuAu.C
JetProduction/Fun4All_JetProductionYear3.C

As stated, this PR adds the year3 jet macro. Also corrects a couple of inaccurate comments in the year2 jet macros.

Add year 3 jet production macro

---

common/G4_TrkrSimulation.C

Reads mvtx misalignment from cdb file provided by @hrjheng 
Accompanies https://github.com/sPHENIX-Collaboration/coresoftware/pull/3481

feat: read mvtx misalignment from cdb

---

TrackingProduction/Fun4All_TrackAnalysis.C

Set the mvtx geom flags to use the updated Acts geometry infrastructure

fix: set mvtx geom flags

---

TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_TrackSeeding.C

This updates our other macros to use the mvtx geometry

update: macros to use mvtx geom

---

common/Trkr_Reco_Cosmics.C

Improves speed of cosmic seeder in current cosmic data with stuck on stupid channels

fix: use adc cut by default

---

common/G4_RunSettings.C

Let's try this again - this adds the settings for simulation run 23 (AuAu)

add run23 (AuAu) settings

---

common/Jet_QA.C

add switches to add only towers or tracks based on the need; add switches to select background subtracted/not-background subtracted inputs, and turn on/off modules as needed

add switches to distinguish calos and tracks, raw and subtracted inputs

---

TrackingProduction/Fun4All_Cosmics.C

This fixes the cosmics macro to use the laser ID correctly. It also updates with some flags that are needed now

fix: cosmics macro uses laser finder correctly

---

CaloProduction/CreateListFiles.pl
CaloProduction/Fun4All_New_Year2_Fitting.C

This PR adds a script CreateListFiles.pl which creates the file list which is need to run Fun4All_New_Year2_Fitting.C:
CreateFileLists.pl will produce a list file which can be read into
the Fun4All_New_Year2_Fitting.C macro
usage: CreateFileLists.pl <runnumber> <segment> <tag>
tag is e.g. new_nocdbtag_v003
Using this one can just run
root.exe -q -b Fun4All_New_Year2_Fitting.C\(10\)

add macro to process seb wise combined files

---

StreamingProduction/tpc_makelist.sh
TrackingProduction/run3auau/Fun4All_PRDFReconstruction.C
TrackingProduction/run3auau/gl1_makelist.sh
TrackingProduction/run3auau/intt_makelist.sh
TrackingProduction/run3auau/mvtx_makelist.sh
TrackingProduction/run3auau/tpc_makelist.sh
TrackingProduction/run3auau/tpot_makelist.sh

This puts a macro and sh scripts to process the tracking directly from the prdfs in preparation for AuAu running

feat: process run25 files from prdfs

---

CaloProduction/Fun4All_New_Year2_Fitting.C
common/G4_RunSettings.C

This PR adds run 28 (pp zero deg xing angle), 29 (1.5 mRad xing angle) and  run 30 (AuAu 1mRad xing angle)

Newsim runs

---

TrackingProduction/Fun4All_Cosmics.C

Updates the cosmics reco macro to read in 48 input tpc raw hit files

fix: read 48 files

---

TrackingProduction/run3auau/Fun4All_raw_hit_KFP.C

This fixes syntax and other bugs that prevent this macro from being run out of the box

fix: bugs in run3auau macro

---

TrackingProduction/run3auau/Fun4All_raw_hit_KFP.C

Makes the QA modules turnkey and work out of the box in the run3auau macro

fix: turnkey QA

---

TrackingProduction/Fun4All_FullReconstruction.C
TrackingProduction/Fun4All_TrackAnalyzer.C
TrackingProduction/Fun4All_TrackFitting.C
TrackingProduction/Fun4All_TrackSeeding.C

Updates the production files and cdb tag for our slate of pp macros running on raw hits and up

fix: update production files and cdbtag

---

common/CDBInsertUtils.C

CDBInsertUtils.C contains utility functions which make inserting calibrations with readback confirmation and md5sum check easier

add utilities to insert calibrations safely (with readback and md5sum check)

---

calibrations/calo/emcal_calib_year1/Fun4All_EMCal.C
calibrations/calo/emcal_calib_year1/base/genCalib.sh
calibrations/calo/emcal_calib_year1/base/run.py
calibrations/calo/emcal_calib_year1/doFitAndCalibUpdate.C
calibrations/calo/emcal_calib_year1/doTscFit.C

- Updated the old EMCal Calibration macros with the current working ones.
- Added driver scripts to automate the calibration procedure over multiple iterations.

Update EMCal Calibration Macros / Scripts

---

TrackingProduction/Trkr_LaserClustering.C
common/G4_TrkrVariables.C
common/Trkr_Clustering.C
common/Trkr_LaserClustering.C

Modifications to add toggle for fitting of laser clusters. Also added runnumber function in laser event identifying so that new GL1 bit isn't used in runs before it was implemented

Laser cluster fitting

---

JetProduction/Fun4All_JetSkimmedProductionYear3.C

Implemented beam background module in JetSkimmedProductionYear3. Changed test file to newcdbtag_v007.

Add beam bkgd production

---

common/Calo_Fitting.C

This PR enables the template fitting for the sepd as desired

sepd wants to use template fit

---

common/Calo_Fitting.C

Reverts sPHENIX-Collaboration/macros#1179

Revert "sepd wants to use template fit"

---

CaloProduction/Fun4All_New_Year2_Fitting.C

This apply the module that check if all packet in the event is good, if not it abort the event

add calopacketskimmer to fitting macro

---

JetProduction/Fun4All_JetSkimmedProductionYear3.C
common/Jet_QA.C

Updated the fun4all for slight adjustments to use DST_CALOFITTING

making adjustments for golden run testing
